### ISSUE TITLE
Post processor applied to all output layers instead of specified layers in the model-proc json config file

### ISSUE THREAD

**Issue by tunght** [dlstreamer/dlstreamer#186]
Hi there

I have this setting in the model proc .json file for a detection model
"output_postproc": [
    {
      "converter": "tensor_to_bbox_ssd",
      "layer_name": "boxes"
    }
  ]

What I understand is that gvadetect would apply the converter to only the output layer named "boxes", but it actually apply the converted to all output layers 

In this line of code the all output_blobs is put into the process function of the converter
https://github.com/openvinotoolkit/dlstreamer_gst/blob/a644d52ab9af0932673fd77b028a05e246c339a1/gst/inference_elements/gvadetect/detection_post_processor.cpp#L147

Does it intent to do so? 

Thank you
Tung

**Comment by mliu2020** [comment]
Hi @tunght,

This is a good question, let me contact with dev team.

How about the result, did you get any result?

Mark

**Comment by tunght** [comment]
Hi Mark,

No, it doesn't work because one of the layers doesn't follow the SSD output format so the process function throws error. It never gets to the right layer. I modified the code to filter the right layer and it works fine

Thanks

**Comment by mliu2020** [comment]
Thanks for the detailed debug info.

This seems a prove that the process function applies to the wrong layer. I will forward this info to dev team.

Just curious, there are other methods to do the post-proc as described by following article,
https://openvinotoolkit.github.io/dlstreamer_gst/

These methods requires call-backs or re-design plugin, do these methods work for you?

Mark

**Comment by tunght** [comment]
Thank you Mark,
Yes, I actually added a new Converter to to parse the raw output blob from my models, it's working fine for me. I just wanted to report this as I think it might be helpful for others

Thanks

**Comment by mliu2020** [comment]
Hi @tunght,

Thanks for the good input. We have discussed internally and we will add a feature so the convert will apply to the specific layer as you described.

Your contribution helps us for a good product.

Mark

**Comment by tunght** [comment]
Thank you Mark. That is a great news, i'm happy to help
