### ISSUE TITLE
vaapi-surface-sharing is outperformed by vaapi pre-process-backend on iGPU

### ISSUE THREAD

**Issue by adranit** [dlstreamer/dlstreamer#195]
On system with iGPU using of vaapi-surface-sharing pre-proc shows worse performance than vaapi pre-proc.

Affected version:
2021.2

Workaround:
Use vaapi pre-proc instead of vaapi-surface-sharing.

**Comment by gsilva2016** [comment]
@adranit does this workaround still implement zero-copy (gpu decode to gpu inference with no memory copy) ?

**Comment by adranit** [comment]
Hello @gsilva2016,
No, the workaround does not implement zero-copy.
