### ISSUE TITLE
Grayscale input

### ISSUE THREAD

**Issue by b04505009** [dlstreamer/dlstreamer#201]
I would like to use only 1 channel as my model input, but element like gvadetect seems not support GRAY8 as sink format. Do you have a plan to support this or is there any work around? Thank you.

**Comment by jayer95** [comment]
+1

**Comment by mliu2020** [comment]
Hi @b04505009,

Sorry for the late response, let me ask if we have a plan or work around.

Mark Liu

**Comment by c37102001** [comment]
+1
