### ISSUE TITLE
2-stage detection by roi-list

### ISSUE THREAD

**Issue by b04505009** [dlstreamer/dlstreamer#206]
Hi, I would like to ask that if I have 2 stages detection, like
gvadetect1 -> gvatrack -> gvadetect2
then how can I know a bbox in gvadetect2 is detected from which bbox in gvadetect1?
For now I use bbox's location to determine that, but I think it could be more efficient to keep this information when inference from roi-list.
Thank you

**Comment by mliu2020** [comment]
Hi @b04505009,

Thanks for creating a new issue.

I didn't try roi-list yet, but could you attached a tag to the roi list of the first gvadetect?

Mark

**Comment by b04505009** [comment]
Hi @mliu2020 ,

I'm not sure how to add a tag to the roi-list, could you provide more details about this?

Also, I have a glance of this code https://github.com/openvinotoolkit/dlstreamer_gst/blob/4a8b37a81b4f8362899d3521bcabe5ecaec97014/gst/inference_elements/gvainference/inference_post_processor.cpp#L45-L62

Seems it just pushes all results into a vector. I doubt that the tag information can be kept.

**Comment by mliu2020** [comment]
Hi @b04505009,

Sorry for the late response, I am not sure if the tagging works either.

I had some discussion with team, since you have gvatrack between gvadetect elements, could you try to distinguish between the results of the first and second detection by the presence of ‘object_id’ property? If you can do this, you may determine which bbox from gvadetect2 is related to which bbox from gvadetect1.

You can find the object id from [this document](https://github.com/openvinotoolkit/dlstreamer_gst/wiki/Object-tracking#how-to-read-object-unique-id).

According to the gvatrack doc, the object ID seems to be only applied to zero-term mode.

The other solution may be to distinguish by the roi location?

Mark

**Comment by b04505009** [comment]
Hi @mliu2020,

Yes I can distinguish which roi is from first gvadetect by object_id because the roi from the second gvadetect would not have this property. However, I'm still not able to determine the matching between the roi from first and second gvadetect. 

I'm now using the location to determine this matching, but I think keeping that information when using roi-list can be more efficient, since we can avoid computing the roi intersection for every frame.

Thank you.

**Comment by mliu2020** [comment]
Yes, I agree.

I didn't use two stage of roi yet, but I think the roi from second doesn't keep its parent roi info.
I think the only working method is the location algorithm but it could cost performance.

Let me discuss with developer and see if they have different idea, 

Mark

**Comment by Sharan-Sundar** [comment]
Any updates on this @mliu2020  ? I am also using gvadetect1 -> gvatrack -> gvadetect2 and facing the same issue. Any time estimates for this enchancement ?

**Comment by adranit** [comment]
Hi @Sharan-Sundar , no updates yet.

**Comment by Sharan-Sundar** [comment]
Does the latest release 2022.1 support this enhancement ?

**Comment by mikhail-nikolskiy** [comment]
Yes, starting Release 2022.1 the bounding box generated by gvadetect2 has field 'parent_id' in GstVideoRegionOfInterestMeta (or GVA::RegionOfInterest::_meta()->parent_id) referencing id of "parent" bounding box generated by gvadetect1 (field 'id' or GVA::RegionOfInterest::region_id()).

**Comment by Sharan-Sundar** [comment]
Thats great !! I ll try it out and close this issue.

**Comment by Sharan-Sundar** [comment]
Hey, @mikhail-nikolskiy 
I tried your suggestion. Correct me if I am wrong, my current pipeline is - 
`gst-launch-1.0 filesrc location=/home/user/vid.mp4 ! decodebin ! videoconvert n-threads=4 ! capsfilter caps="video/x-raw,format=BGRx" ! gvadetect model-instance-id=vehicle0 model=vehicle.xml inference-interval=2 threshold=0.4 ! queue ! gvatrack tracking-type=short-term ! queue ! gvadetect model-instance-id=plate0 model=plate.xml threshold=0.5 inference-interval=1 inference-region=roi-list ! queue ! gvawatermark name=gvawatermark ! videoconvert n-threads=4 ! fpsdisplaysink video-sink=xvimagesink sync=false`
Here, I use a callback at `gvawatermark` and access `GstVideoRegionOfInterestMeta`. I am able to get the `region_id `and `parent_id` of `gvadetect2` here. How do I get the `parent_id` of `gvadetect1 `? Should I get a seperate callback after `gvadetect1` ? Is it the most efficient way or am I missing something ?
Looking forward to your response.

**Comment by akwrobel** [comment]
Closed due to age
