### ISSUE TITLE
Can MQTT be used as a method in gvametapublish on Windows Platform?

### ISSUE THREAD

**Issue by Rasmita-Ardu** [dlstreamer/dlstreamer#219]
I need to use MQTT for gvametapublish. I couldn't find any relevant information related to installation on windows. kindly guide me.

**Comment by mliu2020** [comment]
Hi @Rasmita-Ardu,

In the limitation section of the [Windows installation guide](https://github.com/openvinotoolkit/dlstreamer_gst/wiki/%5BPreview%5D-Windows-Install-Guide), I saw a line in the limitation sections:
> gvametapublish works only with filesystem and console output

I believe this means MQTT doesn't work on Windows yet. But let me double check.

Mark

**Comment by Rasmita-Ardu** [comment]
Any idea how to use this [guide](http://www.steves-internet-guide.com/install-mosquitto-broker/) to install MQTT ? 
I want to use gvametapublish using MQTT

**Comment by mliu2020** [comment]
@Rasmita-Ardu,

I never use it and from the document, it seems straightforward.

If I were you, I would first understand how the MQTT broker works and run some sample code, then it would be easier to figure out how to connect with DL Streamer.

But since it isn't enabled it Windows, it seems not working even you have MQTT installed. So you might try Linux version first and see how they work together, it would be easier once you understood how.

Mark Liu

**Comment by Rasmita-Ardu** [comment]
Thanks @mliu2020 ! 
I am working on getting MQTT installed for linux to understand the working better.

**Comment by mliu2020** [comment]
Thanks @Rasmita-Ardu for understanding the situation,

Can you brief describe your requirements including the MQTT installation steps? And if possible, some of the benefit of MQTT to your solution.

This way, I can put this into our backlog so we will consider to implement this in the future release.

Mark

**Comment by mliu2020** [comment]
@Rasmita-Ardu,

Before I close this post, I want to make sure if you still want this be the feature request?

I would be appreciated if you can brief describe the reason to enable MQTT, are you thinking a product or just personal interest? Any reason that you want MQTT instead of Kafka or other tools?

Mark

**Comment by Rasmita-Ardu** [comment]
@mliu2020 , Apologies for reverting back late. 

Yes, It would be wonderful if you could release the feature which enables MQTT and Kafka as elements in gvametapublish for Windows. 
I would like to transmit the metadata from dlstreamer to my application via MQTT/Kafka which ever is lightweight and apt for my project ( after testing both of them ). 

To answer your question of `Can you brief describe your requirements including the MQTT installation steps? ` 

I did lot of research to understand the installation steps for MQTT in windows and linux platforms. 
I see, there is install_metapublish_dependencies.sh file which installs MQTT library and we can use it to build dlstreamer using the command cmake .. -DENABLE_PAHO_INSTALL=ON. 
![image](https://user-images.githubusercontent.com/34830728/127275105-c958c1de-28cb-4ba8-ad19-eafe25782668.png)

So, I would appreciate if [source code](https://github.com/eclipse/paho.mqtt.c) could be built as a library for windows. I tried building it on my end using the following command
![image](https://user-images.githubusercontent.com/34830728/127275555-2bdef680-48cc-4edb-8340-9564d4afa2ed.png)

However, its not getting built and there were some error messages. 

Thanks,
Rasmita

**Comment by mliu2020** [comment]
Thanks for the input,

I have submitted this as a feature request.

Mark

**Comment by Rasmita-Ardu** [comment]
@mliu2020 , I figured out to enable MQTT support for windows. However, I was trying to create a PR and today and realized that in https://github.com/openvinotoolkit/dlstreamer_gst/blob/master/CMakeLists.txt, 
Only UNIX Support is mentioned unlike UNIX and Windows support in version 1.4.0. 
![image](https://user-images.githubusercontent.com/34830728/141466861-5d2b8dde-7b29-4abd-882b-89d615fd7727.png)

Can you tell me if the windows support is withdrawn permanently ? If Yes, then how should I push my changes so that users can benefit from the MQTT-Windows feature ?

**Comment by Rasmita-Ardu** [comment]
@adranit @openvino-pushbot . Can anyone comment on the above issue I posted ?

**Comment by adranit** [comment]
Hi @Rasmita-Ardu , 
Sorry for late response. We published "support for windows" on separate preview branch (https://github.com/openvinotoolkit/dlstreamer_gst/tree/preview/support-for-windows) and it has not been merged in main branch yet. Could you change the target branch to "preview/support-for-windows"?
