### ISSUE TITLE
gvatrack-GPU performance drops comparing with CPU implementation

### ISSUE THREAD

**Issue by wdkwyf** [dlstreamer/dlstreamer#225]
Hi, I want to check whether GVATrack GPU implementation could benefit my project, so I evalution the performance in devcloud-oneAPI: `qsub -l nodes=s012-n002:gpu:ppn=2:iris_xe_max -d . tracker.sh`
The performance shows GPU-gavtrack **element** has worse performance than CPU-gvatrack:

GPU: 62000 ms
CPU: 20000 ms

Note: I use https://github.com/trawn3333/gstreamer_timestamp_marking to meaure the single element perf.

Could you please provide some performance boost in your side if convenient? Thanks very much.

**Comment by mliu2020** [comment]
Thanks,

I can access DevCloud and could you share tracker.sh or post its content?

Mark Liu

**Comment by wdkwyf** [comment]
tracker.sh
```
source ~/l_openvino_toolkit_internal_ubuntu18_p_2021.4.582/bin/setupvars.sh
cd ~/l_openvino_toolkit_internal_ubuntu18_p_2021.4.582/data_processing/dl_streamer/samples/gst_launch/vehicle_pedestrian_tracking
./vehicle_pedestrian_tracking.sh ~/hospital_20_40.mp4 1 GPU fps zero-term
```

I download openvino 2021.4.582 to my devcloud local path.
Need to modify the gvatrack device=GPU and device=CPU to check whether the whole performance change.

**Comment by mliu2020** [comment]
Thanks,

Let me check it. I also noticed you are using Xe Max which is the discrete GPU, this could cause some difference.

Also I saw the value of CPU/GPU, I check the markout code but not sure the numbers. Is it the total processing time? DL Streamer has a gvafpscount element can also measure FPS number.

Mark Liu

**Comment by wdkwyf** [comment]
> Thanks,
> 
> Let me check it. I also noticed you are using Xe Max which is the discrete GPU, this could cause some difference.
> 
> Also I saw the value of CPU/GPU, I check the markout code but not sure the numbers. Is it the total processing time? DL Streamer has a gvafpscount element can also measure FPS number.
> 
> Mark Liu

Hi, I notice Xe Max/DG1 is supported for GVAtrack, so I choose this node.

The markout/markin will measure the **specified** gvatrack element processing time. I'm also using gvafpscount, but it's the total processing time.

**Comment by mliu2020** [comment]
Hi @wdkwyf,

Sorry for the late response since I had a vacation.

I tried your reproducer and I bump an issue: the graphic environment can be installed by OpenVINO package, the pre-requisition check report both video driver and OpenCL driver was missing. Without this, the GPU path runs into error. How did you resolve the graphic driver issues?

As my understanding, if the environment on DevCloud Edge has the better environment, it should have the latest OpenVINO installed, this is a better path to try. Can you also check if the performance is different?

Mark Liu

**Comment by alexey-belyakov** [comment]
Hi @wdkwyf,

I reproduced performance issue and found solution. We will fix it in the near feature.

**Comment by wdkwyf** [comment]
@mliu2020 Thank you Mak. I didn't run the OpenVINO install_neo...., so I didn't change the OpenCL runtime environment.
The clinfo in devcloud is:
![image](https://user-images.githubusercontent.com/7670749/132822689-a40116cf-a8ff-42d6-9b4b-0cefb2a18cfa.png)

So, I don't know the driver version, maybe it's hidden by admin.

**Comment by wdkwyf** [comment]
> Hi @wdkwyf,
> 
> I reproduced performance issue and found solution. We will fix it in the near feature.

@alexey-belyakov Thank you! Looking forward to it!

**Comment by mliu2020** [comment]
@alexey-belyakov,

Thanks for the effort, if the performance issue, it should be reproducible not limited to DevCloud. That should be my next step, but I appreciated you did it.

Let me label this as an identified bug.

Mark

**Comment by akwrobel** [comment]
Closed due to age.  Please try using the latest Intel® Deep Learning Streamer  release
