### ISSUE TITLE
Installation Error dlstreamer - Vaapi

### ISSUE THREAD

**Issue by ntackie** [dlstreamer/dlstreamer#230]
error: can't connect to X server!
libva info: VA-API version 1.4.1
libva info: va_getDriverName() returns -1
libva info: User requested driver 'iHD'
libva info: Trying to open /opt/intel/mediasdk/lib64/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_4
DRM_IOCTL_I915_GEM_APERTURE failed: Invalid argument
Assuming 131072kB available aperture size.
May lead to reduced performance or incorrect rendering.
get chip id failed: -1 [22]
param: 4, val: 0
libva error: /opt/intel/mediasdk/lib64/iHD_drv_video.so init failed
libva info: va_openDriver() returns 18
vaInitialize failed with error code 18 (invalid parameter),exit

**Comment by brmarkus** [comment]
Can you provide your environment, please? On which hardware, using which operating system?
The errors you see can mean you don't have an Intel GPU (and/or no i915 Intel GPU kernel module loaded, and/or a very new or very old Intel GPU).
Can you provide the output of
`$> lspci | grep VGA`
This should show whether you have an Intel GPU and which type.

**Comment by ntackie** [comment]
I am using two different machine on one machine I have this as my graphics - lspci | grep VGA
03:00.0 **VGA compatible controller: **ASPEED** Technology, Inc. ASPEED Graphics Family (rev 41)**

and on the other machine I also have this - **00:02.0 VGA compatible controller: VMware SVGA II Adapter** 

Is this that reason for the error and why vaapi isnt installed properly on both machines.

**Comment by mliu2020** [comment]
Hi @ntackie,

From your output, are you using the third party graphic(ASPEED) but not Intel graphic?

@brmarkus is right, i915 will only be enabled when your platform has Intel integrated graphic. If you are sure you have the Intel platform, could you give us the hardware spec?

Mark Liu

**Comment by ntackie** [comment]
Hi @mliu2020 @brmarkus  
 The system doesnt have an intel gpu is there a work around with it

**Comment by mliu2020** [comment]
Hi @ntackie,

You can use CPU only options in the GST pipeline command.

Mark Liu

**Comment by brmarkus** [comment]
Hmm, I haven't "googled" your type of GPU. Maybe the manufacturer is supporting Linux and supporting libva.

You could treat the "libva" C-header-file and libraries as the "front end" and the "DRI media-driver" as the "backend".
Under Linux, you usually can see multiple different DRI backend implementations - from different GPU-manufacturers, like, on my machine:

```
$ ls /usr/lib/x86_64-linux-gnu/dri/
i915_dri.so  i965_drv_video.so  kms_swrast_dri.so  nouveau_drv_video.so  r200_dri.so  r600_dri.so        radeon_dri.so    radeonsi_drv_video.so  virtio_gpu_dri.so
i965_dri.so  iris_dri.so        nouveau_dri.so     nouveau_vieux_dri.so  r300_dri.so  r600_drv_video.so  radeonsi_dri.so  swrast_dri.so          vmwgfx_dri.so
```

There are DRI backend media-drivers from/for Intel, NVidia, AMD...
If you find such a DRI backend media-driver from "ASPEED Technology, Inc. ASPEED Graphics Family" then you can specify it via ENV variables like this:

```
export LIBVA_DRIVERS_PATH=<path to a folder containing the DRI driver>
export LIBVA_DRIVER_NAME=<name of the driver module>
```
