### ISSUE TITLE
WARNING: erroneous pipeline: no element "gvadetect"

### ISSUE THREAD

**Issue by ntackie** [dlstreamer/dlstreamer#231]
After installing dlstreamer and openvino when i try to launch a pipeline i get the following error below. Can you please provide feedback to find a solution. Thank you very much. 

******************************************************************
* FATAL ERROR:                                                   *
* This OpenCV build doesn't support current CPU/HW configuration *
*                                                                *
* Use OPENCV_DUMP_CONFIG=1 environment variable for details      *
******************************************************************

Required baseline features:
    ID=  2 (SSE) - OK
    ID=  3 (SSE2) - OK
    ID=  4 (SSE3) - OK
    ID=  5 (SSSE3) - OK
    ID=  6 (SSE4.1) - OK
    ID=  8 (POPCNT) - NOT AVAILABLE
    ID=  7 (SSE4.2) - OK
terminate called after throwing an instance of 'cv::Exception'
  what():  OpenCV(4.5.3-openvino) ../opencv/modules/core/src/system.cpp:645: error: (-215:Assertion failed) Missing support for required CPU baseline features. Check OpenCV build configuration and required CPU/HW setup. in function 'initialize'

DRM_IOCTL_I915_GEM_APERTURE failed: Invalid argument
Assuming 131072kB available aperture size.
May lead to reduced performance or incorrect rendering.
get chip id failed: -1 [22]
param: 4, val: 0
DRM_IOCTL_I915_GEM_APERTURE failed: Invalid argument
Assuming 131072kB available aperture size.
May lead to reduced performance or incorrect rendering.
get chip id failed: -1 [22]
param: 4, val: 0
DRM_IOCTL_I915_GEM_APERTURE failed: Invalid argument
Assuming 131072kB available aperture size.
May lead to reduced performance or incorrect rendering.
get chip id failed: -1 [22]
param: 4, val: 0
WARNING: erroneous pipeline: no element "gvadetect"

**Comment by mliu2020** [comment]
Hi @ntackie,

It seems like you are missing the DL Streamer element like "gvadetect", did you run "source setupvar.sh"?

It would be helpful if you can post the command line.

Mark Liu

**Comment by srinivaskgp** [comment]
come out from the root directory and activate the source.

**Comment by ntackie** [comment]
I did setup the environment withe source.  However running the source ~/intel/dlstreamer_gst/scripts/setup_en.sh provide the following error below. I went into the folder as well to find the bashrc which was there how the source command still didnt work out. Thank you very much. 


ty@ty:~$  source ~/intel/dlstreamer_gst/scripts/setup_env.sh
bash: source ~/intel/dlstreamer_gst/scripts/setup_env.sh: No such file or directory
ty@ty:~$ cd ~/intel/dlstreamer_gst/s
samples/ scripts/ 
ty@ty:~$ cd ~/intel/dlstreamer_gst/scripts/
ty@ty:~/intel/dlstreamer_gst/scripts$ ls
build_install_libva.sh      gst                                  Makefile
build_install_libva_u18.sh  gst-libs                             samples
build.sh                    inference_backend                    setup_env.sh
CMakeCache.txt              install_dependencies.sh              thirdparty
CMakeFiles                  install_dpcpp_dependencies.sh        utils
cmake_install.cmake         install_metapublish_dependencies.sh  version.txt
configs                     intel64
ty@ty:~/intel/dlstreamer_gst/scripts$  source ~/intel/dlstreamer_gst/scripts/setup_env.sh
bash: source ~/intel/dlstreamer_gst/scripts/setup_env.sh: No such file or directory

**Comment by ntackie** [comment]
I did setup the environment withe source.  However running the source ~/intel/dlstreamer_gst/scripts/setup_en.sh provide the following error below. I went into the folder as well to find the bashrc which was there how the source command still didnt work out. Thank you very much. 


ty@ty:~$  source ~/intel/dlstreamer_gst/scripts/setup_env.sh
bash: source ~/intel/dlstreamer_gst/scripts/setup_env.sh: No such file or directory
ty@ty:~$ cd ~/intel/dlstreamer_gst/s
samples/ scripts/ 
ty@ty:~$ cd ~/intel/dlstreamer_gst/scripts/
ty@ty:~/intel/dlstreamer_gst/scripts$ ls
build_install_libva.sh      gst                                  Makefile
build_install_libva_u18.sh  gst-libs                             samples
build.sh                    inference_backend                    setup_env.sh
CMakeCache.txt              install_dependencies.sh              thirdparty
CMakeFiles                  install_dpcpp_dependencies.sh        utils
cmake_install.cmake         install_metapublish_dependencies.sh  version.txt
configs                     intel64
ty@ty:~/intel/dlstreamer_gst/scripts$  source ~/intel/dlstreamer_gst/scripts/setup_env.sh
bash: source ~/intel/dlstreamer_gst/scripts/setup_env.sh: No such file or directory

**Comment by ntackie** [comment]
What could be issue is because of OPENCV not CPU/HW preferences?




******************************************************************
* FATAL ERROR:                                                   *
* This OpenCV build doesn't support current CPU/HW configuration *
*                                                                *
* Use OPENCV_DUMP_CONFIG=1 environment variable for details      *
******************************************************************

Required baseline features:
    ID=  2 (SSE) - OK
    ID=  3 (SSE2) - OK
    ID=  4 (SSE3) - OK
    ID=  5 (SSSE3) - OK
    ID=  6 (SSE4.1) - OK
    ID=  8 (POPCNT) - NOT AVAILABLE
    ID=  7 (SSE4.2) - OK
terminate called after throwing an instance of 'cv::Exception'
  what():  OpenCV(4.5.3-openvino) ../opencv/modules/core/src/system.cpp:645: error: (-215:Assertion failed) Missing support for required CPU baseline features. Check OpenCV build configuration and required CPU/HW setup. in function 'initialize'

**Comment by akwrobel** [comment]
Closing due to age.  Please try the host system documentation (which has been updated since you first saw this issue)
