### ISSUE TITLE
How to do inferencing only on selected labels(objects) using yolo v3?

### ISSUE THREAD

**Issue by antoniomtz** [dlstreamer/dlstreamer#238]
Hello, I was able to run yolo v3 model using DLstreamer and everything works fine.
Next, I would like to know if there is an easy way to tell the pipeline to only do inferencing on a specific object for example, only dogs.

**Comment by adranit** [comment]
Hi @antoniomtz , 
You are right. DL Streamer currently doesn't provide interface for filtering of produced boxes. For now I recommend to modify metadata after gvadetect element to filter boxes using application or python callback (gvapython).
I'll mark this ticket as enhancement request.

**Comment by akwrobel** [comment]
Closed due to age
