### ISSUE TITLE
YOLO v3 performance issues - CPU at 100%

### ISSUE THREAD

**Issue by antoniomtz** [dlstreamer/dlstreamer#243]
Hello,

I have a pipeline using the yolo v3 model. I have noticed that the pipeline takes 100% of my CPU. I have tested it in different CPU (i7,i9 tiger lake) and the performance is the same.
Is this an expected behavior due to the size of the model? 
Any there any tips to optimize the performance?

**Comment by adranit** [comment]
@antoniomtz , are there any updates?
