### ISSUE TITLE
instead of setupvars.sh/setupvars.bat with c++ code?

### ISSUE THREAD

**Issue by xsmart** [dlstreamer/dlstreamer#246]
we want start the pipeline in the c++ code, and is there has anyway do the same fucntion with setupvars.sh/setupvars.bat in c++ code?

**Comment by Kevinpoleary** [comment]
see from our example at https://github.com/openvinotoolkit/dlstreamer_gst/tree/master/samples/cpp/draw_face_attributes

For C++ project, the link to GST library should be linked in with the build process, I think “setvars” here means OpenVINO’s setvars script, it normally sets up the environment for OpenVINO libraries and tools, you should be able to run it even with C++ code. Did you have any issue here?

**Comment by xsmart** [comment]
web want release /opt/intel/openvino_2021 with our software package, and the end user don't need care about the openvino, and we use c++ code to init the env needed by the openvino framework, just like below 
https://www.intel.com/content/www/us/en/support/articles/000033440/software/development-software.html
just like below code,
setenv("INTEL_OPENVINO_DIR", "apptop/modules/openvino")
 setenv("OPENMP_DIR", "apptop/modules/openvino/xxxxxx")

then the openvino will works

**Comment by akwrobel** [comment]
Closed.  We are not currently looking at adding this functionality.
