### ISSUE TITLE
Where can I find the gvatrack performance measures or report?

### ISSUE THREAD

**Issue by IvanZhangDoIt** [dlstreamer/dlstreamer#252]

**Comment by adranit** [comment]
@IvanZhangDoIt , I afraid we don't have any ready reports regarding to gvatrack. What information are you interested in?

**Comment by IvanZhangDoIt** [comment]
in our project, we just want to make sure the tracking performance is good enough, some metrics like MOTA(multiple object tracking accuracy) will help.
if there is no such info, may I know the detail about the tracking algorithm? so then I could infer the result through papers or existing report relative that algorithm.
