### ISSUE TITLE
Gvatrack - multiple Object IDs for a single object

### ISSUE THREAD

**Issue by Sharan-Sundar** [dlstreamer/dlstreamer#255]
Hello, 
I am currently performing license plate detection using a custom trained ssd-mobilenet model.
I am mostly using `OpenVINO - 2020.4.287`  on `Ubuntu 18.04.5`. But I was able to replicate the same problem on `2021.4.1 LTS` as well.

This is my pipeline -
`gst-launch-1.0 filesrc location=/home/user/Downloads/Video.mp4 ! decodebin ! videoconvert n-threads=4 ! capsfilter caps="video/x-raw,format=BGRx" ! gvadetect model-instance-id=inf0 model=/home/user/model/objectdetection-FP32.xml device=CPU batch-size=1 threshold=0.4 inference-interval=1 nireq=1 ! queue !  gvatrack tracking-type=short-term ! queue !        gvawatermark name=gvawatermark ! videoconvert n-threads=4 !  fpsdisplaysink video-sink=xvimagesink sync=true`

The problem is that a single object( vehicle ) gets multiple object ids. It doesn't happen to every object but happens to most objects in this particular setup.

These are the video parameters - 

![Video_Parameters](https://user-images.githubusercontent.com/43034406/146327648-bd5c0eb6-4b85-4326-b820-ced9726935de.png)

The potential causes that I can think of are

1. **Video parameters** - Low FPS - maybe objects in 2 consecutive frames appear different enough for tracking algorithm to classify it as a new object.
2. **Detection Model Accuracy** - but this can mostly be ruled out as the same pipeline works properly for another video with different parameters - 1920x1080 with 25 FPS.
3. **Vehicles going too fast** -  Gvatrack "threshold" too high- Different tracking algorithm or means of modifying tracking algorithm parameters to reduce "threshold".

I am not sure if the problem is related to #132 as I did check with the latest OpenVINO version as well.
Am I going in the right direction ? Am I missing something out ? Looking forward to your help.

Thanks, 
Sharan

**Comment by adranit** [comment]
@Sharan-Sundar , I'd recommend to try gvatrack with the following option in the pipeline:
... gvatrack **config=tracking_per_class=false** tracking-type=short-term ...

https://github.com/openvinotoolkit/dlstreamer_gst/wiki/Object-tracking#tracking-per-class
Tracking per class
Configurable via tracking_per_class parameter. It specifies whether the class label is considered for updating the object_id of an object or not. When set to true, a new tracking ID will be assigned to an objet when the class label changes. When set to false, the tracking ID will be retained based on the position of the bounding box, even if the class label of the object changes due to model inaccuracy. The default value is true

**Comment by Sharan-Sundar** [comment]
@adranit , a single object has ID constantly changed. In Frame 1, it has object ID 1 and in Frame 2 the object ID becomes 2. This doesn't happen for all the objects in the video but for most objects.
I will try tracking_per_class parameter as well but I have just one class - license plate.

**Comment by PavanKumar13** [comment]
> @adranit , a single object has ID constantly changed. In Frame 1, it has object ID 1 and in Frame 2 the object ID becomes 2. This doesn't happen for all the objects in the video but for most objects. I will try `tracking_per_class parameter` as well but I have just one class - license plate.
> 
> **UPDATE:** I tried `tracking_per_class parameter` and it didn't solve the problem.

Hi, 
i am facing the similar issue, the object-id is keep on changing constanly.

@Sharan-Sundar did you got any fix for it ? please let me know
Thanks in advance

**Comment by Sharan-Sundar** [comment]
Hi @PavanKumar13 ,
No I did not find any fix for it. However, the issue disappeared when I increased the bitrate of the video. I am not sure how these are related and why Object-Detection has to get affected by Bitrate.

**Comment by brmarkus** [comment]
Increasing the bitrate sounds like the video-quality was increased/improved - and object-detection improved because of a higher quality of the input-blob.

**Comment by Sharan-Sundar** [comment]
@brmarkus , so then can we conclude that this is due the accuracy of the object-detection model ? gvatrack depends on that ?

**Comment by brmarkus** [comment]
No proof, no deeper analysis, no conclusion.
It could be the higher quality, yes; it could depend on the NN-model's used convolution kernel-size or filters.
It could be re-encoding/transcoding has slightly changed the framerate - leaving or improving artifacts. Re-encoding/transcoding might have changed the GOP-structure (I-frames only? Distance between the I-frames, number of P-frames, etc.).

**Comment by akwrobel** [comment]
There has been no progress on this issue with existing analysis.  Closing this issue.  If this is still seen with the most recent revision of DL Streamer please file a new issue and include your configuration information.
