### ISSUE TITLE
Object class incorrectly changed with gvatrack

### ISSUE THREAD

**Issue by JoeAYeung** [dlstreamer/dlstreamer#259]
Hi, 

I noticed a change in object class with gvatrack.
I had inference-interval=2 and tracking_per_class=false 

With gvatrack, a person and a couple of chairs assigned object id 13, 4 and 9 respectively.
<img width="908" alt="Screen Shot 2022-01-01 at 7 35 19 PM" src="https://user-images.githubusercontent.com/96928924/147889170-854c040d-2b2c-4290-b1d9-b3f9d0708d57.png">

In the next frame, the person and the chairs became bowls with the same object id.
<img width="909" alt="Screen Shot 2022-01-01 at 7 35 49 PM" src="https://user-images.githubusercontent.com/96928924/147889188-614c44e8-1e3d-4c2b-adac-d0fb33776b9b.png">

Without gvatrack, the respective frames are as followed. 

<img width="908" alt="Screen Shot 2022-01-01 at 7 32 10 PM" src="https://user-images.githubusercontent.com/96928924/147889222-f72d1aef-10ba-49f8-a208-d8f99d639f31.png">

<img width="906" alt="Screen Shot 2022-01-01 at 7 32 37 PM" src="https://user-images.githubusercontent.com/96928924/147889231-cfb491e6-7676-49b0-90d1-ca6967bf8696.png">

**Comment by adranit** [comment]
Hi @JoeAYeung ,
I guess you don't set label_id for ROIs in yolov5_post_processing.py. 
gvawatermark uses object_id as a color index if it is set. Otherwise label_id is used as an index. According to the last two pictures, gvawatermark uses color_index=0.

Also gvatrack uses label_id to restore labels for ROIs. If label_id is not set then gvatrack can't correctly restore labels for the tracked ROIs.

**Comment by lamalexck** [comment]
Thanks @adranit !

Setting the label_id did the trick!

In summary, assuming the model returns class number n for the detection, one need to:

label = class_number_to_class_name_map[ n ]

# Create the ROI
roi = frame.add_region( .... , label, .. ) 

# Set the label_id
roi.detection()['label_id'] = n

**Comment by JoeAYeung** [comment]
Thanks @adranit !

Setting the label_id did the trick!

In summary, assuming the model returns class number ```n``` for the detection, one need to:
```
label = class_number_to_class_name_map[ n ]

#Create the ROI
roi = frame.add_region( .... , label, .. ) 

# Set the label_id
roi.detection()['label_id'] = n
```

**Comment by PavanKumar13** [comment]
> Thanks @adranit !
> 
> Setting the label_id did the trick!
> 
> In summary, assuming the model returns class number `n` for the detection, one need to:
> 
> ```
> label = class_number_to_class_name_map[ n ]
> 
> #Create the ROI
> roi = frame.add_region( .... , label, .. ) 
> 
> # Set the label_id
> roi.detection()['label_id'] = n
> ```

Hi @JoeAYeung ,

can you please share me the gvapython yolov5_postprocessing.py file as i am stuck and not able to get the bounding boxes out of gvainference.

Thanks in Advance.

**Comment by JoeAYeung** [comment]
> > Thanks @adranit !
> > Setting the label_id did the trick!
> > In summary, assuming the model returns class number `n` for the detection, one need to:
> > ```
> > label = class_number_to_class_name_map[ n ]
> > 
> > #Create the ROI
> > roi = frame.add_region( .... , label, .. ) 
> > 
> > # Set the label_id
> > roi.detection()['label_id'] = n
> > ```
> 
> Hi @JoeAYeung ,
> 
> can you please share me the gvapython yolov5_postprocessing.py file as i am stuck and not able to get the bounding boxes out of gvainference.
> 
> Thanks in Advance.

@PavanKumar13 
Sorry, due to license constraints I cannot just share the code with you.
However, I can provide pointers: 
* My yolov5_postprocessing.py was based on [https://github.com/violet17/yolov5_demo/blob/main/yolov5_demo_OV2021.3.py](https://github.com/violet17/yolov5_demo/blob/main/yolov5_demo_OV2021.3.py) Specifically, on line 368 the coordinates of the ROI were derived.
* And here is an example of how ROI are inserted into the stream's metadata [https://github.com/dlstreamer/dlstreamer/blob/master/samples/gst_launch/gvapython/face_detection_and_classification/postproc_callbacks/ssd_object_detection.py](https://github.com/dlstreamer/dlstreamer/blob/master/samples/gst_launch/gvapython/face_detection_and_classification/postproc_callbacks/ssd_object_detection.py)

Hope these help!

**Comment by mansi-111** [comment]
Hi @JoeAYeung ,
 
We have tried to create yolov5_postprocessing script with dlstreamer pipeline, but we are getting bounding boxes are off from the actual objects as you can see in the below image and attaching the script would you please correct us, as we got stuck in this and we are attaching the model files also and these are working fine with normal openvino inferencing. 
[filter_item1..py.txt](https://github.com/dlstreamer/dlstreamer/files/8096394/filter_item1.py.txt)
![Screenshot from 2022-02-18 16-09-58](https://user-images.githubusercontent.com/60024757/154667302-e5a3e98f-1c12-46c3-81a1-55e5c9c1490b.png)
Please check the code at line no 184 to 191 where we are parsing gvainference results to yolo parsing.

**Comment by JoeAYeung** [comment]
@mansi-111 

It looks like a scale problem to me.
Try change your scale_bbox to scale without keeping aspect ratio.
