### ISSUE TITLE
Custom SOURCE_ELEMENT ${INPUT}

### ISSUE THREAD

**Issue by psakamoori** [dlstreamer/dlstreamer#262]
Question: How to set/pass custom video input as SOURCE_ELEMENT="v4l2src device=${INPUT}". I wan to send video frame object for example: frame object read from realsense pyrealsense2 python api

Code snippet: 
import pyrealsense2 as rs
align = rs.align(rs.stream.color)
pipe = rs.pipeline()
frames = pipe.wait_for_frames()
aligned_frames = self.align.process(frames)
rgb_frame = self.aligned_frames.get_color_frame()

Want to pass "rgb_frame" as my ${INPUT}" ...

Is this possible? If so, please help with a reference code sample.

**Comment by adranit** [comment]
Hi @psakamoori ,
As far as I understand you tried to set device in the standard way (for ex. 'v4l2src device=/dev/video0', there are should be several devices for realsense in the /dev/ directory) but it did not work for you. 
I think v4l2scr does not support anything except path to the system devices. If you want to produce videoframes in some special way you can use [appsrc](https://gstreamer.freedesktop.org/documentation/app/appsrc.html?gi-language=c)  element in pipeline.

Thanks,
Anton

**Comment by adranit** [comment]
@psakamoori , if the issue is not resolved yet feel free to reopen it.
