### ISSUE TITLE
face detection and emotion classification example failed to run with json file

### ISSUE THREAD

**Issue by niyazFattahov** [dlstreamer/dlstreamer#263]
I can run this command and it's working without json file:
`gst-launch-1.0 rtspsrc location=rtsp://192.168.1.118:9999/test latency=100 ! queue ! rtph264depay ! h264parse ! avdec_h264 ! videoconvert ! gvadetect model=face-detection-adas-0001.xml ! gvaclassify model=emotions-recognition-retail-0003.xml ! gvawatermark ! videoscale ! videoflip method=rotate-180 ! video/x-raw,width=1920,height=1080 ! autovideosink
`
But this command with json file:
`gst-launch-1.0 rtspsrc location=rtsp://192.168.1.118:9999/test latency=100 ! queue ! rtph264depay ! h264parse ! avdec_h264 ! videoconvert ! gvadetect model=face-detection-adas-0001.xml ! gvaclassify model=emotions-recognition-retail-0003.xml model-proc=emotions-recognition-retail-0003.json ! gvawatermark ! videoscale ! videoflip method=rotate-180 ! video/x-raw,width=1920,height=1080 ! autovideosink
`
I get:
Setting pipeline to PAUSED ...
Pipeline is live and does not need PREROLL ...
Progress: (open) Opening Stream
Pipeline is PREROLLED ...
Prerolled, waiting for progress to finish...
Progress: (connect) Connecting to rtsp://192.168.1.118:9999/test
Progress: (open) Retrieving server options
Progress: (open) Retrieving media info
Progress: (request) SETUP stream 0
Progress: (open) Opened Stream
Setting pipeline to PLAYING ...
New clock: GstSystemClock
Progress: (request) Sending PLAY request
Progress: (request) Sending PLAY request
Progress: (request) Sent PLAY request
Redistribute latency...
ERROR: from element /GstPipeline:pipeline0/GstGvaClassify:gvaclassify0: base_inference plugin intitialization failed
Additional debug info:
/root/gst-video-analytics/gst/inference_elements/base/inference_singleton.cpp(136): acquire_inference_instance (): /GstPipeline:pipeline0/GstGvaClassify:gvaclassify0:

Failed to construct OpenVINOImageInference
	Unsupported input_layer precision: 
ERROR: from element /GstPipeline:pipeline0/GstGvaClassify:gvaclassify0: base_inference based element initialization has been failed.
Additional debug info:
/root/gst-video-analytics/gst/inference_elements/base/gva_base_inference.c(603): gva_base_inference_set_caps (): /GstPipeline:pipeline0/GstGvaClassify:gvaclassify0:
inference is NULL.
Execution ended after 0:00:00.317636278
Setting pipeline to NULL ...
ERROR: from element /GstPipeline:pipeline0/GstGvaClassify:gvaclassify0: base_inference failed on stop
Additional debug info:
/root/gst-video-analytics/gst/inference_elements/base/inference_singleton.cpp(196): flush_inference (): /GstPipeline:pipeline0/GstGvaClassify:gvaclassify0:
empty inference instance
Freeing pipeline ...

I use this Json file (it is right file)?: https://github.com/OpenVisualCloud/Ad-Insertion-Sample/blob/master/ad-insertion/analytics/models/emotion_recognition/1/emotions-recognition-retail-0003.json

**Comment by adranit** [comment]
Hi @niyazFattahov ,
I'd recommend to use another model_proc file - https://github.com/dlstreamer/dlstreamer/blob/master/samples/model_proc/intel/object_attribute_estimation/emotions-recognition-retail-0003.json.

Probably the used file is outdated and not compatible with used DL Streamer version.

**Comment by niyazFattahov** [comment]
thank you, I forgot to watch dlstreamer directory to use this file
