### ISSUE TITLE
compiler error on arm64

### ISSUE THREAD

**Issue by dukezuoHZ** [dlstreamer/dlstreamer#264]
I have met a issue when i build dlstreamer on arm64 platform whil i built it ok on x86 platform. the issue is below:
make[2]: *** Waiting for unfinished jobs....
[ 80%] Built target gstvideoanalytics
[ 84%] Built target gstgvavideototensor
[ 88%] Built target gstgvatensortometa
In file included from /home/duke/dlstreamer_gst/gst/elements/gvatrack/tracker_factory.cpp:11:0:
/home/duke/dlstreamer_gst/gst/elements/gvatrack/vas/tracker.h:11:10: fatal error: vas/ot.h: No such file or directory
 #include "vas/ot.h"
          ^~~~~~~~~~
compilation terminated.

It seemd can't find vas library,I  check the CMakelist and edit it:

if (${CMAKE_SYSTEM_PROCESSOR} STREQUAL "aarch64")
    option(ENABLE_ITT "Enable ITT for tracing" ON)        ## OFF->ON
    option(DOWNLOAD_VAS_TRACKER "Download VAS tracker" ON)   ## OFF->ON 
else()
    option(ENABLE_ITT "Enable ITT for tracing" ON)
    option(DOWNLOAD_VAS_TRACKER "Download VAS tracker" ON)
endif()

but it report the same error when built it. how can i do to build it success?

**Comment by adranit** [comment]
Hi @dukezuoHZ ,
Unfortunately, the tracker for arm64 platform is not included in the distribution, so to build the DL Streamer, you need to disable the ENABLE_VAS_TRACKER option.
https://github.com/dlstreamer/dlstreamer/blob/88fc68cbb052e011d51fdd0195e74a38567651a8/CMakeLists.txt#L123

**Comment by dukezuoHZ** [comment]
> Hi @dukezuoHZ , Unfortunately, the tracker for arm64 platform is not included in the distribution, so to build the DL Streamer, you need to disable the ENABLE_VAS_TRACKER option.
> 
> https://github.com/dlstreamer/dlstreamer/blob/88fc68cbb052e011d51fdd0195e74a38567651a8/CMakeLists.txt#L123

think adranit,yes,when i disabled it,it built ok now! but i know this function is ok on intel KMB platform,so how it do right?

**Comment by adranit** [comment]
Hi @dukezuoHZ ,
this library is available for KBM program only, it is not available to external download.
