### ISSUE TITLE
"inference-region roi-list" property works only in OpenVINO_2020.4 converted Tensorflow IR files

### ISSUE THREAD

**Issue by Sharan-Sundar** [dlstreamer/dlstreamer#266]
Hi, 
I am currently performing vehicle detection using a custom-trained ssd model. 
This is using `OpenVINO 2021.4.2 LTS` on Ubuntu `18.04.6 LTS`  with the latest DLstreamer release - #254 .
The output of  `cat /proc/cpuinfo | grep "model name"`  is     `model name	: Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz`.
Gstreamer version is `GStreamer Core Library version 1.18.4 `.

My usecase is #57 - to be more specific it's #206 . My pipeline is `gvadetect1 -> gvatrack -> gvadetect2` .

`Gvadetect2` works properly when I use a `Gvadetect1` model which is multi-class. But the same `Gvadetect2` model gives no detections when I use a single-class `Gvadetect1` model. Both the models work fine individually and this happens only when I use them together in the `gvadetect1 -> gvatrack -> gvadetect2` cascading pipeline.

This leads me to believe that it might be a small mistake somewhere in the source code of the gvadetect element - "inference-region" property. Looking forward to your help.
Thank you.

**Comment by adranit** [comment]
Hi @Sharan-Sundar ,
Do you use object-class property of gvadetect2 ? Could you provide more details about pipeline used?

**Comment by Sharan-Sundar** [comment]
Yes I have tried object-class and it didn't work. 

So, the use case is basically vehicle detection and on top of that, license plate detection. So `gvadetect1 `detects vehicles and `gvadetect2` detects license plates within the vehicles detected from `gvadetect1`.

This is the pipeline -
`gst-launch-1.0 filesrc location=/home/user/vid.mp4 ! decodebin !   videoconvert n-threads=4 ! capsfilter caps="video/x-raw,format=BGRx" !        gvadetect model-instance-id=veh0 model=vehicle.xml inference-interval=2 threshold=0.4  ! queue !        gvatrack tracking-type=short-term ! queue !   gvadetect model-instance-id=plate0 model=plate.xml threshold=0.5 inference-interval=1 inference-region=roi-list object-class=Vehicle ! queue !  gvawatermark name=gvawatermark ! videoconvert n-threads=4 !        fpsdisplaysink video-sink=xvimagesink sync=false`

So here, when I use `gvadetect1` with a Vehicle Type Model that has multiple classes - "cars", "trucks" and "bikes", this pipeline works properly and I get detections from `gvadetect2` as well. But when I use a Vehicle Type Model with only one class - "Vehicle", this pipeline fails and I get no output from `gvadetect2`. Every other parameter remains the same.
Am I using gvadetect correctly ?

**Comment by Sharan-Sundar** [comment]
Check if this helps. VT3 is the multi-class model that works. VT7 is the single-class model that doesn't work. These are the Tensorflow-to-OpenVINO converted xml files.

![Inference_Region](https://user-images.githubusercontent.com/43034406/158805487-b69e4dff-abd3-4cd1-ae03-42f7eee6b982.png)

**Comment by adranit** [comment]
Hi @Sharan-Sundar ,
Using of object-class property requires labels to be assigned to roi. If object-class is set then all ROIs with another labels (and empty too) are rejected. 
I guess you use multi-class model with model_proc file (contains labels), so filtering works as expected. 

I'd recommend two options:
- use model_proc file with labels list for gvadetect1
- remove object-class filter from gvadetect2. I believe "object-class" is not required because gvadetect1(single class model) produces only one type of ROI.

**Comment by Sharan-Sundar** [comment]
No I am not using model-proc yet as I still have not understood model-proc properly. Anyway I don't need pre/post processing so I assumed it wasn't needed.

But, on seeing your comment, I tried but that led to no detections from gvadetect at all. The detection model is ssd-mobilenet and it's detecting only one object class - "Vehicle". This is the model-proc I used - 
```
{
    "json_schema_version": "2.1.0",
    "input_preproc": [],
    "output_postproc": [
        {
            "converter": "tensor_to_bbox_ssd",
            "labels": [
                "Vehicle"
            ]
        }
    ]
}
```
Am I using it correctly? Kindly help me out here.

**Comment by adranit** [comment]
@Sharan-Sundar , I think that the following should work fine.
```
{
    "json_schema_version": "2.1.0",
    "output_postproc": [
        {
            "labels": [
                "Vehicle"
            ]
        }
    ]
}
```

**Comment by Sharan-Sundar** [comment]
Nope. When I use the above file, I get these errors - 
```
0:00:02.352852742 29905 0x7f41240a8840 ERROR             GVA_common post_processor.cpp:212:process: Failed to do SSD post-processing
0:00:02.352904266 29905 0x7f41240a8840 ERROR                default inference_impl.cpp:799:InferenceCompletionCallback: 
Post-processing has been exited with FAIL code.
```

**Comment by Sharan-Sundar** [comment]
Problem still exists in OpenVINO-2022.1 and dlstreamer Release 2022.1. 
To summarize the problem, I am able to use `gvadetect` elements with `inference-region` property set to `roi-list` properly only for models that were converted using OpenVINO2020. If I convert with OpenVINO2021 or OpenVINO2022 and use those IR files, I get an error.

**Comment by mikhail-nikolskiy** [comment]
The `Cannot create reorder primitive: unsupported reorder case` is exception from OpenVINO runtime.
If convert model from TensorFlow to IR using OpenVINO 2022.1, does converted model work in OpenVINO 2022.1 samples, ex [C++ benchmark_app](https://github.com/openvinotoolkit/openvino/tree/master/samples/cpp/benchmark_app)?
If not, it's OpenVINO problem, you can submit bug to https://github.com/openvinotoolkit/openvino/issues

**Comment by akwrobel** [comment]
This is a conversion issue owned by OpenVINO information on filing issues was given above.  Closing issue.
