### ISSUE TITLE
Different padding needed for different classification models

### ISSUE THREAD

**Issue by PavanKumar13** [dlstreamer/dlstreamer#267]
Hi All,

I am trying to do padding for detected faces, and i am having multiple classification models like(age, gender and mask), so every classifier input requires faces with some  % of [left,right,top, bottom] padding, i have tried gvaclassify with model-proc and it has a padding property which can take fixed values  [stride_x, stride_y] but i wanted to do dynamic padding and i am able to do using gvapython  for detected faces, 

ht_ = y_max - y_min
wt_ = x_max - x_min
padding_xmin = int(wt_*0.25)
padding_ymin = int(ht_*0.25)
padding_xmax =int(wt_*0.25)
padding_ymax = int(ht_*0.25)

and the same padded face goes for every classifier model in the pipeline, but i want different padding for every classifier model,

Pipeline: gvainference(detect faces) -> gvapython(post-proc) -> gvaclassify ->gvaclassify -> gvaclassify.

How could i achieve different padding for every classifier model?

Thanks in Advance.

**Comment by nnshah1** [comment]
Couple thoughts:

1) you could add a `tee` element and multiple gvapython -> gvaclassify elements (you would also need to use metaggregate to put values back on the same frame.

2) you could add additional bounding boxes each with a distinct 'label' and have each gvaclassify element pick up a different distinct `label` using the `object-class` property

**Comment by PavanKumar13** [comment]
> Couple thoughts:
> 
> 1. you could add a `tee` element and multiple gvapython -> gvaclassify elements (you would also need to use metaggregate to put values back on the same frame.
> 2. you could add additional bounding boxes each with a distinct `label` and have each gvaclassify element pick up a different distinct `label` using the `object-class` property


Hi @nnshah1,

Thanks for the quick reply,  i will give it a try.

**Comment by akwrobel** [comment]
Closing due to age and no follow up from submitter.
