### ISSUE TITLE
"Gvatrack before Gvadetect" pipeline crashes with GStreamer-CRITICAL 

### ISSUE THREAD

**Issue by Sharan-Sundar** [dlstreamer/dlstreamer#270]
Hi, 
I am currently performing vehicle detection using a custom-trained ssd model. 
This is using `OpenVINO 2021.4.2 LTS` on Ubuntu `18.04.6 LTS`  with the latest DLstreamer release - #254 .
The output of  `cat /proc/cpuinfo | grep "model name"`  is     `model name	: Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz`.
Gstreamer version is `GStreamer Core Library version 1.18.4 `.

My usecase is #57 - to be more specific it's #206 . My architecture is `gvadetect1 -> gvatrack -> gvadetect2` .
This is my pipeline - 
`gst-launch-1.0 filesrc location=/home/user/vid.mp4 ! decodebin ! videoconvert n-threads=4 ! capsfilter caps="video/x-raw,format=BGRx" ! gvadetect model-instance-id=vehicle0 model=vehicle.xml inference-interval=2 threshold=0.4   ! queue ! gvatrack tracking-type=short-term ! queue ! gvadetect model-instance-id=plate0 model=plate.xml threshold=0.5 inference-interval=1 inference-region=roi-list ! queue ! gvawatermark name=gvawatermark ! videoconvert n-threads=4 ! fpsdisplaysink video-sink=xvimagesink sync=false`

The problem is that it randomly crashes with these logs -

```
(gst-launch-1.0:2570): GStreamer-CRITICAL **: 08:41:46.627: gst_buffer_get_size: assertion 'GST_IS_BUFFER (buffer)' failed

(gst-launch-1.0:2570): GStreamer-CRITICAL **: 08:41:46.628: gst_mini_object_unref: assertion 'GST_MINI_OBJECT_REFCOUNT_VALUE (mini_object) > 0' failed

(gst-launch-1.0:2570): GStreamer-CRITICAL **: 08:41:46.631: gst_buffer_unmap: assertion 'GST_IS_BUFFER (buffer)' failed

(gst-launch-1.0:2570): GStreamer-CRITICAL **: 08:41:46.631: gst_buffer_get_size: assertion 'GST_IS_BUFFER (buffer)' failed

(gst-launch-1.0:2570): GStreamer-CRITICAL **: 08:41:46.631: gst_mini_object_unref: assertion 'GST_MINI_OBJECT_REFCOUNT_VALUE (mini_object) > 0' failed
Got EOS from element "pipeline0".
```

This seems to happen when there are multiple objects getting detected in the frame.
However,  everything runs smoothy if I use just  `gvadetect1 -> gvatrack`  or  `gvadetect2 -> gvatrack`.  Only when I use back-to-back gvadetect elements, this occurs. This leads me to believe that it might be a problem with the "inference-region" property in the gvadetect element. Looking forward to your help.
Thank you.

**Comment by Sharan-Sundar** [comment]
Hi @adranit , yes it was my fault. I have edited the question with the actual pipeline now including "inference-region". But like you said, this problem might be with gvatrack before an inference element. I have updated the question also with the same.

So I tried this and it didn't work.
```
void UpdateClassificationHistory(GstVideoRegionOfInterestMeta *meta, GvaBaseInference *gva_base_inference,
                                 const GstStructure *classification_result) {

    if (G_OBJECT_TYPE(G_OBJECT(gva_base_inference)) != GST_GVA_CLASSIFY_TYPE)
        return;

    if (gva_base_inference->type != GST_GVA_CLASSIFY_TYPE)
        return;

    GstGvaClassify *gvaclassify = (GstGvaClassify *)gva_base_inference;
    gint meta_id = 0;
    get_object_id(meta, &meta_id);
    if (gvaclassify->reclassify_interval != 1 and meta_id > 0)
        gvaclassify->classification_history->UpdateROIParams(meta_id, classification_result);
}
```
Do you have any other suggestions ? And approximately when can we expect the next Release ?

**Comment by Sharan-Sundar** [comment]
Does the release 2022.1 solve this bug ?

**Comment by mikhail-nikolskiy** [comment]
We deprecated and removed short-term tracker in release 2022.1: https://github.com/dlstreamer/dlstreamer/releases
so please replace 'tracking-type=short-term' with 'tracking-type=short-term-imageless', or 'tracking-type=zero-term' plus remove 'inference-interval'.
Let us know if issue still reproducible on latest release and after these changes, I hope it will not.

**Comment by Sharan-Sundar** [comment]
That's great !! I will try and get back to you.

**Comment by Sharan-Sundar** [comment]
@mikhail-nikolskiy, the issue is not reproducible from 2022.1 onwards. Closing it now.
