### ISSUE TITLE
inference-region in gvadetect

### ISSUE THREAD

**Issue by howarwang** [dlstreamer/dlstreamer#271]
I have an ANPR pipeline('filesrc', 'decodebin', 'videoconvert', 'capsfilter','inferenceregion','gvadetect','gvatrack',
                           'gvaclassify', 'gvawatermark', 'fpsdisplaysink'). 
The element of inferenceregion is to specify a small region (inference-region) for gvadetect to recognize number plate.
Also compared the average fps of two scenarios: with inference-region(parital frame detect) and with no inference-region(full frame detect), found the fps have not too much difference. But from: [https://github.com/dlstreamer/dlstreamer/wiki/gvadetect](url) looks like the gvadetect can detect a specified roi-list, which should be more efficient than do full frame detection.
My question is if the inference-region of gvadetct is for smaller region inference or filtering? I mean if only for filtering, then the infernece fps wont be improved too much.

**Comment by akwrobel** [comment]
**inference-region** is not for filtering, it is for running inference on ROIs directly when set to **roi-list**.  Please let us know if you have any additional questions.

**Comment by akwrobel** [comment]
@howarwang do you have any further questions on this?

**Comment by akwrobel** [comment]
No response from submitter, closing issue
