### ISSUE TITLE
Release date for latest DL Streamer with the latest OpenVINO release be published to Dockerhub?

### ISSUE THREAD

**Issue by scalers-ai** [dlstreamer/dlstreamer#272]
Older versions of openvino/ubuntu20_dev have DLStreamer included but the latest (2022.1) doesn't seem to. Is there a naming convention which has a meaning or is it (almost) random?

DL Streamer seems to be one of the useful API for OpenVINO, especially for enterprise (i.e. non-embedded) developers.

Thanks!

**Comment by brmarkus** [comment]
When looking into "https://hub.docker.com/r/openvino/ubuntu20_dev" there is a reference to the OpenVINO release notes:

> Release Notes: https://software.intel.com/en-us/articles/OpenVINO-RelNotes

And the release-notes contain this:

> [DL Streamer](https://github.com/dlstreamer/dlstreamer)
> DL Streamer is not included in OpenVINO toolkit by default anymore. It should be installed/downloaded separately, please follow [Installation Guide](https://github.com/dlstreamer/dlstreamer/wiki/Install-Guide).

**Comment by scalers-ai** [comment]
Thanks.

**Comment by scalers-ai** [comment]
Edited the title of the issue. When will DL Streamer release support for OpenVINO 2022.1? When will docs/other content be updated to reflect this support?

**Comment by brmarkus** [comment]
Stay tuned for only a few more days.

**Comment by kuanhenglee** [comment]
Any update on the DLstreamer with the support for OpenVINO 2022.1?

**Comment by skibey** [comment]
DL Streamer 2022.1 release with OpenVINO 2022.1 is trending early next week, we are doing final checks. Thank you for your patience.

**Comment by scalers-ai** [comment]
Thanks for publishing! Closing this issue.

**Comment by akwrobel** [comment]
Intel® DL Streamer 2022.1 Pipeline Framework has been published and the DockerHub images can be found here: https://hub.docker.com/r/intel/dlstreamer
Pipeline Framework now has it's own DockerHub images.  You should use the devel tag for the latest.  https://hub.docker.com/r/intel/dlstreamer/tags?page=1&name=devel

Documentation will be updated to reflect this shortly.
