### ISSUE TITLE
How can i write a custom ImageInference to replace OpenVINOImageInference?

### ISSUE THREAD

**Issue by dukezuoHZ** [dlstreamer/dlstreamer#273]
Dlstreamer is vary easily used for AI application  especially  with mediapipe. But i found it was bound so deeply with OpenVINO on intel platform.  For another arm64 platform just like NXP(imx8mp), It used nnstreamer (based on gstreamer) for ai inference. I want to  write a customed ImageInference  just like  class NNstreamerImageInference : public InferenceBackend::ImageInference. But i found it used  a gstreamer element named tensor filter to submit image and read ai result  data. so if I linked the element with dlstreamer's element srcpad,  just as  gvaclassify.   how can i transfer data to model-proc?
because NXP have self's hardware CSC(color space convert) module. how can i used it for InputPreprocessors of model-proc?

**Comment by mikhail-nikolskiy** [comment]
Are you looking into ImageInference C++ interface implementation via NNStreamer element tensor_filter?

Alternative (probably better?) way would be gvadetect/gvaclassify implemented as GStreamer bin element, internally building  sub-pipeline of pre-processing, inference, post-processing GStreamer elements according to parameters specified in model-proc?

**Comment by dukezuoHZ** [comment]
yes,I check the source OpenvinoImageInference ,it use openvino setblob/getblob to send and get ai result,but if we used NNStreamer element tensor_filter, the ai blob data flow from srcpad of gvadetect/gvaclassify Initiative。
