### ISSUE TITLE
Batching frames from multiple cameras

### ISSUE THREAD

**Issue by pkaczmarczyk-nct** [dlstreamer/dlstreamer#274]
Hi!

I want to analyze the multiple RTSP camera sources in a single processing pipeline.

For reference, I am looking for something like is available in [Nvidia's Deepstream SDK ](https://docs.nvidia.com/metropolis/deepstream/dev-guide/text/DS_plugin_gst-nvstreammux.html).
For my use case, batch inference (or more important having the last frames from multiple cameras in one place) is essential.

Does the DL Streamer support such pipelines?

**Comment by nnshah1** [comment]
DL Streamer supports batching accross pipelines using the model-instance-id parameter. 

If batching for inference is the main use case that should work (with some caveats on the individual streams having the same pre-processing requirements).

For running multiple pipelines in a single process if you're interested in a microservice approach you can also look at our pipeline server component as well: [pipeline-server(https://github.com/dlstreamer/pipeline-server)

**Comment by stu-github** [comment]
> Hi!
> 
> I want to analyze the multiple RTSP camera sources in a single processing pipeline.
> 
> For reference, I am looking for something like is available in [Nvidia's Deepstream SDK ](https://docs.nvidia.com/metropolis/deepstream/dev-guide/text/DS_plugin_gst-nvstreammux.html). For my use case, batch inference (or more important having the last frames from multiple cameras in one place) is essential.
> 
> Does the DL Streamer support such pipelines?

Which solution do you use now？

**Comment by akwrobel** [comment]
Closed, this was answered and there has been no further response from the submitter.
