### ISSUE TITLE
vainfo error

### ISSUE THREAD

**Issue by HuangYijuan** [dlstreamer/dlstreamer#275]
libva info: VA-API version 1.4.1
libva info: va_getDriverName() returns 0
libva info: User requested driver 'iHD'
libva info: Trying to open /opt/intel/mediasdk/lib64/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_4
DRM_IOCTL_I915_GEM_APERTURE failed: Invalid argument
Assuming 131072kB available aperture size.
May lead to reduced performance or incorrect rendering.
get chip id failed: -1 [22]
param: 4, val: 0
libva error: /opt/intel/mediasdk/lib64/iHD_drv_video.so init failed
libva info: va_openDriver() returns 18
vaInitialize failed with error code 18 (invalid parameter),exit

**Comment by brmarkus** [comment]
Can you provide more details about your environment, please?
Which HW are you on? Can you provide the info from e.g. "$> lscpu" and "$> lspci", to see which CPU and which GPU you are using?
Which OS are you using? Are you running your tests "natively" in the OS, or within a Docker container, within a guest-OS, or using a KVM, any virtualization, any hypervisor?
Have you installed OpenVINO and DL-Streamer from pre-packaged deliveries, or built from source, in which versions?

**Comment by HuangYijuan** [comment]
lscpu
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   39 bits physical, 48 bits virtual
CPU(s):                          24
On-line CPU(s) list:             0-23
Thread(s) per core:              1
Core(s) per socket:              16
Socket(s):                       1
NUMA node(s):                    1
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           151
Model name:                      12th Gen Intel(R) Core(TM) i9-12900KF
Stepping:                        2
CPU MHz:                         874.971
CPU max MHz:                     6700.0000
CPU min MHz:                     800.0000
BogoMIPS:                        6374.40
Virtualization:                  VT-x
L1d cache:                       384 KiB
L1i cache:                       256 KiB
L2 cache:                        10 MiB
NUMA node0 CPU(s):               0-23
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disab
                                 led via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and _
                                 _user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Enhanced IBRS, IBPB conditiona
                                 l, RSB filling
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected

lspci
00:00.0 Host bridge: Intel Corporation Device 4660 (rev 02)
00:01.0 PCI bridge: Intel Corporation Device 460d (rev 02)
00:06.0 PCI bridge: Intel Corporation Device 464d (rev 02)
00:14.0 USB controller: Intel Corporation Device 7ae0 (rev 11)
00:14.2 RAM memory: Intel Corporation Device 7aa7 (rev 11)
00:14.3 Network controller: Intel Corporation Device 7af0 (rev 11)
00:15.0 Serial bus controller [0c80]: Intel Corporation Device 7acc (rev 11)
00:15.1 Serial bus controller [0c80]: Intel Corporation Device 7acd (rev 11)
00:15.2 Serial bus controller [0c80]: Intel Corporation Device 7ace (rev 11)
00:15.3 Serial bus controller [0c80]: Intel Corporation Device 7acf (rev 11)
00:16.0 Communication controller: Intel Corporation Device 7ae8 (rev 11)
00:17.0 SATA controller: Intel Corporation Device 7ae2 (rev 11)
00:19.0 Serial bus controller [0c80]: Intel Corporation Device 7afc (rev 11)
00:19.1 Serial bus controller [0c80]: Intel Corporation Device 7afd (rev 11)
00:1c.0 PCI bridge: Intel Corporation Device 7abc (rev 11)
00:1d.0 PCI bridge: Intel Corporation Device 7ab4 (rev 11)
00:1e.0 Communication controller: Intel Corporation Device 7aa8 (rev 11)
00:1e.3 Serial bus controller [0c80]: Intel Corporation Device 7aab (rev 11)
00:1f.0 ISA bridge: Intel Corporation Device 7a84 (rev 11)
00:1f.3 Audio device: Intel Corporation Device 7ad0 (rev 11)
00:1f.4 SMBus: Intel Corporation Device 7aa3 (rev 11)
00:1f.5 Serial bus controller [0c80]: Intel Corporation Device 7aa4 (rev 11)
01:00.0 VGA compatible controller: NVIDIA Corporation Device 2208 (rev a1)
01:00.1 Audio device: NVIDIA Corporation Device 1aef (rev a1)
02:00.0 Non-Volatile memory controller: Phison Electronics Corporation Device 5013 (rev 01)
03:00.0 Ethernet controller: Realtek Semiconductor Co., Ltd. RTL8125 2.5GbE Controller (rev 05)
04:00.0 Non-Volatile memory controller: Samsung Electronics Co Ltd Device a80a

ubuntu20.04, natively in OS, have installed Openvino runtime, 2021.1.110

**Comment by brmarkus** [comment]
The CPU "i9-12900KF" doesn't contain an integrated/embedded GPU.
The output of "$> lspci" doesn't show an Intel GPU - only an NVIDIA GPU.

The installation of OpenVINO, MediaSDK, the "source setupvars.sh" script and DL-Streamer components assume to run in an environment where at least one Intel GPU is available (integrated/embedded and/or discrete).

Your log-messages from "vainfo" shows that the media-driver of libva is taken from MediaSDK, called "iHD_drv_video.so" is supporting Intel GPUs, but not NVIDIA GPUs.
You might need to choose another media-driver, and configure it via ENV variables like `LIBVA_DRIVERS_PATH` and `LIBVA_DRIVER_NAME`.
