### ISSUE TITLE
adding frame data in a native element

### ISSUE THREAD

**Issue by scalers-ai** [dlstreamer/dlstreamer#281]
At present, the main DLStreamer element functionality seems to be to emit and publish inference metadata to messaging topics.

If the frame has to be manipulated, then one has to either write a C++ plugin or use GVAPython which is an order of magnitude slower.

Is there a way to add the frame data (binary) per message emitted? Yes, it would be "heavier", but still much more efficient than using Python at runtime - and much more efficient to develop than a custom C++ element.

e.g. gvametapublish add-frame-data=true ...

This could add a BLOB containing the image buffer. Is there something like this already?

**Comment by nnshah1** [comment]
@scalers-ai Independent of the ability to do remote processing of frame & results (which is a great feature add and something we've discussed as well) - can you give an example where the Python callback is too slow here? 

Given the use of numpy / opencv / etc. not much happens in pure Python and so want to also understand what kind of algorithms where Python is not applicable. This is more curiosity than a feedback no your request. 

In fact in the Pipeline Server we do support the notion of "frame destination" but today use that for visualization (i.e. rtsp / webrtc) or application (appsink) but not for remote processing. If you can supply a motivating example / prototype we could also explore.

**Comment by scalers-ai** [comment]
@nnshah1, thanks for the prompt feedback/response.

The "performance" issue is not apparent until we try to run multiple parallel inference streams with embedded gvapython.

e.g.

gst-launch... rtspsrc... ! gvadetect... ! gvapython... ! \
rtspsrc... ! gvaclassify... ! gvapython... (and so on)

Given than Python is generally 10-50 times slower than near-native stuff like C/C++/Rust etc (or even semi-native stuff like Golang), the idea is to avoid using the inline Python inference.

The tradeoff will be increased latency (bad) but ability to distribute AI post-processing (good) for application logic.

Visualization of the resulting feed is a good sub-use-case but that's only one limited scenario. The built in visualizations are quite limited, hence, better to do more interesting/intricate visualization in a different application process.

Hope that explains the thinking behind the request better.

Thanks
