### ISSUE TITLE
video resize to fit the input size of the model before running gvadetect?

### ISSUE THREAD

**Issue by kuanhenglee** [dlstreamer/dlstreamer#286]
If the input size of the model (e.g. object detection) is expecting a size of 240x240. Should we resize of the original video frame (e.g. 1920x1080) to 240x240 before calling the gvadetect? I notice that even without the resizing, the gvadetect is still working. Will the dlstreamer take care of the downsizing before running the model internally?

**Comment by brmarkus** [comment]
You provide a model-proc JSON file to the gvadetect plugin?

Depending on the model-proc file (and default-values) the conversion to what the model expect is done automatically (except for e.g. RGB-color-channel-swap).

With the model-proc and gvadetect attributes (like `pre-process-backend`) it can even be specified whether pre-processing shall be GPU-HW-accelerated by using GPU-zero-copy, or using e.g. OpenCV methods (usually using CPU).

But you can add pre-processing on your own to your pipeline if you need anything special like conversion to grey-scale, or applying letter-boxing, rotation, etc.

**Comment by akwrobel** [comment]
You do not need to resize as gvadetect will do this automatically based on the model requirements.
