### ISSUE TITLE
Dlstreamer benchmark sample fails with GPU as DECODE and INFERENCE device in 11th Gen Intel® Core™

### ISSUE THREAD

**Issue by kudupax** [dlstreamer/dlstreamer#287]
Precondition:
OpenVINO with GPU drivers is installed
DL streamer pipeline framework is installed through APT with packages intel-dlstreamer and intel-dlstreamer-samples
OpenVINO pre-trained model is downloaded and placed at HOME/intel/dl_streamer/models/intel/
Sample video (bolt-detection.mp4) is downloaded

Steps to reproduce:
1.	source /opt/intel/openvino_2022/setupvars.sh
2.	source /opt/intel/dlstreamer/setupvars.sh
3.	cd /opt/intel/dlstreamer/samples/benchmark/
4.	./benchmark.sh <path_to_videofile>/head-pose-face-detection-female-and-male.mp4 GPU GPU
(Tested with other video files too)

Outcome:
Pipeline run fails.

NOTE:
This was not observed with DECODE and INFERENCE devices as CPU-CPU, CPU-GPU and GPU-CPU combinations.

Error:
gst-launch-1.0 filesrc location=<PATH>/head-pose-face-detection-female-and-male.mp4 ! decodebin ! video/x-raw\(memory:DMABuf\) ! gvadetect model-instance-id=inf0 model=<HOME>/intel/dl_streamer/models/intel/face-detection-adas-0001/FP32/face-detection-adas-0001.xml device=GPU ! queue ! gvafpscounter ! fakesink async=false
Setting pipeline to PAUSED ...
Pipeline is PREROLLING ...
INFO:
/root/gst-video-analytics/gst/inference_elements/base/gva_base_inference.cpp(766): gva_base_inference_update_object_classes (): /GstPipeline:pipeline0/GvaDetectBin:gvadetectbin0/GstGvaDetect:gvadetect0:
empty inference instance: retry will be performed once instance will be acquired
Got context from element 'vaapipostproc0': gst.vaapi.Display=context, gst.vaapi.Display=(GstVaapiDisplay)"\(GstVaapiDisplayGLX\)\ vaapidisplayglx0", gst.vaapi.Display.GObject=(GstObject)"\(GstVaapiDisplayGLX\)\ vaapidisplayglx0";
Redistribute latency...
Pipeline is PREROLLED ...
Setting pipeline to PLAYING ...
New clock: GstSystemClock
ERROR: from element /GstPipeline:pipeline0/GvaDetectBin:gvadetectbin0/GstGvaDetect:gvadetect0: base_inference plugin initialization failed
Additional debug info:
/root/gst-video-analytics/gst/inference_elements/base/inference_singleton.cpp(172): acquire_inference_instance (): /GstPipeline:pipeline0/GvaDetectBin:gvadetectbin0/GstGvaDetect:gvadetect0:

Failed to construct OpenVINOImageInference
	basic_string_view::substr: __pos (which is 18446744073709551603) > __size (which is 47)
Execution ended after 0:00:00.263504425
ERROR: from element /GstPipeline:pipeline0/GvaDetectBin:gvadetectbin0/GstGvaDetect:gvadetect0: base_inference based element initialization has been failed.
Setting pipeline to NULL ...
Additional debug info:
/root/gst-video-analytics/gst/inference_elements/base/gva_base_inference.cpp(754): gva_base_inference_set_caps (): /GstPipeline:pipeline0/GvaDetectBin:gvadetectbin0/GstGvaDetect:gvadetect0:

inference is NULL.
ERROR: from element /GstPipeline:pipeline0/GvaDetectBin:gvadetectbin0/GstGvaDetect:gvadetect0: base_inference plugin initialization failed
Additional debug info:
/root/gst-video-analytics/gst/inference_elements/base/inference_singleton.cpp(172): acquire_inference_instance (): /GstPipeline:pipeline0/GvaDetectBin:gvadetectbin0/GstGvaDetect:gvadetect0:

Failed to construct OpenVINOImageInference
	basic_string_view::substr: __pos (which is 18446744073709551603) > __size (which is 47)
ERROR: from element /GstPipeline:pipeline0/GvaDetectBin:gvadetectbin0/GstGvaDetect:gvadetect0: base_inference based element initialization has been failed.
Additional debug info:
/root/gst-video-analytics/gst/inference_elements/base/gva_base_inference.cpp(754): gva_base_inference_set_caps (): /GstPipeline:pipeline0/GvaDetectBin:gvadetectbin0/GstGvaDetect:gvadetect0:

inference is NULL.
ERROR: from element /GstPipeline:pipeline0/GvaDetectBin:gvadetectbin0/GstGvaDetect:gvadetect0: base_inference failed on stop
Additional debug info:
/root/gst-video-analytics/gst/inference_elements/base/gva_base_inference.cpp(855): gva_base_inference_stop (): /GstPipeline:pipeline0/GvaDetectBin:gvadetectbin0/GstGvaDetect:gvadetect0:
empty inference instance
Freeing pipeline ...

**Comment by brmarkus** [comment]
Can you provide more details about your environment, please? Which OperatingSystem in which version? Which GPU-driver was installed?
Which version of gstreamer and libva and intel-media-driver have you installed?

Have you installed the "OpenVINO dependencies" (see https://docs.openvino.ai/latest/openvino_docs_install_guides_installing_openvino_linux.html#step-2-install-external-software-dependencies)?

Can you provide the output of the command `vainfo`, please?

Instead of using `decodebin`, can you fully qualify the "demuxing-parsing-decoding" instead and provide the output, please (like `qtdemux ! h264parse ! vaapih264dec`)?

Can you use `video/x-raw(memory:VASurface)` (to get GPU-zero-copy between the video-decoder and doing inference on the GPU) instead of `video/x-raw(memory:DMABuf)`?

**Comment by kudupax** [comment]
Please find the environment details. OpenVINO is installed with Step 2: Install External Software Dependencies and GPU setup.

Processor : 11th Gen Intel(R) Core(TM) i7-1185GRE @ 2.80GHz
platform: TIGERLAKE
Graphics : Mesa Intel® Xe Graphics( TGL GT2)

$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.4 LTS"

$ (dpkg-query --showformat='${Version}' --show intel-opencl-icd)
21.48.21782

gst-launch-1.0 --gst-version
GStreamer Core Library version 1.16.2
source /opt/intel/openvino_2022/setupvars.sh
[setupvars.sh] OpenVINO environment initialized
gst-launch-1.0 --gst-version
GStreamer Core Library version 1.16.2
source /opt/intel/dlstreamer/setupvars.sh
[setupvars.sh] GStreamer 1.18 environment initialized
[setupvars.sh] Intel(R) DL Streamer environment initialized
gst-launch-1.0 --gst-version
GStreamer Core Library version 1.18.4

$ vainfo
libva info: VA-API version 1.14.0
libva info: User environment variable requested driver 'iHD'
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_13
libva info: va_openDriver() returns 0
vainfo: VA-API version: 1.14 (libva 2.14.0)
vainfo: Driver version: Intel iHD driver for Intel(R) Gen Graphics - 21.4.1 (be92568)
vainfo: Supported profile and entrypoints

I was running the benchmark sample not exactly the gst-launch-1.0 commands directly.

Command 1: Instead of using decodebin, can you fully qualify the "demuxing-parsing-decoding" instead and provide the output, please (like qtdemux ! h264parse ! vaapih264dec)?
/opt/intel/dlstreamer/samples/benchmark$ gst-launch-1.0 filesrc location=/home/intel/head-pose-face-detection-female-and-male.mp4 ! qtdemux ! h264parse ! vaapih264dec ! video/x-raw\(memory:DMABuf\) ! gvadetect model-instance-id=inf0 model=/home/intel/intel/dl_streamer/models/intel/face-detection-adas-0001/FP32/face-detection-adas-0001.xml device=GPU ! queue ! gvafpscounter ! fakesink async=false
Setting pipeline to PAUSED ...
INFO:
/root/gst-video-analytics/gst/inference_elements/base/gva_base_inference.cpp(766): gva_base_inference_update_object_classes (): /GstPipeline:pipeline0/GvaDetectBin:gvadetectbin0/GstGvaDetect:gvadetect0:
empty inference instance: retry will be performed once instance will be acquired
Got context from element 'vaapidecode_h264-0': gst.vaapi.Display=context, gst.vaapi.Display=(GstVaapiDisplay)"\(GstVaapiDisplayGLX\)\ vaapidisplayglx0", gst.vaapi.Display.GObject=(GstObject)"\(GstVaapiDisplayGLX\)\ vaapidisplayglx0";
Pipeline is PREROLLED ...
Setting pipeline to PLAYING ...
New clock: GstSystemClock
Redistribute latency...
ERROR: from element /GstPipeline:pipeline0/GstQTDemux:qtdemux0: Internal data stream error.
Additional debug info:
../gst/isomp4/qtdemux.c(6545): gst_qtdemux_loop (): /GstPipeline:pipeline0/GstQTDemux:qtdemux0:
streaming stopped, reason not-negotiated (-4)
Execution ended after 0:00:00.004591231
Setting pipeline to NULL ...
ERROR: from element /GstPipeline:pipeline0/GvaDetectBin:gvadetectbin0/GstGvaDetect:gvadetect0: base_inference failed on stop
Additional debug info:
/root/gst-video-analytics/gst/inference_elements/base/gva_base_inference.cpp(855): gva_base_inference_stop (): /GstPipeline:pipeline0/GvaDetectBin:gvadetectbin0/GstGvaDetect:gvadetect0:
empty inference instance
Freeing pipeline ...


Command 2: Can you use video/x-raw(memory:VASurface) (to get GPU-zero-copy between the video-decoder and doing inference on the GPU) instead of video/x-raw(memory:DMABuf)?

$ gst-launch-1.0 filesrc location=/home/intel/head-pose-face-detection-female-and-male.mp4 ! decodebin ! video/x-raw\(memory:VASurface\) ! gvadetect model-instance-id=inf0 model=/home/intel/intel/dl_streamer/models/intel/face-detection-adas-0001/FP32/face-detection-adas-0001.xml device=GPU ! queue ! gvafpscounter ! fakesink async=false

(gst-plugin-scanner:11376): GStreamer-WARNING **: 12:01:44.440: Failed to load plugin '/opt/intel/dlstreamer/lib/libgvametapublishmqtt.so': libpaho-mqtt3a.so.1: cannot open shared object file: No such file or directory

(gst-plugin-scanner:11376): GStreamer-WARNING **: 12:01:44.484: Failed to load plugin '/opt/intel/dlstreamer/lib/libgvametapublishkafka.so': librdkafka++.so.1: cannot open shared object file: No such file or directory
Setting pipeline to PAUSED ...
Pipeline is PREROLLING ...
INFO:
/root/gst-video-analytics/gst/inference_elements/base/gva_base_inference.cpp(766): gva_base_inference_update_object_classes (): /GstPipeline:pipeline0/GvaDetectBin:gvadetectbin0/GstGvaDetect:gvadetect0:
empty inference instance: retry will be performed once instance will be acquired
Got context from element 'vaapipostproc0': gst.vaapi.Display=context, gst.vaapi.Display=(GstVaapiDisplay)"\(GstVaapiDisplayGLX\)\ vaapidisplayglx0", gst.vaapi.Display.GObject=(GstObject)"\(GstVaapiDisplayGLX\)\ vaapidisplayglx0";
Redistribute latency...
Pipeline is PREROLLED ...
Setting pipeline to PLAYING ...
New clock: GstSystemClock
ERROR: from element /GstPipeline:pipeline0/GvaDetectBin:gvadetectbin0/GstGvaDetect:gvadetect0: base_inference plugin initialization failed
Additional debug info:
/root/gst-video-analytics/gst/inference_elements/base/inference_singleton.cpp(172): acquire_inference_instance (): /GstPipeline:pipeline0/GvaDetectBin:gvadetectbin0/GstGvaDetect:gvadetect0:

Failed to construct OpenVINOImageInference
	basic_string_view::substr: __pos (which is 18446744073709551603) > __size (which is 47)
ERROR: from element /GstPipeline:pipeline0/GvaDetectBin:gvadetectbin0/GstGvaDetect:gvadetect0: base_inference based element initialization has been failed.
Additional debug info:
/root/gst-video-analytics/gst/inference_elements/base/gva_base_inference.cpp(754): gva_base_inference_set_caps (): /GstPipeline:pipeline0/GvaDetectBin:gvadetectbin0/GstGvaDetect:gvadetect0:

inference is NULL.
Execution ended after 0:00:00.165882544
Setting pipeline to NULL ...
ERROR: from element /GstPipeline:pipeline0/GvaDetectBin:gvadetectbin0/GstGvaDetect:gvadetect0: base_inference plugin initialization failed
Additional debug info:
/root/gst-video-analytics/gst/inference_elements/base/inference_singleton.cpp(172): acquire_inference_instance (): /GstPipeline:pipeline0/GvaDetectBin:gvadetectbin0/GstGvaDetect:gvadetect0:

Failed to construct OpenVINOImageInference
	basic_string_view::substr: __pos (which is 18446744073709551603) > __size (which is 47)
ERROR: from element /GstPipeline:pipeline0/GvaDetectBin:gvadetectbin0/GstGvaDetect:gvadetect0: base_inference based element initialization has been failed.
Additional debug info:
/root/gst-video-analytics/gst/inference_elements/base/gva_base_inference.cpp(754): gva_base_inference_set_caps (): /GstPipeline:pipeline0/GvaDetectBin:gvadetectbin0/GstGvaDetect:gvadetect0:

inference is NULL.
ERROR: from element /GstPipeline:pipeline0/GvaDetectBin:gvadetectbin0/GstGvaDetect:gvadetect0: base_inference failed on stop
Additional debug info:
/root/gst-video-analytics/gst/inference_elements/base/gva_base_inference.cpp(855): gva_base_inference_stop (): /GstPipeline:pipeline0/GvaDetectBin:gvadetectbin0/GstGvaDetect:gvadetect0:
empty inference instance
Freeing pipeline ...

**Comment by kudupax** [comment]
I used MobaXTerm. Without setting the DISPLAY it works. If i set the display (export DISPLAY=:0), then the same error is shown only for DECODE - GPU, INFERENCE - GPU.

**Comment by tobiasmo1** [comment]
@kudupax - It sounds like the reported error occurs only when an invalid value is assigned to DISPLAY.

The [MobaXterm documentation](https://mobaxterm.mobatek.net/documentation.html#6_2) states this may already be assigned by default as `localhost:10.0` or `:10.0`.  If so the runtime value would need to be preserved so do not override the value for DISPLAY environment variable by assigning it manually.

Additional background can be found [here](https://unix.stackexchange.com/questions/470331/mobaxterm-x11-forwarding-issue-with-unix).

Can you confirm this resolves the issue for you?

**Comment by kudupax** [comment]
I tried with the VNCviewer by connecting to a system connected to a single monitor. 
Here also i observed the same issue when DECODE and INFERENCE devices as GPU GPU. But it worked for other combinations CPU CPU, CPU GPU, GPU CPU.
I will try this on a fresh system and update here to avoid multiple EVN variable settings.

**Comment by sbin149x** [comment]
Hi. I'm wondering if you're able to fix this issue? Since I get the same error when running DECODE and INFERENCE on the GPU device when using the Ubuntu terminal directly, but it works when using SSH because I didn't export DISPLAY. I will open a new issue later if needed for system and error details.

**Comment by akwrobel** [comment]
Closing as there has been no follow up from the submitter.  This appears to be an environmental setup issue.
