### ISSUE TITLE
How to use latest OpenVINO with dl streamer？

### ISSUE THREAD

**Issue by wdkwyf** [dlstreamer/dlstreamer#288]
Is there anyway we can use the self-built openvino with dl streamer without using the APT install one？

**Comment by brmarkus** [comment]
Would it be possible for you to use "https://github.com/dlstreamer/dlstreamer/releases" (pre-buit, or built from source), v1.6, "[Release 2022.1](https://github.com/dlstreamer/dlstreamer/releases/tag/v1.6)" together with your self-built OpenVINO?

**Comment by wdkwyf** [comment]
Hi, @brmarkus . I need to use the latest openvino with dl streamer, instead of 2022.1 version.

**Comment by brmarkus** [comment]
The "latest" OpenVINO is still close to and still very similar to the latest published version "2022.1".
If you use the latest OpenVINO then the latest public version of DL-Streamer (v1.6) should still work, as it was made for OpenVINO v2022.1.

Have you tried?
Have you run into troubles?

**Comment by wdkwyf** [comment]
I agree that latest OV might be compatible, but is there any guide how can we use self-built OpenVINO with DL streamer?&nbsp;



---Original---
From: "Markus ***@***.***&gt;
Date: Wed, Jun 29, 2022 19:14 PM
To: ***@***.***&gt;;
Cc: "Yufei ***@***.******@***.***&gt;;
Subject: Re: [dlstreamer/dlstreamer] How to use latest OpenVINO with dl streamer？ (Issue #288)




 
The "latest" OpenVINO is still close to and still very similar to the latest published version "2022.1".
 If you use the latest OpenVINO then the latest public version of DL-Streamer (v1.6) should still work, as it was made for OpenVINO v2022.1.
 
Have you tried?
 Have you run into troubles?

**Comment by brmarkus** [comment]
When you use your environment "natively" (not within e.g. a Docker container), then use Option #3, like this:
https://dlstreamer.github.io/get_started/install/install_guide_ubuntu.html#id3

But instead of installing a pre-built OpenVINO, you build (`make`) and install (`make install`) it.

Before building DL-Streamer from source, don't forget to "source" the OpenVINO environment (like `source /opt/intel/openvino_2022/setupvars.sh`); this way ENV variables to library-search-paths, header-search-paths and cmake-package-search-path environments would be exported and exposed.
While building the installed (and build from source) OpenVINO depencies and development-resources could be found.

**Comment by wdkwyf** [comment]
Hi, when the OV is built from source, user has to link the necessary dependence by himself by 'export LD_LIBRARY_PATH=xxxx'. I didnt find there is such simple "source setupvars.sh" to complete the env setting in self-built OV. So I wonder if DL Streamer can explicitly show the env setting in the user guide? For example, user should add opencv.so and openvino.so path to LD_LIBRARY_PATH because they are the dependency of DL Streamer. It can help to save user's time when they saw annoying error message such as "there is no element gvadetect"



---Original---
From: "Markus ***@***.***&gt;
Date: Sun, Jul 3, 2022 01:24 AM
To: ***@***.***&gt;;
Cc: "Yufei ***@***.******@***.***&gt;;
Subject: Re: [dlstreamer/dlstreamer] How to use latest OpenVINO with dl streamer？ (Issue #288)




 
When you use your environment "natively" (not within e.g. a Docker container), then use Option #3, like this:
 https://dlstreamer.github.io/get_started/install/install_guide_ubuntu.html#id3
 
But instead of installing a pre-built OpenVINO, you build (make) and install (make install) it.
 
Before building DL-Streamer from source, don't forget to "source" the OpenVINO environment (like source /opt/intel/openvino_2022/setupvars.sh); this way ENV variables to library-search-paths, header-search-paths and cmake-package-search-path environments would be exported and exposed.
 While building the installed (and build from source) OpenVINO depencies and development-resources could be found.

**Comment by brmarkus** [comment]
If you clone the sources of OpenVINO, then you will find `scripts/setupvars/setupvars.sh`.

Follow the OpenVINO Wiki under https://github.com/openvinotoolkit/openvino/wiki/BuildingCode.

Build and install OpenVINO - by giving an <INSTALLDIR>.
This way the "source script" will be installed as well under <INSTALLDIR>.

If the build succeeded and OpenVINO got installed to <INSTALLDIR>, then call `source <INSTALLDIR>/setupvars.sh`.

If you look inside it, then you will find export-ENV-variables like: InferenceEngine_DIR, ngraph_DIR, OpenVINO_DIR, IE_PLUGINS_PATH, HDDL_INSTALL_DIR, LD_LIBRARY_PATH and more.

With these exposed ENV variables CMAKE/MAKE of DL-Streamer will be able to find the locally build and installed OpenVINO development-resources.

**Comment by wdkwyf** [comment]
this script file exists because it will be included into the final installation package(also you can see the setupvars.bat in script directory). However, if you run the script in your self built environment , no correct env will be settled because installation package and self-built OV have different file org structures.&nbsp;



---Original---
From: "Markus ***@***.***&gt;
Date: Sun, Jul 3, 2022 02:24 AM
To: ***@***.***&gt;;
Cc: "Yufei ***@***.******@***.***&gt;;
Subject: Re: [dlstreamer/dlstreamer] How to use latest OpenVINO with dl streamer？ (Issue #288)




 
If you clone the sources of OpenVINO, then you will find scripts/setupvars/setupvars.sh.
 
Follow the OpenVINO Wiki under https://github.com/openvinotoolkit/openvino/wiki/BuildingCode.
 
Build and install OpenVINO - by giving an .
 This way the "source script" will be installed as well under .
 
If the build succeeded and OpenVINO got installed to , then call source <INSTALLDIR&gt;/setupvars.sh.
 
If you look inside it, then you will find export-ENV-variables like: InferenceEngine_DIR, ngraph_DIR, OpenVINO_DIR, IE_PLUGINS_PATH, HDDL_INSTALL_DIR, LD_LIBRARY_PATH and more.
 
With these exposed ENV variables CMAKE/MAKE of DL-Streamer will be able to find the locally build and installed OpenVINO development-resources.

**Comment by brmarkus** [comment]
Can you describe in more details how you build and installed OpenVINO? Have you built it only? Have you also installed it to a custom installation directory (or default installation-directory)?
I build it and install it to "/opt/intel/openvino/", and can call `source /opt/intel/openvino/setupvars.sh`.

What does your installation directory structure look like?

**Comment by wdkwyf** [comment]
all openvino related .so files are in bin/x64/release directory .
opencv related .so files are in xxx/temp/ directory.



---Original---
From: "Markus ***@***.***&gt;
Date: Sun, Jul 3, 2022 02:58 AM
To: ***@***.***&gt;;
Cc: "Yufei ***@***.******@***.***&gt;;
Subject: Re: [dlstreamer/dlstreamer] How to use latest OpenVINO with dl streamer？ (Issue #288)




 
Can you describe in more details how you build and installed OpenVINO? Have you built it only? Have you also installed it to a custom installation directory (or default installation-directory)?
 I build it and install it to "/opt/intel/openvino/", and can call source /opt/intel/openvino/setupvars.sh.
 
What does your installation directory structure look like?

**Comment by wdkwyf** [comment]
I ignore and skip the install process with only build process. That's why I cannot&nbsp; use simple setupvars.sh file and have to find and manage all env variables by myself. Thanks for pointing that!



---Original---
From: "Markus ***@***.***&gt;
Date: Sun, Jul 3, 2022 02:58 AM
To: ***@***.***&gt;;
Cc: "Yufei ***@***.******@***.***&gt;;
Subject: Re: [dlstreamer/dlstreamer] How to use latest OpenVINO with dl streamer？ (Issue #288)




 
Can you describe in more details how you build and installed OpenVINO? Have you built it only? Have you also installed it to a custom installation directory (or default installation-directory)?
 I build it and install it to "/opt/intel/openvino/", and can call source /opt/intel/openvino/setupvars.sh.
 
What does your installation directory structure look like?

**Comment by akwrobel** [comment]
DLStreamer releases support specific versions of OpenVINO as listed in the release page.  Custom setup is outside of the scope of this project.
