### ISSUE TITLE
Can not install DL Streamer 2022.1 on Ubuntu 18.04

### ISSUE THREAD

**Issue by fantashi099** [dlstreamer/dlstreamer#289]
Hi,

I am facing an issue of the newest DeepLearning Streamer installation from APT repository. I tried Option 1 and Option 3 in Install Guide Ubuntu but did not work (same issue).

Error: Unable to locate package intel-dlstreamer-dev

I am currently using DL Streamer 2021.4 from Openvino installation.

Many thanks.

**Comment by mikhail-nikolskiy** [comment]
Sorry, installation via APT packages supported on Ubuntu 20.04 (version 2022.1) and will be supported on Ubuntu 22.04 (future versions), not supported on Ubuntu 18.04.
But you can build DL Streamer from source code following instructions in https://dlstreamer.github.io/get_started/install/install_guide_ubuntu.html#id3

**Comment by fantashi099** [comment]
I did try installing from source but the problem still couldn't solve
Error: Unable to locate package OpenVINO™

**Comment by brmarkus** [comment]
Can you fully specify at which step, which commands, which scripts you face the issue?

Originally you reported "Error: Unable to locate package intel-dlstreamer-dev", now you see "Error: Unable to locate package OpenVINO™".

Performing which steps show you these errors?

It could just be you missed to call "source /opt/intel/openvino/bin/setupvars.sh", which sets and exposes library-search-path and other ENV variables helping to find OpenVINO's libraries, header-files, plugins, modules.

**Comment by fantashi099** [comment]
Option #1: Install Intel® DL Streamer Pipeline Framework from APT repository
Step 1: Install required packages
_Option a : (Recommended) Specific GPU driver versions used in OpenVINO™ and Pipeline Framework validation_

Command: 
```sh
# Install Intel® DL Streamer Pipeline Framework and recommended version of media driver
$ sudo apt-get update && sudo apt-get install intel-dlstreamer-dev
```

Error:
```sh
E: Unable to locate package intel-dlstreamer-dev
```

_Option b: For latest OpenCL™ and media driver versions_

Command:

```sh
# Install
sudo apt-get update && sudo apt-get install intel-dlstreamer-dev
```

Errror:
```sh
E: Unable to locate package intel-dlstreamer-dev
```

---

Option #3: Compile Intel® DL Streamer Pipeline Framework from sources on host system
Step 2: Install Intel® Distribution of OpenVINO™ Toolkit
Install required packages:
```sh
sudo apt-get update && sudo apt-get install -y OpenVINO™ openvino-opencv
```

Error:
```sh
E: Unable to locate package OpenVINO™
```

**Comment by brmarkus** [comment]
As mentioned above under "https://github.com/dlstreamer/dlstreamer/issues/289#issuecomment-1167655719" under your older Ubuntu 18.04 you cannot install DL-Streamer or OpenVINO via "apt-get install"; this is suported with Ubuntu 20.04 and newer only.

> Sorry, installation via APT packages supported on Ubuntu 20.04 (version 2022.1) and will be supported on Ubuntu 22.04 (future versions), not supported on Ubuntu 18.04. But you can build DL Streamer from source code following instructions in https://dlstreamer.github.io/get_started/install/install_guide_ubuntu.html#id3

**Comment by fantashi099** [comment]
Thanks a lot for the quick response.
