### ISSUE TITLE
Missing plugin(s) in `intel-dlstreamer-gst-plugins-base` (Ubuntu 20.04)

### ISSUE THREAD

**Issue by RyanHir** [dlstreamer/dlstreamer#291]
Hello, I am installing dlstreamer using the APT guide at https://dlstreamer.github.io/get_started/install/install_guide_ubuntu.html and I am able to use the VA-API functionality correctly on my machines. However, I need to use the `opengl` plugin (provided by `gst-plugins-base`) in my pipeline but it appears that this is not packaged in `intel-dlstreamer-gst-plugins-base`.

I would prefer not having to rebuild GStreamer for deployment. Is it possible to include this plugin into the repository package?

**Comment by mikhail-nikolskiy** [comment]
DL Streamer installs GStreamer 1.18 and sets environment variable `GST_PLUGIN_PATH=
/opt/intel/dlstreamer/gstreamer/lib/gstreamer-1.0`.
Some plugins not enabled in GStreamer build configuration, opengl is one of these plugins.
You can try workaround
```
ln -s /usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstopengl.so /opt/intel/dlstreamer/gstreamer/lib/gstreamer-1.0/
```
to make system installed opengl plugin (GStreamer 1.16, if Ubuntu 20.04) visible to GStreamer 1.18 installed by DL Streamer.

Another potential workaround is add the whole folder with system installed plugins to GST_PLUGIN_PATH (important to add after DL Streamer path, not before)
```
GST_PLUGIN_PATH=
/opt/intel/dlstreamer/gstreamer/lib/gstreamer-1.0:/usr/lib/x86_64-linux-gnu/gstreamer-1.0
```

**Comment by akwrobel** [comment]
As mentioned above this is a result of the custom GStreamer that DLStreamer uses not including these plugins as they are not supported by current DLStreamer usages.  As there has been no follow up from the submitter this issue is being closed.
