### ISSUE TITLE
Erroe: Unable to locate package intel-dlstreamer-gst

### ISSUE THREAD

**Issue by KiwiHana** [dlstreamer/dlstreamer#292]

**Comment by KiwiHana** [comment]
guide: https://dlstreamer.github.io/get_started/install/install_guide_ubuntu.html#option-3-compile-intel-dl-streamer-pipeline-framework-from-sources-on-host-system

$ sudo apt-get install -y --no-install-recommends intel-dlstreamer-gst cmake build-essential libpython3-dev python-gi-dev
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package intel-dlstreamer-gst

$ curl https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB | sudo apt-key add -
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:02:10 --:--:--     0
curl: (7) Failed to connect to apt.repos.intel.com port 443: Connection timed out
gpg: no valid OpenPGP data found.

**Comment by brmarkus** [comment]
Have you called "sudo apt-get update"?
Looks like you are behind a corporate network proxy (http_proxy, https_proxy, maybe even no_proxy)?

**Comment by KiwiHana** [comment]
> Have you called "sudo apt-get update"? Looks like you are behind a corporate network proxy (http_proxy, https_proxy, maybe even no_proxy)?

Yes, my device behind a corporate network proxy. After execute $sudo apt-get update, I still can't install intel-dlstreamer-gst

**Comment by mikhail-nikolskiy** [comment]
As stated in guide, the following three steps should succeed before "apt install intel-dlstreamer-gst"
```
curl https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB | sudo apt-key add -
echo "deb https://apt.repos.intel.com/openvino/2022 `. /etc/os-release && echo ${UBUNTU_CODENAME}` main" | sudo tee /etc/apt/sources.list.d/intel-openvino-2022.list
sudo apt-get update
```

You can also refer to OpenVINO APT install docs here https://docs.openvino.ai/latest/openvino_docs_install_guides_installing_openvino_apt.html

**Comment by KiwiHana** [comment]
> As stated in guide, the following three steps should succeed before "apt install intel-dlstreamer-gst"
> 
> ```
> curl https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB | sudo apt-key add -
> echo "deb https://apt.repos.intel.com/openvino/2022 `. /etc/os-release && echo ${UBUNTU_CODENAME}` main" | sudo tee /etc/apt/sources.list.d/intel-openvino-2022.list
> sudo apt-get update
> ```
> 
> You can also refer to OpenVINO APT install docs as DL Streamer shares same APT repository https://docs.openvino.ai/latest/openvino_docs_install_guides_installing_openvino_apt.html

This command can't execute successfully.
$ curl https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB | sudo apt-key add -
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:02:11 --:--:--     0
curl: (7) Failed to connect to apt.repos.intel.com port 443: Connection timed out
gpg: no valid OpenPGP data found.

**Comment by brmarkus** [comment]
When you are behind a corporate network proxy, then have you configured the following?

* /etc/apt/apt.conf.d/proxy.conf
acquire::http::proxy "http://my-proxy.com:port/";
acquire::https::proxy "http://my-proxy.com:port/";

* /etc/environment
http_proxy="http://my-proxy.com:port/"
https_proxy="http://my-proxy.com:port/"
no_proxy="127.0.0.1,localhost,.my-company.com"

Depending on your company, you might add "intel.com" to your "no_proxy" ;-)

**Comment by KiwiHana** [comment]
> When you are behind a corporate network proxy, then have you configured the following?
> 
> * /etc/apt/apt.conf.d/proxy.conf
>   acquire::http::proxy "http://my-proxy.com:port/";
>   acquire::https::proxy "http://my-proxy.com:port/";
> * /etc/environment
>   http_proxy="http://my-proxy.com:port/"
>   https_proxy="http://my-proxy.com:port/"
>   no_proxy="127.0.0.1,localhost,.my-company.com"
> 
> Depending on your company, you might add "intel.com" to your "no_proxy" ;-)

Yes, I have modify proxy in /etc/environment, but the error still exist.

**Comment by brmarkus** [comment]
Can you reach "https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB" at all? I tried with MS-Windows in my corporate network with curl and wget.
And also tried via Linux in my laboratory network with curl, wget and with the browser.

**Comment by KiwiHana** [comment]
Closed. This issue caused by Proxy.
