### ISSUE TITLE
CMAKE Failed: Could NOT find OpenCL Could not find a package configuration file provided by "OpenCV" 

### ISSUE THREAD

**Issue by KiwiHana** [dlstreamer/dlstreamer#294]
Ubuntu20.04
refer: https://dlstreamer.github.io/get_started/install/install_guide_ubuntu.html#option-3-compile-intel-dl-streamer-pipeline-framework-from-sources-on-host-system

~/intel/dlstreamer_gst/build$ cmake -DCMAKE_INSTALL_PREFIX=/opt/intel/dlstreamer  ..
-- CMAKE_BUILD_TYPE is undefined. Set default build type Release.
CMake Warning at CMakeLists.txt:28 (message):
  GIT_INFO is undefined.  Set default value 0.

ENABLE_PAHO_INSTALLATION=OFF
ENABLE_RDKAFKA_INSTALLATION=OFF
-- Could NOT find OpenCL (missing: OpenCL_LIBRARY OpenCL_INCLUDE_DIR) 
OpenCL not found. OpenCL-based elements won't be available.
-- Could NOT find OpenCL (missing: OpenCL_LIBRARY OpenCL_INCLUDE_DIR) 
CMake Warning at src/opencv/CMakeLists.txt:9 (find_package):
  By not providing "FindOpenCV.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "OpenCV", but
  CMake did not find one.

  Could not find a package configuration file provided by "OpenCV" with any
  of the following names:

    OpenCVConfig.cmake
    opencv-config.cmake

  Add the installation prefix of "OpenCV" to CMAKE_PREFIX_PATH or set
  "OpenCV_DIR" to a directory containing one of the above files.  If "OpenCV"
  provides a separate development package or SDK, be sure it has been
  installed.

CMake Error at gst/elements/CMakeLists.txt:11 (find_package):
  By not providing "FindOpenCV.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "OpenCV", but
  CMake did not find one.

  Could not find a package configuration file provided by "OpenCV" with any
  of the following names:

    OpenCVConfig.cmake
    opencv-config.cmake

  Add the installation prefix of "OpenCV" to CMAKE_PREFIX_PATH or set
  "OpenCV_DIR" to a directory containing one of the above files.  If "OpenCV"
  provides a separate development package or SDK, be sure it has been
  installed.

-- Configuring incomplete, errors occurred!
See also "/home/adc-iot/intel/dlstreamer_gst/build/CMakeFiles/CMakeOutput.log".
See also "/home/adc-iot/intel/dlstreamer_gst/build/CMakeFiles/CMakeError.log".

**Comment by KiwiHana** [comment]
closed https://github.com/dlstreamer/dlstreamer/issues/139

**Comment by sbin149x** [comment]
Hi @KiwiHana. I encountered the same error when try to build dlstreamer using source code for v1.6, can you share how to solve the error?

**Comment by brmarkus** [comment]
You might want to create a new GITHUB issue and provide details about your environment (HW and SW).

How have you started to prepare the environment, have you installed the pre-requisites (like OpenVINO, as described under "https://dlstreamer.github.io/get_started/install/install_guide_ubuntu.html#option-3-compile-intel-dl-streamer-pipeline-framework-from-sources-on-host-system")?

Which version of OpenVINO have you installed, how have you installed it? Have you encountered warnings or errors while installing OpenVINO? Have you done a quick test of the standalone OpenVINO installation (like using some of the demos, checking with `hello_query_device` to see if the underlying HW is detected and supported)?

OpenCL could be tricky as there are dependencies to the used HW - do you run on an Intel-CPU (with an Intel-GPU)?

**Comment by KiwiHana** [comment]
> Hi @KiwiHana. I encountered the same error when try to build dlstreamer using source code for v1.6, can you share how to solve the error?
Try this command:
# Install
sudo apt-get update && sudo apt-get install -y intel-opencl-icd ocl-icd-opencl-dev opencl-clhpp-headers
