### ISSUE TITLE
SHORT_TERM can not be used

### ISSUE THREAD

**Issue by bigbosshuang** [dlstreamer/dlstreamer#296]
some TrackingType can not be used in the new version,such as SHORT_TERM

**Comment by fantashi099** [comment]
With regard to the newest version document, short-term now change to short-term-imageless in the tracking-type property. Useful Link: https://dlstreamer.github.io/elements/gvatrack.html or you can find more information on release note.

**Comment by akwrobel** [comment]
As @fantashi099 pointed out above, SHORT_TERM was removed with the last release, 

Please see the Deprecation Notices in this release: https://github.com/dlstreamer/dlstreamer/releases/tag/v1.6

_Deprecation Notices
Object tracking type 'short-term' deprecated and removed in gvatrack element. Either replace 'tracking-type=short-term' with 'tracking-type=zero-term' and remove 'inference-interval=N' property in gvadetect/gvaclassify, or replace 'tracking-type=short-term' with 'tracking-type=short-term-imageless'_
