### ISSUE TITLE
How to use dlstreamer to run non deep learning algorithm.

### ISSUE THREAD

**Issue by zhcf** [dlstreamer/dlstreamer#297]
I want to use dlstramer to run my non deep learning algorithm which is written using opencv,  is it possible?

**Comment by akwrobel** [comment]
Yes, it is possible.  Please see the documentation here: https://dlstreamer.github.io/dev_guide/custom_processing.html

**Comment by akwrobel** [comment]
Closing due to age and no update from the submitter.
