### ISSUE TITLE
How to save the inference result for the past few frame?

### ISSUE THREAD

**Issue by zhouzhou0322** [dlstreamer/dlstreamer#300]
Hi, I need to detect whether an object is stopped.  I am trying to develop based on the [Vehicle and Pedestrian Tracking Sample](https://github.com/dlstreamer/dlstreamer/tree/master/samples/gst_launch/vehicle_pedestrian_tracking). I add a python callback to catch  
each frame. How do I save the inference result(bbox and object ID) for later use?

**Comment by nnshah1** [comment]
The `video_frame` class has methods to retrieve the detections (region bounding boxes) and each region has an object id. You can find the class methods & descriptions here: 

https://github.com/dlstreamer/dlstreamer/tree/master/python/gstgva 

A sample demonstrating how to get the region objects here:

https://github.com/dlstreamer/dlstreamer/blob/master/samples/python/draw_face_attributes/draw_face_attributes.py#L39

For a more advanced example from the pipeline server project you can also check the implementation of basic line crossing:

https://github.com/dlstreamer/pipeline-server/blob/c2ece52901f322af588fa8565de53314f2f95010/extensions/spatial_analytics/object_line_crossing.py#L46

**Comment by zhouzhou0322** [comment]
> The `video_frame` class has methods to retrieve the detections (region bounding boxes) and each region has an object id. You can find the class methods & descriptions here:
> 
> https://github.com/dlstreamer/dlstreamer/tree/master/python/gstgva
> 
> A sample demonstrating how to get the region objects here:
> 
> https://github.com/dlstreamer/dlstreamer/blob/master/samples/python/draw_face_attributes/draw_face_attributes.py#L39
> 
> For a more advanced example from the pipeline server project you can also check the implementation of basic line crossing:
> 
> https://github.com/dlstreamer/pipeline-server/blob/c2ece52901f322af588fa8565de53314f2f95010/extensions/spatial_analytics/object_line_crossing.py#L46

Thank you, great reference code.
