### ISSUE TITLE
how to use gvametaaggregate?

### ISSUE THREAD

**Issue by SuperElectron** [dlstreamer/dlstreamer#301]
Is there an example that shows how to use "gvametaaggregate"?

Here is pipeline I am trying to make work:

`mkdir -p /device_media/root/logs/;
export DETECTION_MODEL="/device_media/root/models/intel/person-vehicle-bike-detection-2004/FP16/person-vehicle-bike-detection-2004.xml"`
`export THRESHOLD=0.5`
`export MODEL_PROC="/device_media/root/configs/person-vehicle-bike-detection-2004.json"`
`export DETECTIONS_JSON1="/device_media/root/logs/multisrc-detection1.json"`
`export DETECTIONS_JSON2="/device_media/root/logs/multisrc-detection2.json"`
`export DETECTIONS_JSON3="/device_media/root/logs/multisrc-detection3.json"`

`GST_DEBUG_DUMP_DOT_DIR=/device_media/root/logs GST_DEBUG=3 gst-launch-1.0 -e \
  filesrc location="${VIDEO1}" ! \
    qtdemux ! \
    h264parse config-interval=-1 ! \
    avdec_h264 ! \
    gvadetect batch-size=1 model="${DETECTION_MODEL}" device=CPU threshold="${THRESHOLD}" model-proc="${MODEL_PROC}" model-instance-id="primary_detector" ! \
    gvatrack tracking-type=short-term name="tracker1" ! \
    queue max-size-time=3000000000 name=q1 ! \
    gvametaconvert name="gvametaconvert_1" format=0 json-indent=2 source="Left" add-empty-results=0 ! \
    gvametapublish method=file file-path="${DETECTIONS_JSON1}" ! \
  m.sink_1 filesrc location="${VIDEO1}" ! \
      qtdemux ! \
      h264parse config-interval=-1 ! \
      avdec_h264 ! \
      gvadetect batch-size=1 model="${DETECTION_MODEL}" device=CPU threshold="${THRESHOLD}" model-proc="${MODEL_PROC}" model-instance-id="primary_detector" ! \
      gvatrack tracking-type=short-term name="tracker2" ! \
      queue max-size-time=3000000000 name=q2 ! \
      gvametaconvert name="gvametaconvert_2" format=0 json-indent=2 source="Right" add-empty-results=0 ! \
      gvametapublish method=file file-path="${DETECTIONS_JSON2}" ! \
  m.sink_0 gvametaaggregate name=m ! \
  gvametaconvert name="gvametaconvert_3" format=0 json-indent=2 add-empty-results=0 ! \
  gvametapublish method=file file-path="${DETECTIONS_JSON3}" ! \
      gvawatermark ! videoconvert ! autovideosink`
      
Here is the output .dot file converted to png

[
![PAUSED_PLAYING4](https://user-images.githubusercontent.com/11896926/184430724-37a8ee2d-cf05-412a-a8d8-c72798908bc8.png)
](url)

**Steps up to replicate**

Docker image: [openvino/ubuntu20_data_dev](https://hub.docker.com/r/openvino/ubuntu20_data_dev)

`mkdir - p /device_media/root/streams/`
`wget https://github.com/intel-iot-devkit/sample-videos/raw/master/person-bicycle-car-detection.mp4`
`find /opt -name download.py -type f`

- use the script to download `person-vehicle-bike-detection-2004.json` with the following command

`python3 download.py --name person-vehicle-bike-detection-2004.json`

-check the export from the script above, and move things into their appropriate location

`docker run -it --name intel \
	--env="XAUTHORITY=${XAUTH}" \
	--env="DISPLAY=${DISPLAY}" \
	--device /dev/dri \
	--user=0 \
	--net=host \
	--privileged \
	-v ~/.Xauthority:/root/.Xauthority \
	-v /tmp/.X11-unix/:/tmp/.X11-unix/ \
	-v "/dev:/dev" \
	-v "/device_media:/device_media" \
	openvino/ubuntu20_data_dev:latest`

- run the script above, and take note that gvametaconvert uses `source="Left"` or `source="Right"`  to mark the json files with its source
- check multisrc-detection1.json ("Left") and multisrc-detection2.json ("Right") to see if separate pipelines are getting results
- view video to see that two boxes are being drawn for one detection
- view multisrc-detection3.json ("combined?") and there is only "Left"

**Problem**
Why isn't the metadata being combined with `gvametaaggregate` so that we can dump it and see it in multisrc-detection3json

**Comment by brmarkus** [comment]
Do you see the following pipeline working for you, seen here: https://github.com/dlstreamer/dlstreamer/issues/127 ?

> Schematic pipeline with gvametaaggreagate element:
> filesrc ! decodebin ! videoconvert ! video/x-raw,format=I420 ! tee name=t t. ! queue ! gvametaaggregate name=a ! gvawatermark ! videoconvert ! fpsdisplaysink t. ! queue ! videoscale(300x300) ! gvadetect model=model.xml ! a.

**Comment by SuperElectron** [comment]
Thanks for the example bmarkus.  I should clarify a bit on what I am trying to achieve ...

1. What does gvametaaggregate do, and why would someone want it in a pipeline
2. In my example, I am trying to aggregate metadata from 2 sources. I can just use one source, as shown below, and it works. But ... what additional functionality does gvametaaggregate provide?

`mkdir -p /device_media/root/logs/; export DETECTION_MODEL="/device_media/root/models/intel/person-vehicle-bike-detection-2004/FP16/person-vehicle-bike-detection-2004.xml"`
`export THRESHOLD=0.5`
`export MODEL_PROC="/device_media/root/configs/person-vehicle-bike-detection-2004.json"`
`export DETECTIONS_JSON1="/device_media/root/logs/multisrc-detection1.json"`


`GST_DEBUG_DUMP_DOT_DIR=/device_media/root/logs GST_DEBUG=3 gst-launch-1.0 -e filesrc location="${VIDEO1}" ! qtdemux ! h264parse config-interval=-1 ! avdec_h264 ! gvadetect batch-size=1 model="${DETECTION_MODEL}" device=CPU threshold="${THRESHOLD}" model-proc="${MODEL_PROC}" model-instance-id="primary_detector" ! gvatrack tracking-type=short-term name="tracker1" ! queue max-size-time=3000000000 name=q1 ! gvametaconvert name="gvametaconvert_1" format=0 json-indent=2 source="Left" add-empty-results=0 !  gvametapublish method=file file-path="${DETECTIONS_JSON1}"`

**Comment by nnshah1** [comment]
metaggregate is used to aggregate multiple metadata onto the same frame from a single source (that is if you are doing detection + classification in different branches on the same frame). It will in fact only output the frame from the first sink pad (aggregating all metadata from all sink pads onto the frame for the first sink pad).

typically for your use case (multiple sources to kafka) - we would have seperate metapublish elements with perhaps the same topic and do the aggregation in the message bus as opposed to the pipeline.

If you really need to have a single gvametapublish, you could try a funnel element. Please note I don't know if it will work - but it might be worth trying. In that case it would look something like:

pipeline1 --> gvametaconvert -> funnel
pipeline2 --> gvametaconvert -> funnel -> gvametapublish -> fakesink
pipeline3 --> gvametaconvert -> funnel 

From my understanding funnel will just forward the individual frames without trying to synchronize anything.
