### ISSUE TITLE
How to print out the error traceback message when use the gvapython module.

### ISSUE THREAD

**Issue by zhouzhou0322** [dlstreamer/dlstreamer#303]
Hi, there. I am developing using gvapython element. There's  no trackback info when something is wrong in my gvapython python script. (shown below ) Btw, I am using the gst-launch to start a pipeline. Is there any way I can print out the python trackout.

> gst-launch-1.0 v4l2src device=/dev/video2 ! image/jpeg,width=1920,height=1080,framerate=30/1 ! jpegparse ! jpegdec ! videorate ! videoscale ! videoconvert ! video/x-raw,format=BGRx,framerate=30/1 ! gvadetect model=/models/intel/face-detection-adas-0001/FP16-INT8/face-detection-adas-0001.xml inference-interval=1 threshold=0.4 device=CPU ! queue ! gvatrack tracking-type=zero-term ! gvapython module=/share/tidy-dlstreamer/tidy-dlstreamer-2022.1.0/source/dlstreamer/samples/gst_launch/gvapython/tracking/postproc_callbacks/detect_post.py class=ObjectIsStopping function=process_frame ! gvawatermark ! videoconvert ! gvafpscounter ! autovideosink sync=false
Setting pipeline to PAUSED ...
ERROR: from element /GstPipeline:pipeline0/GstGvaPython:gvapython0: Error creating Python callback
Additional debug info:
/root/gst-video-analytics/gst/elements/gvapython/gstgvapython.c(228): gst_gva_python_start (): /GstPipeline:pipeline0/GstGvaPython:gvapython0:
Module: /share/tidy-dlstreamer/tidy-dlstreamer-2022.1.0/source/dlstreamer/samples/gst_launch/gvapython/tracking/postproc_callbacks/detect_post.py
 Class: ObjectIsStopping
 Function: process_frame
 Arg: []
 Keyword Arg: {}

**Comment by zhouzhou0322** [comment]
> Try setting the GST_DEBUG level to >= 3. That typically gives more details.
> 
> `export GST_DEBUG=3`

I set export GST_DEBUG=gvapython:5

Still no traceback info tell me which line go wrong.(see below) Its very time consuming to figure out what's wrong.


> ` Class: ObjectIsStopping
 Function: process_frame
 Arg: []
 Keyword Arg: {}

ERROR: from element /GstPipeline:pipeline0/GstGvaPython:gvapython0: Error creating Python callback
Additional debug info:
/root/gst-video-analytics/gst/elements/gvapython/gstgvapython.c(228): gst_gva_python_start (): /GstPipeline:pipeline0/GstGvaPython:gvapython0:
Module: /share/tidy-dlstreamer/tidy-dlstreamer-2022.1.0/source/dlstreamer/samples/gst_launch/gvapython/tracking/postproc_callbacks/detect_post.py
 Class: ObjectIsStopping
 Function: process_frame
 Arg: []
 Keyword Arg: {}

ERROR: pipeline doesn't want to preroll.
Failed to set pipeline to PAUSED.
Setting pipeline to NULL ...
Freeing pipeline ...
0:00:00.375283998 1279795 0x560707c6a470 DEBUG              gvapython gstgvapython.c:249:gst_gva_python_dispose:<gvapython0> dispose
0:00:00.375293598 1279795 0x560707c6a470 DEBUG              gvapython gstgvapython.c:259:gst_gva_python_finalize:<gvapython0> finalize`

**Comment by zhouzhou0322** [comment]
>  Class: ObjectIsStopping
 Function: process_frame
 Arg: []
 Keyword Arg: {}

ERROR: from element /GstPipeline:pipeline0/GstGvaPython:gvapython0: Error creating Python callback
Additional debug info:
/root/gst-video-analytics/gst/elements/gvapython/gstgvapython.c(228): gst_gva_python_start (): /GstPipeline:pipeline0/GstGvaPython:gvapython0:
Module: /share/tidy-dlstreamer/tidy-dlstreamer-2022.1.0/source/dlstreamer/samples/gst_launch/gvapython/tracking/postproc_callbacks/detect_post.py
 Class: ObjectIsStopping
 Function: process_frame
 Arg: []
 Keyword Arg: {}

ERROR: pipeline doesn't want to preroll.
0:00:00.345759464 1301989 0x55e7420382a0 WARN                GST_PADS gstpad.c:1142:gst_pad_set_active:<gvapython0:sink> Failed to activate pad
Failed to set pipeline to PAUSED.
Setting pipeline to NULL ...
Freeing pipeline ...


here's what print out with GST_DEBUG=3, still no traceback

**Comment by nnshah1** [comment]
unfortunately I think you'll need to add try / catch, print statements to narrow down if it is related to loading the file or if it can find the file.

Generally errors can be:

1) not able to find or load the file
2) not able to initialize the class
3) error while running process_frame

Since this seems at creation time - I would suggest starting with a simple script that just has an empty 'process_frame' and then add imports -
