### ISSUE TITLE
vaapi stops working correctly intermittently 

### ISSUE THREAD

**Issue by papasanimohansrinivas** [dlstreamer/dlstreamer#305]
hi dlstreamer team,

I am running dlstreamer:devel docker on xeon e2286g bare metal dedicated server from vultr , and in bios boot menu  I have enabled integrated graphics card too , when i initialise my pipeline with 

```GST_DEBUG=3 gst-launch-1.0 udpsrc port=10000   ! queue !   h264parse ! vaapidecodebin  !  videorate ! video/x-raw,width=312,height=312 ,framerate=1/1  ! videoconvert ! capsfilter  caps="video/x-raw,format=BGR"  ! gvapython module=xeon_gva_python.py class=custom_accumulator function=process_frame arg={\\\"cam_no\\\":\\\"1\\\"} ! fakesink async=false```

pipeline runs but for every 5 hours pipeline doesnot run showing below statements 

```
videodecoder gstvideodecoder.c:1448:gst_video_decoder_sink_event_default:<vaapidecode0> upstream tags: taglist, video-codec=(string)"H.264\ \(Main\ Profile\)", minimum-bitrate=(uint)8080, maximum-bitrate=(uint)160080, bitrate=(uint)27246;
0:00:04.417700189    55 0x55e7662c3b00 WARN             vaapidecode gstvaapidecode.c:778:gst_vaapidecode_handle_frame:<vaapidecode0> decode error -1
0:00:04.417734799    55 0x55e7662c3b00 WARN            videodecoder gstvideodecoder.c:4361:_gst_video_decoder_error:<vaapidecode0> error: Decoding error
0:00:04.417755512    55 0x55e7662c3b00 WARN            videodecoder gstvideodecoder.c:4363:_gst_video_decoder_error:<vaapidecode0> error: Decode error -1
0:00:04.417774714    55 0x55e7662c3b00 INFO             vaapidecode gstvaapidecode.c:789:gst_vaapidecode_handle_frame:<vaapidecode0> requesting upstream a key unit
0:00:04.417820212    55 0x55e7662c3b00 INFO               h264parse gsth264parse.c:3632:gst_h264_parse_src_event:<h264parse0> received upstream force-key-unit event, seqnum 243 running_time 99:99:99.999999999 all_headers 0 count 0

```
then i had to reboot server for vaapi to properly working again 

kindly provide a solution to this !

**Comment by akwrobel** [comment]
Hi @papasanimohansrinivas please try running without gvapython as this is not a supported use case
You can find the support list here: https://docs.openvino.ai/2022.1/openvino_docs_OV_UG_supported_plugins_Supported_Devices.html
Which is lists support for Intel HD or IRIS

**Comment by akwrobel** [comment]
@papasanimohansrinivas please update after trying the steps above.  This issue will remain open until the end of the year pending your response.
