### ISSUE TITLE
 inference-interval  in gvadetect 

### ISSUE THREAD

**Issue by howarwang** [dlstreamer/dlstreamer#306]
I set  inference-interval of gvadetect as 5 and expected to do inference on frame index: 1, 6, 11,16,....
But looks gvadetect didnt skip frames still inferenced on each frame. To verify it, I printed rois on frame buffer, the frame indice are continuous no jumping and also printed timestamp for each buffer which contains rois, the interval is 40ms (25 fps).
Is there any other place should be configured?

**Comment by mikhail-nikolskiy** [comment]
Can you please share gst-launch pipeline (including how do you print results)?

**Comment by akwrobel** [comment]
@howarwang can you please share the requested information?
