### ISSUE TITLE
frame duplication for entire time duration 

### ISSUE THREAD

**Issue by papasanimohansrinivas** [dlstreamer/dlstreamer#307]
hi guys i am perplexed with an issue,  here is the gst-launch-1.0 command i am trying 

`/opt/intel/dlstreamer/gstreamer/bin/gst-launch-1.0 -vvvv udpsrc port=10016   ! queue !   h264parse ! vaapih264dec  !  vaapipostproc  ! videoconvert ! capsfilter  caps="video/x-raw,format=BGR"  ! videorate drop-only=true  max-rate=5 silent=false average-period=100000000 ! video/x-raw,width=312,height=312 ,framerate=1/1  ! gvapython module=xeon_gva_python.py class=custom_accumulator function=process_frame arg={\\\"cam_no\\\":\\\"17\\\"} ! fakesink async=false`

goal here is to accumulate 1 frame per second until 16 frames are collected and pushed to a queue on other server 

but when i am checking i am getting 2 frames repeated for entire 16 frames , can u guys point me in the right direction here !

do let me know if u guys need more info for this !

**Comment by mikhail-nikolskiy** [comment]
This is probably related to properties in videorate element and caps filter "framerate=1/1", there is no other gva* elements besides gvapython.

**Comment by akwrobel** [comment]
Closed due to age and no response from submitter.
