### ISSUE TITLE
How to let gvawatermark draw some custom parameters like confidence for each detection?

### ISSUE THREAD

**Issue by zhouzhou0322** [dlstreamer/dlstreamer#309]
Try to modify the tracking demo`https://github.com/dlstreamer/dlstreamer/tree/master/samples/gst_launch/vehicle_pedestrian_tracking`(gst-launch). For now, the image window only draw the tracking id. How to draw other parameters like confidence for each detection? Do I need to rebuild the gvawatermark plugin. If so, any examples I can reference?

**Comment by mikhail-nikolskiy** [comment]
If you convert confidence to string and add it as labels, gvawatermark should visualize it.
It could be done similar to this example
https://github.com/dlstreamer/dlstreamer/blob/master/samples/gst_launch/gvapython/face_detection_and_classification/postproc_callbacks/age_gender_classification.py
(like below, not tested)
```
from gstgva import VideoFrame

def process_frame(frame: VideoFrame) -> bool:
    for roi in frame.regions():
        roi.add_tensor("confidence").set_label(str(roi.confidence()))

    return True
```

**Comment by zhouzhou0322** [comment]
Thanks you. BTW, is there any build plugin example I can reference if I want to write some customized plugin just like gvawatermark?
