### ISSUE TITLE
Error while running pose estimation using webcam as input

### ISSUE THREAD

**Issue by PulkitMishra** [dlstreamer/dlstreamer#313]
I am on a Linux system(PopOS to be specific) and am running DL Streamer Pipeline Framework via Docker image.

I start the container as -

`sudo docker run --rm -it --user root --device /dev/video0:/dev/video0 -e DISPLAY -e QT_X11_NO_MITSHM=1 -v /tmp/.X11-unix:/tmp/.X11-unix -v $HOME/.Xauthority:/root/.Xauthority -v ~/Desktop/dlstreamer-dev:/home/dlstreamer dlstreamer/dlstreamer:devel /bin/bash`

Inside the container when I run inference on a video file by : 
`./human_pose_estimation.sh testA.mp4 CPU display` it works just fine 

but when I try webcam as input 
`./human_pose_estimation.sh /dev/video0 CPU display`

I get the error

> gst-launch-1.0 v4l2src device=/dev/video0 ! decodebin ! gvaclassify model=/home/dlstreamer/intel/dl_streamer/models/intel/human-pose-estimation-0001/FP32/human-pose-estimation-0001.xml model-proc=./model_proc/human-pose-estimation-0001.json device=CPU inference-region=full-frame ! queue ! gvafpscounter ! fakesink async=false
> error: XDG_RUNTIME_DIR not set in the environment.
> Setting pipeline to PAUSED ...
> Pipeline is live and does not need PREROLL ...
> INFO:
> /root/gst-video-analytics/gst/inference_elements/base/gva_base_inference.cpp(766): gva_base_inference_update_object_classes (): /GstPipeline:pipeline0/GvaClassifyBin:gvaclassifybin0/GstGvaClassify:gvaclassify0:
> empty inference instance: retry will be performed once instance will be acquired
> Pipeline is PREROLLED ...
> Setting pipeline to PLAYING ...
> New clock: GstSystemClock
> WARNING: from element /GstPipeline:pipeline0/GstDecodeBin:decodebin0: Delayed linking failed.
> Additional debug info:
> gst/parse/grammar.y(540): gst_parse_no_more_pads (): /GstPipeline:pipeline0/GstDecodeBin:decodebin0:
> failed delayed linking some pad of GstDecodeBin named decodebin0 to some pad of GvaClassifyBin named gvaclassifybin0
> ERROR: from element /GstPipeline:pipeline0/GstV4l2Src:v4l2src0: Internal data stream error.
> Additional debug info:
> ../libs/gst/base/gstbasesrc.c(3127): gst_base_src_loop (): /GstPipeline:pipeline0/GstV4l2Src:v4l2src0:
> streaming stopped, reason not-linked (-1)
> Execution ended after 0:00:00.465295377
> Setting pipeline to NULL ...
> ERROR: from element /GstPipeline:pipeline0/GvaClassifyBin:gvaclassifybin0/GstGvaClassify:gvaclassify0: base_inference failed on stop
> Additional debug info:
> /root/gst-video-analytics/gst/inference_elements/base/gva_base_inference.cpp(855): gva_base_inference_stop (): /GstPipeline:pipeline0/GvaClassifyBin:gvaclassifybin0/GstGvaClassify:gvaclassify0:
> empty inference instance
> Freeing pipeline ...

Is this a bug with the example itself or am I doing something incorrectly

**Comment by brmarkus** [comment]
You might need to check your camera's (preferred) default mode (like resolution, color-format, framerate).

For instance the USB-webcam "Logitech HD Pro Webcam C920" shows via `v4l2-ctl --list-formats-ext` (you would need to install `sudo apt-get install v4l-utils`) the supported formats.

Your used camera might use an "exotic" set of properties (check for the set of attributes with `Index       : 0`).
You (e.g. via `v4l2-ctl --set-fmt-video... ... ...`) or your application might have changed the format into an exotic one for which the pipeline would need to be adapted.

Can you try to manually get a simplified gstreamer command line working, something like the following?

(might need to set the ENV variables `DISPLAY` and/or `XDG_RUNTIME_DIR` first)

`gst-launch-1.0 v4l2src device=/dev/video0 ! 'video/x-raw,format=(string)YUY2,width=640,height=480' ! videoconvert ! xvimagesink`

`gst-launch-1.0 v4l2src device=/dev/video0 ! image/jpeg,width=640,height=480,framerate=30/1 ! jpegdec ! xvimagesink`

`gst-launch-1.0 v4l2src device=/dev/video0 ! video/x-h264,width=800,height=600,framerate=30/1 ! vaapih264dec ! xvimagesink`

**Comment by PulkitMishra** [comment]
Thanks for the quick response @brmarkus 
Yes that is indeed the case. !videoconvert was missing in [pose estimation](https://github.com/dlstreamer/dlstreamer/tree/master/samples/gst_launch/human_pose_estimation) (which is otherwise present in other samples like [here](https://github.com/dlstreamer/dlstreamer/blob/master/samples/gst_launch/action_recognition/action_recognition.sh)). Submitted a quick fix for the same. Please check #314 I have tested script with with file source, uri and webcam
