### ISSUE TITLE
How to pass user defined metadata through the pipeline?

### ISSUE THREAD

**Issue by zhouzhou0322** [dlstreamer/dlstreamer#316]
Is there any way I can pass some customized metadata through the pipeline?

**Comment by brmarkus** [comment]
You might find additional information in another issue/question like this:
"https://github.com/dlstreamer/dlstreamer/issues/178" ("How to attach and extract custom metadata generated by custom written plugin?")

**Comment by zhouzhou0322** [comment]
Thank you. Any code I can refer to if I want to build some customized element plugin?

**Comment by rmnchopra91** [comment]
please take a look into "[#329](https://github.com/dlstreamer/dlstreamer/issues/329)"
