### ISSUE TITLE
Does the docker image '2022.1.1-ubuntu20-devel' support yolov5 inference?

### ISSUE THREAD

**Issue by howarwang** [dlstreamer/dlstreamer#319]
I tried to use yolov5 on this image but failed. Also noticed in the latest repo and the yolo-v5.json post-proc has jsut been added. So It means yolov5 could be supported in the next release? Thanks in advance.

**Comment by mikhail-nikolskiy** [comment]
Yes, yolov5 support coming soon in 2022.2 release.

**Comment by howarwang** [comment]
Thanks Mikhail.

**Comment by howarwang** [comment]
@mikhail-nikolskiy  I just tested yolov5 in dlstreamer 2022.2 pre-release but failed. I followed this [guide](https://dlstreamer.github.io/get_started/install/install_guide_ubuntu.html#id4) to build container. The shell script like below:

#!/bin/bash
# ==============================================================================
# Copyright (C) 2020-2022 Intel Corporation
#
# SPDX-License-Identifier: MIT
# ==============================================================================

set -e

# Command-line parameters
INPUT=${1:-https://github.com/intel-iot-devkit/sample-videos/raw/master/person-bicycle-car-detection.mp4} # Input file or URL
DETECTION_INTERVAL=${2:-3}     # Object detection interval: 1 means detection every frame, 2 means detection every second frame, etc.
DEVICE=${3:-AUTO}              # Device for decode and inference in OpenVINO(TM) format, examples: AUTO, CPU, GPU, GPU.0
OUTPUT=${4:-display-async}     # Output type, valid values: display, display-async, fps, json, display-and-json
TRACKING_TYPE=${5:-short-term-imageless} # Object tracking type, valid values: short-term-imageless, zero-term, zero-term-imageless

# Reclassify interval (run classification every 10th frame)
RECLASSIFY_INTERVAL=10

if [[ $INPUT == "/dev/video"* ]]; then
  SOURCE_ELEMENT="v4l2src device=${INPUT}"
elif [[ $INPUT == *"://"* ]]; then
  SOURCE_ELEMENT="urisourcebin buffer-size=4096 uri=${INPUT}"
else
  SOURCE_ELEMENT="filesrc location=${INPUT}"
fi

if [[ $DEVICE == "CPU" ]]; then
  DECODE_ELEMENT="decodebin force-sw-decoders=true"
elif [[ $DEVICE == "GPU" ]]; then
  DECODE_ELEMENT="decodebin ! video/x-raw\(memory:VASurface\)"
else
  DECODE_ELEMENT="decodebin"
fi

if [[ $OUTPUT == "display" ]]; then
  SINK_ELEMENT="gvawatermark ! videoconvert ! gvafpscounter ! autovideosink"
elif [[ $OUTPUT == "display-async" ]]; then
  SINK_ELEMENT="gvawatermark ! videoconvert ! gvafpscounter ! autovideosink sync=false"
elif [[ $OUTPUT == "fps" ]]; then
  SINK_ELEMENT="gvafpscounter ! fakesink async=false "
elif [[ $OUTPUT == "json" ]]; then
  rm -f output.json
  SINK_ELEMENT="gvametaconvert ! gvametapublish file-format=json-lines file-path=output.json ! fakesink async=false"
elif [[ $OUTPUT == "display-and-json" ]]; then
  rm -f output.json
  SINK_ELEMENT="gvawatermark ! gvametaconvert ! gvametapublish file-format=json-lines file-path=output.json ! videoconvert ! gvafpscounter ! autovideosink sync=false"
else
  echo Error wrong value for OUTPUT parameter
  echo Valid values: "display" - render to screen, "fps" - print FPS, "json" - write to output.json, "display-and-json" - render to screen and write to output.json
  exit
fi

PROC_PATH() {
    echo $(dirname "$0")/model_proc/$1.json
}

DETECTION_MODEL=/models/object-recognition/yolov5s/yolov5s-roaduser.xml
DETECTION_MODEL_PROC=/opt/intel/dlstreamer/samples/model_proc/public/yolo-v5.json
 

PIPELINE="gst-launch-1.0 \
  ${SOURCE_ELEMENT} ! ${DECODE_ELEMENT} ! queue ! \
  gvadetect model=$DETECTION_MODEL \
            model-proc=$DETECTION_MODEL_PROC \
            inference-interval=${DETECTION_INTERVAL} \
            threshold=0.4 \
            device=${DEVICE} ! \
  queue ! \
  gvatrack tracking-type=${TRACKING_TYPE} ! \
 
  queue ! \
  $SINK_ELEMENT"

echo ${PIPELINE}
eval $PIPELINE


**The pipeline failed due to the reason:**

ERROR: from element /GstPipeline:pipeline0/GstGvaDetect:gvadetect0: base_inference based element initialization has been failed.
Additional debug info:
/home/dlstreamer/dlstreamer/gst/inference_elements/base/gva_base_inference.cpp(768): gva_base_inference_set_caps (): /GstPipeline:pipeline0/GstGvaDetect:gvadetect0:

post-processing is NULL.
Execution ended after 0:00:00.727231600
Setting pipeline to NULL ...
ERROR: from element /GstPipeline:pipeline0/GstGvaDetect:gvadetect0: base_inference failed on frame processing
Additional debug info:
/home/dlstreamer/dlstreamer/gst/inference_elements/base/gva_base_inference.cpp(918): gva_base_inference_transform_ip (): /GstPipeline:pipeline0/GstGvaDetect:gvadetect0:

Failed to submit images to inference
        Mapper is null
Freeing pipeline ...

**Comment by howarwang** [comment]
Or should I use GvaInference ?

**Comment by mikhail-nikolskiy** [comment]
Please try 2022.2, source code and Debian packages and Docker images now released!
Install guide: https://dlstreamer.github.io/get_started/install/install_guide_ubuntu.html
