### ISSUE TITLE
dlstreamer and pyinstaller 

### ISSUE THREAD

**Issue by Sharan-Sundar** [dlstreamer/dlstreamer#326]
Hi, 
I am currently developing code to perform object-detection on live rtsp streams.
I am using `OpenVINO 2022.1` ( installed using PyPI ) and `DLStreamer` ( installed from APT repository ). This is on `Ubuntu 20.04.5 LTS`.

I am currently using `Pyinstaller` ( 5.5 ) to convert my scripts into executable files. This is mainly for security reasons when deploying in edge devices - to not reveal source code.

My code script is based on the [draw_face_attributes.py](https://github.com/dlstreamer/dlstreamer/blob/master/samples/gstreamer/python/draw_face_attributes/draw_face_attributes.py) in Samples/. This is the script that I am trying to convert into an exe file using pyinstaller.

The problem I face is, when I run that exe file, I get - `WARNING: erroneous pipeline: no element "gvadetect"`
This means that the DLStreamer environment is not initialized. I am not able to figure out how to convert a python file with DLStreamer elements into an exe file. I get the same error even when I run exe after running `source /opt/intel/dlstreamer/setupvars.sh`. I am trying to see how to initialize the environment within the exe file.

Now, I know that my issue is more of an question than a bug. But I hope that you give me some way out or suggestions for this. I have seen similar issues and threads on the OpenVINO forums regarding the OpenVINO API and I was able to get that working without having to initialize OpenVINO environment. But I am not able make DLStreamer and Pyinstaller work.

Looking forward to your response.
Thank you.

**Comment by akwrobel** [comment]
Hi @Sharan-Sundar can you confirm which version of DL Streamer you are using?  The latest versions of DLS and OpenVINO are both 2022.2, and we recommend using the latest versions.  From your comments it looks like there may be a mismatch.

**Comment by Sharan-Sundar** [comment]
Hi @akwrobel ,
I have installed DL Streamer using [APT](https://dlstreamer.github.io/get_started/install/install_guide_ubuntu.html#option-1-install-intel-dl-streamer-pipeline-framework-from-apt-repository) so I am assuming it's the latest version - your latest build https://apt.repos.intel.com/openvino/2022.

But my problem is not with that as DLStreamer and OpenVINO work perfectly when I run the python script. My problems comes only when I use pyinstaller and convert the script into an exe.

**Comment by akwrobel** [comment]
Closed due to age
