### ISSUE TITLE
[Question] Default Gvadetect->Gvaclassify Pipeline Use Resized frame?

### ISSUE THREAD

**Issue by wdkwyf** [dlstreamer/dlstreamer#327]
Hi, assume the original frame is 1920x1080, OpenVINO detect model input size is 416x416, classify model is 112x112. Can I suppose the following assumption?
1: gvadetect and gvaclassify will resize the input frame automatically (in this case, resize frame to 416x416 and 112x112 respectively) if no reshape setting.
2: If the output ROI region shape is 50x50 from gvadetect, the gvaclassify will crop the 50x50 from the resized 416x416 frame.
3: If I want to crop from original frame, I need to use gvametaaggregate? https://github.com/dlstreamer/dlstreamer/issues/127#issuecomment-719586619

**Comment by nnshah1** [comment]
1) Yes - this is correct - input is resized automatically to input of inference
2) No - in this case gvaclassify will crop from the original resolution. That is if the ROI shape is 50x50 in 416x416 - it will be updated to the correct coordinates in the original frame (1920x1080) and cropped from original frame before scaling to 112x112)
3) No need

**Comment by wdkwyf** [comment]
> 1. Yes - this is correct - input is resized automatically to input of inference
> 2. No - in this case gvaclassify will crop from the original resolution. That is if the ROI shape is 50x50 in 416x416 - it will be updated to the correct coordinates in the original frame (1920x1080) and cropped from original frame before scaling to 112x112)
> 3. No need

@nnshah1 Got it. thanks very much!
