### ISSUE TITLE
gstreamer-vaapi-patches

### ISSUE THREAD

**Issue by sbin149x** [dlstreamer/dlstreamer#328]
Hi. I would like to know if we build dlstreamer from source code, do we have to apply the gstreamer-vaapi-patches manually to be able to use pre-process-backend="vaapi" ?

Thanks.

**Comment by mikhail-nikolskiy** [comment]
We recommend GStreamer 1.20, the pre-process-backend="vaapi" (and "vaapi-surface-sharing") works on GStreamer 1.20 without any patches. You can either install it via 
```
sudo apt-get install -y intel-dlstreamer-gst
source /opt/intel/dlstreamer/gstreamer/setupvars.sh
```
or build from GStreamer 1.20 source code.
