### ISSUE TITLE
Not able to add some custom data in gvametaconvert0 of Gvametaconvert element of DL streamer

### ISSUE THREAD

**Issue by rmnchopra91** [dlstreamer/dlstreamer#329]
I am able to add custom data in `gvametaconvert0` of `Gvametaconvert `element of **DL streamer**.
default json format is like **`{"objects":[...],  "resolution":{"height":720,"width":1280},  "timestamp":2122644783}`** which I am receiving at the mqtt broker. But I want to add `currentTime` that will be system/machine time in parallel to available `timestamp`  in mentioned JSON

I go into the git code of [dlstreamer](https://github.com/dlstreamer/dlstreamer) and found  `get_frame_data` of [file](https://github.com/dlstreamer/dlstreamer/blob/master/gst/elements/gvametaconvert/jsonconverter.cpp). Do I need to add here new property currentTime or I am getting it wrong ?

**Comment by nnshah1** [comment]
Yes - that is correct - that file is the correct place to modify if you want to add additional metadata directly into the json message before publication on a message bus.

One other option is if you insert a callback or gvapython element after gvametaconvert but before gvametapublish - you can access the messages() of the frame and alter them before publication to the message bus.

Here is an example that adds "events" to a frame : https://github.com/dlstreamer/pipeline-server/blob/552608a1168e8034db1643aef143adc3adb8a91e/extensions/gva_event_meta/gva_event_meta.py#L18 

Note: the metapublish element only publishes the first message currently - thus the operation to edit a message is:

1) get original message string
2) modify message string
3) remove original message string from frame
4) set new message string to frame

**Comment by rmnchopra91** [comment]
Hey,
thanks for the reply on my query. Now i am facing another challenge in my case.
I am using below piece of code.
```
gvametaconvert format=json add-empty-results=true ! \
gvapython module=test.py class=test function=add_data arg=[{}] name=gvapython_{} ! \
gvametapublish method= mqtt address={}:1884 topic=traffic_stats/{}/{}/traffic  ! \
```
But the issue is after adding gvapython(2nd line) in the script. No data is sending at the 1884 port. If i am removing line 2 then data is passing properly.

**Comment by nnshah1** [comment]
is it possible to show the test.py code you are using? My guess is that you are removing the message but not setting it again.

**Comment by rmnchopra91** [comment]
In test.py below code is written:
```
def add_data(self, frame: VideoFrame) -> bool:
        try:
            t = time.localtime()
            current_time = time.strftime("%H:%M:%S", t)
            current_time_stamp = "currenttimestamp: " + current_time
            print("original message : " , frame.messages())
            frame.add_message(current_time_stamp)
            print("modified message : " , frame.messages())
        except NameError:
            print("frame is not defined")
```

**Comment by rmnchopra91** [comment]
If I am calling `frame.remove_message(frame.messages())` then I am getting exception:
![image](https://user-images.githubusercontent.com/26848414/200835441-357bcfe7-85d1-483f-9fab-a4727e4de072.png)

**Comment by rmnchopra91** [comment]
this above exception is resolved by this code `frame.remove_message(frame.messages()[0])`
But still I am not able to get the data at mosca side after adding this gvapython element in my pipeline

**Comment by rmnchopra91** [comment]
```
def add_data(self, frame: VideoFrame) -> bool:
        "write your code here what ever you want to do"
        return True
```
I missed to mention return statement here. Because of that I was not getting expected data at another endpoint(mosca)

**Comment by rmnchopra91** [comment]
I am closing it, because it works for me as expected.
