### ISSUE TITLE
How can dlstreamer 2022.2 support yolov6 or yolov7?

### ISSUE THREAD

**Issue by howarwang** [dlstreamer/dlstreamer#333]
I followed yolov5 way to convert yolov7 from pytorch to onnx and then to openvino IR, but failed to infer in the pipeline.
(I have specified the output node of IR )

**Comment by brmarkus** [comment]
Can you provide more details an what you have tried, what you have installed in which versions, testing which programs and scripts, using what command line parameters?

You might try using OpenVINO directly, first - not requiring to create a `model-proc` file now.

Commenting on Yolo-V7, this is what I used:

```
$> git clone https://github.com/WongKinYiu/yolov7.git
$> wget https://github.com/WongKinYiu/yolov7/releases/download/v0.1/yolov7-tiny.pt
$> wget https://github.com/WongKinYiu/yolov7/releases/download/v0.1/yolov7.pt
```
Exporting to ONNX:

```
$> python export.py --weights yolov7-tiny.pt --grid --end2end --simplify --topk-all 100 --iou-thres 0.65 --conf-thres 0.35 --img-size 640 640 --max-wh 640
$> python export.py --weights yolov7.pt --grid --end2end --simplify --topk-all 100 --iou-thres 0.65 --conf-thres 0.35 --img-size 640 640 --max-wh 640
```

And then using the ONNX with OpenVINO - no need to convert to IR-format:
```
$> ./benchmark_app -m /myfolder/yolov7-tiny.onnx -d CPU -api async -niter 100
$> ./benchmark_app -m /myfolder/yolov7.onnx -d CPU -api async -niter 100
```

And then you might want to have a closer look into the Open-Model-Zoo samples for e.g. object-detection - and what pre- and what post-procession is required (like non-max-suppression NMS).

**Comment by brmarkus** [comment]
Soon you can find an OpenVINO Notebook with a Yolo-V7 Tutorial (PullRequest "https://github.com/openvinotoolkit/openvino_notebooks/pull/654/files"), covering these topics:

- Prepare PyTorch model
- Download and prepare dataset
- Validate original model
- Convert PyTorch model to ONNX
- Convert ONNX model to OpenVINO IR
- Validate converted model
- Prepare and run optimization pipeline
- Compare accuracy of the FP32 and quantized models
- Compare performance of the FP32 and quantized models

**Comment by howarwang** [comment]
Thanks @brmarkus , I tried to convert yolov7 pt to onnx but didnt simply onnx model, which looks workable but the bboxes apparently are not accurate. If I convert to simplied onnx,  it doesnt work in dlstreamer pipeline. 
So I guess, there are something below should be considered:
1. The output nodes from simplied and unsimiplied onnx are quite different
2. NMS and activation parameters are required to config

**Comment by sathyanarayanmc** [comment]
We have trained a Yolov7 model and converted to openvino by folowing this steps ' https://docs.openvino.ai/latest/notebooks/226-yolov7-optimization-with-output.html ' 

filesrc location=5.jpg     videoconvert n-threads=4 ! capsfilter caps="video/x-raw,format=BGR" ! gvainference model-instance-id=yolov7-tiny.xml  gvapython module=yolo_filter.py  video-sink=xvimagesink sync=false

The output we get out of dlstreamer in yolo_filter is quite different from the output of the model 

Can you please help us with inferencing in dlstreamer of yolo v7 and yolo v8

**Comment by akwrobel** [comment]
Yolov7 and V8 are not currently in the DL streamer support path, and there is no plan to add this support in currently supported version.
