### ISSUE TITLE
How to use gdb to debug dlstreamer?

### ISSUE THREAD

**Issue by SilvaXiang** [dlstreamer/dlstreamer#337]
I want to see the data flow inside dlstreamer. I wonder how to use gdb to debug dlstreamer?

**Comment by brmarkus** [comment]
Doesn't this sound like a basic gstreamer question?
DL-Streamer is a collection of gstreamer plugin, like so many other gstreamer plugins.

Have you tried searching with your favorite search-engine?
Basic debugging&logging, example: "https://gstreamer.freedesktop.org/documentation/tutorials/basic/debugging-tools.html?gi-language=c"

GDB with gstreamer plugin, example: "https://developer.ridgerun.com/wiki/index.php/GStreamer_Debugging_Using_GDB"
