### ISSUE TITLE
Gvadetect  and gvatrack - only track objects inside custom region of interest

### ISSUE THREAD

**Issue by PavanKumar13** [dlstreamer/dlstreamer#339]
Hi,

I am trying to track objects only inside the selected/custom ROI, I tried two combinations,

**gvainference -> gvapython -> gvatrack ,**
I removed objects which lie outside the ROI using some custom function and passing only the remaining objects to gvatrack for tracking, this works fine but in the process of parsing detection results to yolo I can see the drop in fps and a lot of frames being dropped.

**gvadetect -> gvapython -> gvatrack** 
I tried the same thing to remove objects outside ROI using the custom function, but I cannot remove the metadata going to gvatrack,
so all the objects are getting tracked. I don't see a drop in fps, but uninterested objects are being tracked consuming a lot of CPU.

Is there a way to remove the objects from metadata, before giving the bounding boxes to gvatrack?

Openvino version used: 2021.4
Target Device: Intel Xeon Gold + 8x Myriad VPU

Please give any suggestions to improve the performance of this device.

Thanks in advance

**Comment by PavanKumar13** [comment]
Hi,

Any updates/suggestion on the issue.


Thanks

**Comment by brmarkus** [comment]
Will your inference inside and outside the ROI create lots of lots of objects, that the processing is so time-consuming?
Would it help to do a NMS/non-max-suppression first?
Could lots of objects be filtered via a confidence-level first?

Can you find a suitable (pre- and/or )post-processing step under "https://dlstreamer.github.io/dev_guide/how_to_create_model_proc_file.html"?

**Comment by changtimwu** [comment]
@PavanKumar13 According to your description, I believe it's totally doable in dlstreamer.  

Below is clips of my pipeline and gvapython module.   Objects detected outside the ROI(as the `roizone` variable below) won't be overlayed. 

```sh
gvadetect model=$detmodel model-proc=$detproc pre-process-backend=vaapi-surface-sharing device=GPU ! \
gvapython module=metafilter.py ! \
meta_overlay device=GPU ! \
```

metafilter.py
```py
from gstgva import VideoFrame
from shapely.geometry import Polygon,box

def in_interested( roi) -> bool:
    [x,y,w,h] = roi.rect()
    b = box( x, y, x+w, y+h)
    overlap = roizone.intersection(b)
    instead = overlap. Area > (0.7 * b.area) # The object is mostly inside the region.
    #if not instead:
    #    print('{} area {} not interested'.format(roi.rect(), b.area ))
    return instead

def process_frame(frame: VideoFrame) -> bool:
    width = frame.video_info().width
    height = frame.video_info().height
    drois=[]
    for roi in frame. Regions():
        if not in_interested( roi):
            drois.append(roi)
    for roi in drois:
        frame.remove_region(roi)
    return True
```

**Comment by PavanKumar13** [comment]
> his usage is not suppo

Hi @changtimwu,

Awesome, this is what i was looking for, Thanks for the reply


Thanks,
Pavan

**Comment by akwrobel** [comment]
Closed due to lack of response and age.
