### ISSUE TITLE
Any plan to release docker images packed with OpenVINO 2022.3?

### ISSUE THREAD

**Issue by changtimwu** [dlstreamer/dlstreamer#340]
According to [the tag list of the official DL-Streamer docker repo](https://hub.docker.com/r/intel/dlstreamer/tags), there is no DL-Streamer  image for OpenVINO 2022.3.  The latest tag is still based on 2022.2.

**Comment by brmarkus** [comment]
It looks like it's on it's way, see "https://github.com/openvinotoolkit/model_server/pull/1672".

**Comment by akwrobel** [comment]
Hi @changtimwu Intel® Deep Learning Streamer 2022.3, which aligns with the 2022.3 version of OpenVINO was released last week.  
https://github.com/dlstreamer/dlstreamer/releases/tag/2022.3-release
