### ISSUE TITLE
No output while running sample gvadetect pipeline

### ISSUE THREAD

**Issue by xiang-wuu** [dlstreamer/dlstreamer#342]
I installed dlstreamer and openvino as per the instructions mentioned in official doc [here](https://dlstreamer.github.io/get_started/install/install_guide_ubuntu.html#option-1-install-intel-dl-streamer-pipeline-framework-from-apt-repository), the installation seems to be okay but when i tried executing the very basic pipeline based on `gvadetect` for object detection, the output window render the input video but without any detection ROI's.
<h3>Steps to Reproduce</h3>
<h4>System specifications</h4>

**CPU:** 12th Gen Intel(R) Core(TM) i7-12650H
**O.S**: Ubuntu-20.04 LTS
**GPU**: NVIDIA GeForce RTX 3050 Laptop GPU
**Graphics**: NVIDIA Drivers Version- 515.86.01
**Openvino**: openvino_2022

intitialized the environment
```
source /opt/intel/openvino_2022/setupvars.sh
source /opt/intel/dlstreamer/setupvars.sh
```
Model required for basic detection pipeline,
```
export DETECTION_MODEL=${MODELS_PATH}/intel/person-vehicle-bike-detection-2004/FP32/person-vehicle-bike-detection-2004.xml
export DETECTION_MODEL_PROC=/opt/intel/dlstreamer/samples/gstreamer/model_proc/intel/person-vehicle-bike-detection-2004.json
```
input video file to be get inferred,
```
export VIDEO_EXAMPLE=~/path/to/video/FILENAME
```
below sample pipeline launched based on `gvadetect` and rendered with `video-sink=xvimagesink sync=false` elements,
```
gst-launch-1.0 \
filesrc location=${VIDEO_EXAMPLE} ! decodebin ! \
gvadetect model=${DETECTION_MODEL} model_proc=${DETECTION_MODEL_PROC} device=CPU ! queue ! \
gvawatermark ! videoconvert ! fpsdisplaysink video-sink=xvimagesink sync=false
```
but, below is output screenshot without any bounding boxes(ROI's) rendered on the output screen, also there are weird vertical strides which doesn't exist in the original input video but somehow appearing while rendering with dlstreamer pipeline, below is output after running the pipeline,
```
(gst-plugin-scanner:329094): GStreamer-WARNING **: 01:16:13.092: Failed to load plugin '/opt/intel/dlstreamer/lib/gstreamer-1.0/libgvametapublishkafka.so': librdkafka++.so.1: cannot open shared object file: No such file or directory

(gst-plugin-scanner:329094): GStreamer-WARNING **: 01:16:13.092: Failed to load plugin '/opt/intel/dlstreamer/lib/gstreamer-1.0/libgvametapublishmqtt.so': libpaho-mqtt3a.so.1: cannot open shared object file: No such file or directory

** (gst-plugin-scanner:329094): CRITICAL **: 01:16:13.265: gi.repository.Gst is no dict
DRM_IOCTL_I915_GEM_APERTURE failed: Invalid argument
Assuming 131072kB available aperture size.
May lead to reduced performance or incorrect rendering.
get chip id failed: -1 [22]
param: 4, val: 0
Setting pipeline to PAUSED ...
DRM_IOCTL_I915_GEM_APERTURE failed: Invalid argument
Assuming 131072kB available aperture size.
May lead to reduced performance or incorrect rendering.
get chip id failed: -1 [22]
param: 4, val: 0
Pipeline is PREROLLING ...
Got context from element 'vaapipostproc1': gst.vaapi.Display=context, gst.vaapi.Display=(GstVaapiDisplay)"\(GstVaapiDisplayGLX\)\ vaapidisplayglx0", gst.vaapi.Display.GObject=(GstObject)"\(GstVaapiDisplayGLX\)\ vaapidisplayglx0";
Redistribute latency...
Pipeline is PREROLLED ...
Setting pipeline to PLAYING ...
Redistribute latency...
New clock: GstSystemClock
Got EOS from element "pipeline0".
Execution ended after 0:02:50.576449027
Setting pipeline to NULL ...
Freeing pipeline ...
```
![Screenshot from 2023-01-15 01-15-55](https://user-images.githubusercontent.com/107029401/212493663-aa3b4427-19ce-40cd-8a14-7d2536b8eb0e.png)
by looking at the CPU utilization it looks like openvino inference is happening , but somehow there is no detection's showed on the render screen,
![Screenshot from 2023-01-15 01-18-05](https://user-images.githubusercontent.com/107029401/212493702-2a012cf8-eea4-46ab-beef-732d1824e50b.png)
Do i missing something here, as i followed all the steps and instructions as mentioned, i have gone through several community forums and other issues but no luck so far :disappointed:

**Comment by brmarkus** [comment]
Your SoC "12th Gen Intel(R) Core(TM) i7-12650H" contains an embedded, integrated Intel-GPU.
Your description also mentions an additional, but discrete GPU graphics card.
OpenVINO, DL-Streamer and the gstreamer-setup are optimized and validated using Intel-CPUs and Intel-GPUs (like zero-copy between GPU-video-decoding and GPU-inference).

Can you double-check which video-codec-plugins and which color-space-formats is used between the plugins (e.g. via the ENV variable `GST_DEBUG_DUMP_DOT_DIR` and using DOT to generate and visualize the pipeline graph)?

Can you try to spell-out the plugins explicitly instead of using `decodebin`, i.e. deciding which video-decoder-plugin to use and to do a color-space-format-conversion, when needed (e.g. the Intel-GPU-video-codec usually outputs NV12, but the inference expects RGB or BGR)?

It might just be an installation topic, library-/gstreamer-plugin-search-path order, getting confused between Intel-libraries and plugins and the corresponding NVIDIA ones.

**Comment by brmarkus** [comment]
Do you want to make use of the GPU of your SoC for video-decoding? Do you want to use your NVIDIA GPU for video-decoding? or do you want to use the CPU for video-decoding?

If the Intel-GPU of your Intel-SoC is not disabled (e.g. in BIOS) and OpenVINO and DL-Streamer is installed completely and you experiment directly in the OS natively (e.g. and not in a container or VM), then could you check the following, please?

`$ lspci | grep GPU`
Do you see the Intel-GPU and the NVIDIA gpu?

$ vainfo
Do you see the drivers (frontent libva and backend iHD) loaded, and the various codecs and profiles listed? Example (which I found in the Internet as an example):
```
	libva info: VA-API version 1.11.0
	libva info: User environment variable requested driver 'iHD'
	libva info: Trying to open /opt/intel/openvino/opt/intel/mediasdk/lib64//iHD_drv_video.so
	libva info: Found init function __vaDriverInit_1_11
	libva info: va_openDriver() returns 0
	vainfo: VA-API version: 1.11 (libva 2.6.0)
	vainfo: Driver version: Intel iHD driver for Intel(R) Gen Graphics - 21.1.3 (bec8e13)
	vainfo: Supported profile and entrypoints
		  VAProfileNone                   : VAEntrypointVideoProc
		  VAProfileNone                   : VAEntrypointStats
		  VAProfileMPEG2Simple            : VAEntrypointVLD
		  VAProfileMPEG2Simple            : VAEntrypointEncSlice
		  VAProfileMPEG2Main              : VAEntrypointVLD
		  VAProfileMPEG2Main              : VAEntrypointEncSlice
		  VAProfileH264Main               : VAEntrypointVLD
		  VAProfileH264Main               : VAEntrypointEncSlice
		  VAProfileH264Main               : VAEntrypointFEI
		  VAProfileH264Main               : VAEntrypointEncSliceLP
		  VAProfileH264High               : VAEntrypointVLD
		  VAProfileH264High               : VAEntrypointEncSlice
... ... ...
```
Then the drivers and dependencies where all installed and set-up properly as described in the documentation.

Assuming your video is encoded in h.264/AVC, then you can check your gstreamer installation:

`$ gst-inspect-1.0 | grep 264`
Do you see vaapi-based decoder and encoder plugins like this (for the Intel-GPU)?
```
	vaapi:  vaapih264dec: VA-API H264 decoder
	vaapi:  vaapih264enc: VA-API H264 encoder
```

Then you should be able to spell-out a simple pipeline like this:

(depending on your environment and how you are connected and whether your machines have displays connected or remote-screen-forwarding, requiring specific DISPLAY and/or XDG_RUNTIME_DIR environment variables)
`$ gst-launch-1.0 filesrc location=/my/path/my-video.h264 ! h264parse ! vaapih264dec ! xvimagesink`

With your more complex pipeline, you could try to set e.g. `export GST_DEBUG_DUMP_DOT_DIR=/tmp/` (plus installing e.g. `sudo apt install graphviz`) and executing your pipeline (and probably cancelling it after a few seconds).

You will see a few files being created under `/tmp/`, like `0.00.12.938764111-gst-launch.PLAYING_PAUSED.dot`.

Then convert the DOT-file into a picture like:
```
dot -Tpng 0.00.12.938764111-gst-launch.PLAYING_PAUSED.dot > gst-launch.PLAYING_PAUSED.png
```
Now you should be able to see your pipeline, the plugins and the input- and output-format.

You will see whether video-format-conversion will be required; you will see if gstreamer implicitely has added (wrongly assumed) conversions and might spell them out (like NV12 or YUV to RGB or BGR conversion).

Your used models might require slightly modified model-proc JSON files with special pre- and/or post-processing instructions.

**Comment by akwrobel** [comment]
Closed due to no response from the submitter.
