### ISSUE TITLE
Understanding VideoFrame in GVAPython

### ISSUE THREAD

**Issue by sbin149x** [dlstreamer/dlstreamer#343]
Hi, I'm trying to do custom preprocessing and post-processing due to unsupported model in DL Streamer and I'm not really familiar with this. For now the idea is to use gvainference + gvapython for the pipeline and call the processing part using gvapython module.
For the pre-processing part, I just want to understand why when I convert the VideoFrame object to numpy array, the mat.shape change to (329,426,1)? What I expect is (226,426,3). 
Originally the video resolution is 426x226. Output of the mediainfo: 
![image](https://user-images.githubusercontent.com/99851971/212830104-c5851833-3503-4c85-943f-613ef497bee5.png)

The code that I use:
![image](https://user-images.githubusercontent.com/99851971/212830674-16271184-7b59-4fb1-a312-93f07756b71f.png)

We already have the complete script for all pre and post processing part as initially the model was run using the script, but now need to implement it on Openvino and DL Streamer environment. 

Really appreciate the helps.
Thanks.

**Comment by akwrobel** [comment]
@sbin149x can you please share the pipeline you are using in this instance?
