### ISSUE TITLE
implement bytetrack into dl streamers 

### ISSUE THREAD

**Issue by boonpin75** [dlstreamer/dlstreamer#344]
hi all ., 
 I would like to know what is the possible way to implement the bytetrack into the dl streamer pipeline ? I have checking on the guide for gvapython and if there is possible to modify the code for the gvatrack directly .  appreciate if you can provide the answer if gvapython is a visible solution for implement the bytetrack . 

thanks !

**Comment by akwrobel** [comment]
Hi @boonpin75 you would need to implement a new custom GStreamer element to support bytetrack yourself.  This can be done using C/C++ or Python, but not GVAPython

**Comment by akwrobel** [comment]
@boonpin75 did you have any further concerns?

**Comment by boonpin75** [comment]
no,  you can close the issue
