### ISSUE TITLE
How to get output inference?

### ISSUE THREAD

**Issue by sbin149x** [dlstreamer/dlstreamer#345]
Hi, I have a pose_detection.xml model that is not from OpenVino Model Zoo and is not supported by DL Streamer. I want to know how I can get the output of the inference to get the keypoints and confidence scores of the pose detection using GVAPython. I did take a look at this sample code but am really unsure where to start https://github.com/dlstreamer/dlstreamer/blob/master/samples/gstreamer/gst_launch/gvapython/face_detection_and_classification/postproc_callbacks/ssd_object_detection.py. The idea is to to draw the poses on the image or video frame since we don't have model-proc.

**Comment by akwrobel** [comment]
This is not a supported case for DL Streamer, but you are looking at the right sample.  You can get the raw tensor data using frame.tensors() (line 23 from the sample you linked)

**Comment by akwrobel** [comment]
Closed, no response from submitter with and follow up questions.
