### ISSUE TITLE
'libgstvideoanalyticsmeta.so' from the APT repository

### ISSUE THREAD

**Issue by rimms** [dlstreamer/dlstreamer#347]
I trying to install DL Streamer from APT repository and build my application using DL Streamer.

```
. /etc/os-release \
  && curl -sSL https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB | apt-key add - \
  && curl -sSL https://repositories.intel.com/graphics/intel-graphics.key | apt-key add - \
  && echo "deb [arch=amd64] https://repositories.intel.com/graphics/ubuntu ${UBUNTU_CODENAME}-legacy main" > /etc/apt/sources.list.d/intel-graphics-legacy.list \
  && echo "deb https://apt.repos.intel.com/openvino/2022 ${UBUNTU_CODENAME} main" > /etc/apt/sources.list.d/intel-openvino-2022.list
apt update
apt install -y intel-dlstreamer-dev=2022.2.0.82
```

`/opt/intel/dlstreamer/lib/pkgconfig/dl-streamer.pc` distributed by `intel-dlstreamer-cpp=2022.2.0.82` is defined as follows:

```
prefix=${pcfiledir}/../..
exec_prefix=${prefix}/bin
libdir=${prefix}/lib
includedir=${prefix}/include
Name: Intel® Deep Learning Streamer (Intel® DL Streamer) Pipeline Framework
Description: Elements that enable Deep Learning inference and media analytics capabilities in the GStreamer framework
Version:1.7.0
Libs: -L${libdir} -lgstvideoanalyticsmeta
Cflags: -I${includedir
```

But `libgstvideoanalyticsmeta.so` is not distributed  by `intel-dlstreamer-bins=2022.2.0.82`.

How can I get `libgstvideoanalyticsmeta.so` from the APT repository?

---

I use Ubuntu 20.04 LTS.

**Comment by alekseyfa** [comment]
Since 2022.2 version the `libgstvideoanalyticsmeta.so` library is not distributed by intel-dlstreamer. If you want to use the C++ API, just include the dlstreamer headers in your cmake file.

```
target_include_directories(${TARGET_NAME}
PRIVATE
    ${DLSTREAMER_INCLUDE_DIRS}
)
```

The fact that `gstvideoanalyticsmeta` is listed in the `dl-streamer.pc` file is an error, thank you for noticing, we will fix that.

**Comment by rimms** [comment]
@alekseyfa 
I was able to build my application.

I closed this issue. Thank you.
