### ISSUE TITLE
Is there any guideline on writing Custom C++ Element / GStreamer Plugin ?

### ISSUE THREAD

**Issue by sbmalik** [dlstreamer/dlstreamer#350]
I have previously worked with NVIDIA Deepstream SDK and they have a basic plugin with make file and everything, on which a new developer can build on. I was wondering if there's a similar simple guideline (which can be helpful for building custom elements). I know the `src` directory contains many custom elements but as a beginner the (nested) cmake(s) is somehow complex for me. It would be great help if you can guide on this.

**Comment by pk1d3v** [comment]
Hi @sbmalik,

You can check official GStreamer documentation, e.g. [Plugin Writer's Guide](https://gstreamer.freedesktop.org/documentation/plugin-development/index.html#). And GStreamer for some boilerplate plugin code: [gst-template](https://gitlab.freedesktop.org/gstreamer/gst-template).

**Comment by sbmalik** [comment]
@pk1d3v Thank you. I'll surely check that. Moreover, it would be great if you can share resources on C++ Elements (Specific to OpenVINO), that can be used as both GStreamer/Non-GStreamer based apps?

**Comment by pk1d3v** [comment]
> @pk1d3v such as how to make/install the [rate_adjust](https://github.com/dlstreamer/dlstreamer/tree/master/src/cpu/rate_adjust) element as **gst** and **non-gst** separately ?

For GStreamer you don't need to actually install `rate_adjust` - just build the code, then update `GST_PLUGIN_PATH` environment variable or use [setup_env.sh](https://github.com/dlstreamer/dlstreamer/blob/master/scripts/setup_env.sh) script.
After that element should be ready to use. Verify with:
```sh
gst-inspect-1.0 rate_adjust
```

For non-gst usage you need to include [rate_adjust.h](https://github.com/dlstreamer/dlstreamer/blob/master/src/cpu/_plugin/dlstreamer/cpu/elements/rate_adjust.h), then create element via [ElementDesc::create](https://github.com/dlstreamer/dlstreamer/blob/master/include/dlstreamer/element.h#L92) and use it in your code. You can take a look how to create FFMPEG source element [here](https://github.com/dlstreamer/dlstreamer/blob/master/samples/ffmpeg_dpcpp/rgb_to_grayscale/rgb_to_grayscale.cpp#L38)

**Comment by sbmalik** [comment]
Understood, Thank you
