### ISSUE TITLE
DLStreamer preprocessing is padding with image with zeros instead of commonly used greyscale value 114

### ISSUE THREAD

**Issue by maitek** [dlstreamer/dlstreamer#351]
Most YOLO versions variants are padding the images with the a greyscale value 114.

https://github.com/ultralytics/yolov3/blob/21a56e51e57dc21035fbf30400664e605f4824be/utils/augmentations.py#L111
https://github.com/ultralytics/yolov5/blob/e4d836080f68dd14ae9becaa7b50c510ac1db54f/utils/augmentations.py#L111
https://github.com/WongKinYiu/yolov7/blob/2fdc7f14395f6532ad05fb3e6970150a6a83d290/utils/datasets.py#L984

In dlstreamer the image is padded with zeros.

https://github.com/dlstreamer/dlstreamer/blob/1f41fb0607831d3583f34a1b0d9e578ab3ff87a2/inference_backend/pre_proc/opencv_utils/opencv_utils.cpp#L251

114 comes from the mean 8-bit integer pixel value of ImageNet and makes sure that the size of the padding does not significantly change the mean value of the image. Padding with zeros during inference will affect the accuracy negatively if the model was trained with 114-grey padding which most YOLO versions are.  

I would suggest to change the default padding pixel value to from zero to 114 in the ResizeAspectRatio preprocessing step. Possibly the model_proc.json could have a parameter in order to change this value if needed. What do you think?

**Comment by akwrobel** [comment]
Hi @maitek we have reviewed this enhancement request, and this is not in our current roadmap, and we do not intend to add thsi functionality at this time.
