### ISSUE TITLE
WARNING: erroneous pipeline: no element "gvadetect"

### ISSUE THREAD

**Issue by fdordz** [dlstreamer/dlstreamer#352]
Hello

I have Ubuntu 20.04 with openvino_toolkit_ubuntu20_2022.3.0.9052.9752fafe8eb_x86_64 and Intel DL Streamer
I'm trying to do the tutorial https://dlstreamer.github.io/get_started/tutorial.html

When I proceeded to running a pipeline using the code I got the error below:

[root@2CY33Q3 (OptiPlex XE4 series) video]$source /opt/intel/openvino_2022/setupvars.sh
[setupvars.sh] OpenVINO environment initialized
[root@2CY33Q3 (OptiPlex XE4 series) video]$source /opt/intel/dlstreamer/setupvars.sh
[setupvars.sh] GStreamer 1.20 framework initialized
[setupvars.sh] GStreamer 1.20 plugins path initialized
[setupvars.sh] Intel(R) DL Streamer environment initialized
[root@2CY33Q3 (OptiPlex XE4 series) video]$sudo gst-launch-1.0  filesrc location=person-bicycle-car-detection.mp4 ! decodebin gvadetect model=person-vehicle-bike-detection-2004.xml model_proc=person-vehicle-bike-detection-2004.json  device=CPU ! queue ! gvawatermark ! videoconvert ! fpsdisplaysink video-sink=xvimagesink sync=false
**WARNING: erroneous pipeline: no element "gvadetect**

could you please help me?

Thanks

**Comment by brmarkus** [comment]
Do you need to use `sudo` when calling `gst-launch-1.0`?

It looks like there is a missing `!` between `decodebin` and `gvadetect`.

**Comment by fdordz** [comment]
That worked !!. I have different issue.

[root@2CY33Q3 (OptiPlex XE4 series) video]$gst-launch-1.0  filesrc location=person-bicycle-car-detection.mp4 ! decodebin ! gvadetect model=person-vehicle-bike-detection-2004.xml model_proc=person-vehicle-bike-detection-2004.json  device=CPU ! queue ! gvawatermark ! videoconvert ! fpsdisplaysink video-sink=xvimagesink sync=false
Setting pipeline to PAUSED ...
ERROR: from element /GstPipeline:pipeline0/GstFPSDisplaySink:fpsdisplaysink0/GstXvImageSink:xvimagesink0: Could not initialise Xv output
Additional debug info:
../sys/xvimage/xvimagesink.c(1806): gst_xv_image_sink_open (): /GstPipeline:pipeline0/GstFPSDisplaySink:fpsdisplaysink0/GstXvImageSink:xvimagesink0:
XVideo extension is not available
ERROR: pipeline doesn't want to preroll.
Failed to set pipeline to PAUSED.
Setting pipeline to NULL ...
Freeing pipeline ...

**Comment by JSVJ** [comment]
@fdordz , Is DLStreamer working with Open VINO 2022.3 ? Could you please tell me how did you install it? I am getting troubles in making these two work. 

I opened this issue, https://github.com/dlstreamer/dlstreamer/issues/353

**Comment by brmarkus** [comment]
> That worked !!. I have different issue.
> 
> [root@2CY33Q3 (OptiPlex XE4 series) video]$gst-launch-1.0 filesrc location=person-bicycle-car-detection.mp4 ! decodebin ! gvadetect model=person-vehicle-bike-detection-2004.xml model_proc=person-vehicle-bike-detection-2004.json device=CPU ! queue ! gvawatermark ! videoconvert ! fpsdisplaysink video-sink=xvimagesink sync=false
> Setting pipeline to PAUSED ...
> ERROR: from element /GstPipeline:pipeline0/GstFPSDisplaySink:fpsdisplaysink0/GstXvImageSink:xvimagesink0: Could not initialise Xv output
> Additional debug info:
> ../sys/xvimage/xvimagesink.c(1806): gst_xv_image_sink_open (): /GstPipeline:pipeline0/GstFPSDisplaySink:fpsdisplaysink0/GstXvImageSink:xvimagesink0:
> XVideo extension is not available
> ERROR: pipeline doesn't want to preroll.
> Failed to set pipeline to PAUSED.
> Setting pipeline to NULL ...
> Freeing pipeline ...

You do have a monitor connected to your machine (and you do have a GPU)?
Do you use your machine "directly" or "remotely"?

You do use an X/X11-based window-manager (and not e.g. based on Wayland)?
Then you might just set the `DISPLAY` env variable, to e.g. `export DISPLAY=:0` (or DISPLAY=:1 etc.), depending on how many monitors you have connected or whether you use display-forwarding?

**Comment by brmarkus** [comment]
Will it work when using `autovideosink` instead of `xvimagesink`?

**Comment by akwrobel** [comment]
Hi @fdordz can you please try this with the recent 2022.3 release which is aligned with the OpenVINO 2022.3?

**Comment by akwrobel** [comment]
@fdordz have you been able to try with the 2022.3 release?
