### ISSUE TITLE
OpenVINO 2022.3 support 

### ISSUE THREAD

**Issue by aahouzi-intel** [dlstreamer/dlstreamer#355]
Hi! I'm working with DL streamer, and I have a model in which OV had a bug, so the devs from OV fixed the bug and included it in 2022.3 version of OV, when are you gonna add support for the latest version? 

For now, I cannot work without this specific version. Or do u have any workaround to make it work?

**Comment by akwrobel** [comment]
Hi @aahouzi-intel We are rapidly approaching our next release which will align Intel® DL Streamer with the 2022.3 OV version.
