### ISSUE TITLE
Is gstreamer1.0-plugin-ugly installed by default? If yes, then how to uninstall it

### ISSUE THREAD

**Issue by sbmalik** [dlstreamer/dlstreamer#356]
I am working with rtsp cameras and some cameras are not working, but when I uninstalled the `gstreamer1.0-plugin-ugly` the playbin is able to access the rtsp stream. I found [solution from here](https://forums.developer.nvidia.com/t/gst-launch-1-0-rtspsrc/227062/2)

`apt remove --purge gstreamer1.0-plugins-ugly -y`

When I tried doing the same in dlstreamer container **intel/dlstreamer:2022.2.0-ubuntu20-gpu419.40-devel**, it says that plugins-ugly are not installed. But when I run this command the playbin is able capture the stream and works well.

`GST_PLUGIN_PATH=/usr/lib/x86_64-linux-gnu/gstreamer-1.0:/opt/intel/dlstreamer/lib/gstreamer-1.0 gst-launch-1.0 playbin uri='rtsp://username:pass@XX.XX.XX.XX/cam/realmonitor?channel=1&subtype=0'`

I noticed that including the following path is causing the problem
`/opt/intel/dlstreamer/gstreamer/lib/gstreamer-1.0`

I am afraid if I exclude these libraries it will have an effect on **dlstreamer**. So Can you tell a way to remove the specific component of **gstreamer1.0-plugin-ugly**

**Comment by sbmalik** [comment]
Thanks @akwrobel, I'll test and let you know

**Comment by sbmalik** [comment]
@akwrobel 
`GST_PLUGIN_PATH=/usr/lib/x86_64-linux-gnu/gstreamer-1.0 gst-launch-1.0 playbin uri='rtsp://uname:pass@XX.XX.XX.XX'` is working but `gst-launch-1.0 playbin uri='rtsp://uname:pass@XX.XX.XX.XX'` is not working. I have not installed the gstreamer-plugins-ugly. I think it's the same problem. Can you please share the details how to remove the gstreamer1.0-plugin-ugly related plugins (`xxx.so`) from dlstreamer ?

**Comment by sbmalik** [comment]
@leopck , No the issue is related to plugin-ugly adding some headers in rtsp authentication, some rtsps are working but I think rtsp cameras with outdated firmware (maybe causing issue). I tried the same within the deepstream which works after removing the plugin-ugly.

**Comment by leopck** [comment]
@sbmalik is this issue resolved on the latest plugin-ugly?

**Comment by leopck** [comment]
if you are willing to take the risk, and we do not test for this configuration, you can remove the plugin ugly using `apt remove intel-dlstreamer-gst-plugins-ugly` that is the package name from our side. But can't guarantee if it breaks anything, you might want to give that a try.

**Comment by sbmalik** [comment]
Yes, I tried with updated plugins-ugly but the issue is still there. However thank you @leopck for telling me the package name, the issue is resolved after removing `intel-dlstreamer-gst-plugins-ugly` for my cameras.
