### ISSUE TITLE
Caught SIGSEGV issue running dlstreamer:2022.3.0-ubuntu22-gpu555 with latest openVINO 

### ISSUE THREAD

**Issue by antoniomtz** [dlstreamer/dlstreamer#358]
Hello,

I've been trying to run dlstreamer pipelines using the latest docker image 2022.3.0-ubuntu22-gpu555 and latest openVINO from master branch.

What I do, I compile openVINO from scratch using latest master branch inside the 2022.3.0-ubuntu22-gpu555 image.
I tested my new image running sample python apps from the openVINO model zoo and they run just fine showing openVINO build 2023.

However, when I run a dlstreamer pipeline, I get:

**$ gst-launch-1.0 $inputsrc ! decodebin ! gvadetect model=models/face-detection/face-detection-0200.xml device=CPU ! gvawatermark ! videoconvert ! gvafpscounter ! autovideosink sync=false**

```
Caught SIGSEGV
exec gdb failed: No such file or directory
Spinning.  Please run 'gdb gst-launch-1.0 14' to continue debugging, Ctrl-C to quit, or Ctrl-\ to dump core.
```
Are there some known issues using the latest openVINO from master branch and DLstreamer?

**Comment by akwrobel** [comment]
@antoniomtz can you please add more details on your use case and need? 
- Are you using the latest pre-release or the tip of main for OpenVINO?
- Why do you need this specific version of OpenVINO

The Intel® Deep Learning Streamer 2022.3 is aligned with support for specific versions of OpenVINO in this case OpenVINO 2022.3 Please see the [release notes for 2022.3] (https://github.com/dlstreamer/dlstreamer/releases/tag/2022.3-release) which call out the supported version.

**Comment by antoniomtz** [comment]
Yes, using the tip of main from openVINO with 2022.3.0-ubuntu22-gpu555.
it seems that dlstreamer 2022.3.0 isn't compatible with the 2023 openVINO yet.

**Comment by pk1d3v** [comment]
Hi @antoniomtz,

The Intel® Deep Learning Streamer 2022.3 is compiled against OpenVINO 2022.3 as @akwrobel mentioned. If you are using different version of OpenVINO you need to build DL Streamer from source.

**Comment by antoniomtz** [comment]
@pk1d3v I was able to recompile dlstreamer against openVINO from a commit back in February. 
It looks like the tip of main in openVINO has some changes that conflicts with dlstreamer.

For now, I was able to test what I needed. 

Thanks.
