### ISSUE TITLE
CMake Error at /usr/local/lib/cmake/opencv4/OpenCVModules.cmake:37 (message):   Some (but not all) targets in this export set were already defined.

### ISSUE THREAD

**Issue by KiwiHana** [dlstreamer/dlstreamer#360]
Install dlstreamer cmake ERROR refer to :https://dlstreamer.github.io/get_started/install/install_guide_ubuntu.html#option-3-compile-intel-dl-streamer-pipeline-framework-from-sources-on-host-system

$ ls /usr/local/lib
cmake                       libopencv_core.so.4.7.0        libopencv_gapi.a              libopencv_imgproc.so          libopencv_photo.so.407        libopencv_video.so.4.7.0
libavcodec.a                libopencv_dnn.a                libopencv_gapi.so             libopencv_imgproc.so.407      libopencv_photo.so.4.7.0      libswresample.a
libavdevice.a               libopencv_dnn.so               libopencv_gapi.so.407         libopencv_imgproc.so.4.7.0    libopencv_stitching.a         libswscale.a
libavfilter.a               libopencv_dnn.so.407           libopencv_gapi.so.4.7.0       libopencv_ml.a                libopencv_stitching.so        libvpl.so
libavformat.a               libopencv_dnn.so.4.7.0         libopencv_highgui.a           libopencv_ml.so               libopencv_stitching.so.407    libvpl.so.2
libavutil.a                 libopencv_features2d.a         libopencv_highgui.so          libopencv_ml.so.407           libopencv_stitching.so.4.7.0  libvpl.so.2.7
libopencv_calib3d.a         libopencv_features2d.so        libopencv_highgui.so.407      libopencv_ml.so.4.7.0         libopencv_video.a             libvpl.so.2.8
libopencv_calib3d.so        libopencv_features2d.so.407    libopencv_highgui.so.4.7.0    libopencv_objdetect.a         libopencv_videoio.a           opencv4
libopencv_calib3d.so.407    libopencv_features2d.so.4.7.0  libopencv_imgcodecs.a         libopencv_objdetect.so        libopencv_videoio.so          pkgconfig
libopencv_calib3d.so.4.7.0  libopencv_flann.a              libopencv_imgcodecs.so        libopencv_objdetect.so.407    libopencv_videoio.so.407      python3.10
libopencv_core.a            libopencv_flann.so             libopencv_imgcodecs.so.407    libopencv_objdetect.so.4.7.0  libopencv_videoio.so.4.7.0    vpl
libopencv_core.so           libopencv_flann.so.407         libopencv_imgcodecs.so.4.7.0  libopencv_photo.a             libopencv_video.so
libopencv_core.so.407       libopencv_flann.so.4.7.0       libopencv_imgproc.a           libopencv_photo.so            libopencv_video.so.407

a380@a380:~/intel/dlstreamer_gst$ source /opt/intel/openvino_2022.3.0/setupvars.sh
[setupvars.sh] OpenVINO environment initialized
a380@a380:~/intel/dlstreamer_gst$ source /opt/intel/dlstreamer/gstreamer/setupvars.sh
[setupvars.sh] GStreamer 1.20 framework initialized
[setupvars.sh] GStreamer 1.20 plugins path initialized
a380@a380:~/intel/dlstreamer_gst$ mkdir ~/intel/dlstreamer_gst/build
a380@a380:~/intel/dlstreamer_gst$ cd ~/intel/dlstreamer_gst/build
a380@a380:~/intel/dlstreamer_gst/build$ cmake ..
-- The C compiler identification is GNU 11.3.0
-- The CXX compiler identification is GNU 11.3.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- CMAKE_BUILD_TYPE is undefined. Set default build type Release.
INFOGIT_INFO is undefined. Set default value 0.
ENABLE_PAHO_INSTALLATION=OFF
ENABLE_RDKAFKA_INSTALLATION=OFF
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.2")
-- Checking for module 'gstreamer-1.0>=1.16'
--   Found gstreamer-1.0, version 1.20.3
-- Checking for one of the modules 'libavformat;libavcodec;libswscale;libavutil'
-- Checking for modules 'libavformat;libavcodec;libswscale;libavutil'
--   Found libavformat, version 60.3.100
--   Found libavcodec, version 60.3.100
--   Found libswscale, version 7.1.100
--   Found libavutil, version 58.2.100
-- Checking for module 'gstreamer-video-1.0>=1.16'
--   Found gstreamer-video-1.0, version 1.20.3
-- Checking for module 'gstreamer-allocators-1.0'
--   Found gstreamer-allocators-1.0, version 1.20.3
-- Checking for module 'glib-2.0'
--   Found glib-2.0, version 2.72.4
Intel® oneAPI DPC++ Compiler not found, skipping dlstreamer_gst_sycl library
-- Looking for CL_VERSION_3_0
-- Looking for CL_VERSION_3_0 - found
-- Found OpenCL: /usr/lib/x86_64-linux-gnu/libOpenCL.so (found version "3.0")
-- Checking for one of the modules 'va;libva'
-- Found OpenCV: /usr/local (found version "4.7.0") found components: core imgproc
-- Found OpenCV: /usr/local (found version "4.7.0") found components: opencv_calib3d opencv_core opencv_dnn opencv_features2d opencv_flann opencv_gapi opencv_highgui opencv_imgcodecs opencv_imgproc opencv_ml opencv_objdetect opencv_photo opencv_stitching opencv_video opencv_videoio
Intel® oneAPI DPC++ Compiler not found, skipping  library
-- Found OpenCV: /usr/local (found version "4.7.0") found components: core imgproc
-- Checking for module 'gstreamer-audio-1.0>=1.16'
--   Found gstreamer-audio-1.0, version 1.20.3
-- Checking for module 'pygobject-3.0'
--   Found pygobject-3.0, version 3.42.1
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.10.so (found suitable version "3.10.6", minimum required is "3.4")
-- Checking for one of the modules 'va-drm;libva-drm'
-- Found OpenCV: /usr/local (found version "4.7.0") found components: core imgproc imgcodecs
-- [download 0% complete]
-- [download 1% complete]
-- [download 2% complete]
-- [download 3% complete]
-- [download 4% complete]
-- [download 5% complete]
-- [download 6% complete]
-- [download 7% complete]
-- [download 8% complete]
-- [download 10% complete]
-- [download 12% complete]
-- [download 14% complete]
-- [download 16% complete]
-- [download 18% complete]
-- [download 20% complete]
-- [download 22% complete]
-- [download 24% complete]
-- [download 26% complete]
-- [download 28% complete]
-- [download 30% complete]
-- [download 32% complete]
-- [download 34% complete]
-- [download 36% complete]
-- [download 38% complete]
-- [download 40% complete]
-- [download 42% complete]
-- [download 46% complete]
-- [download 48% complete]
-- [download 50% complete]
-- [download 52% complete]
-- [download 55% complete]
-- [download 57% complete]
-- [download 59% complete]
-- [download 61% complete]
-- [download 63% complete]
-- [download 65% complete]
-- [download 67% complete]
-- [download 69% complete]
-- [download 71% complete]
-- [download 73% complete]
-- [download 75% complete]
-- [download 77% complete]
-- [download 79% complete]
-- [download 81% complete]
-- [download 83% complete]
-- [download 85% complete]
-- [download 87% complete]
-- [download 89% complete]
-- [download 91% complete]
-- [download 93% complete]
-- [download 95% complete]
-- [download 97% complete]
-- [download 99% complete]
-- [download 100% complete]
-- Download of JSON header is successful
-- Download of JSON validator is successful
-- Build spdlog: 1.10.0
-- Build type: Release
CMake Error at /usr/local/lib/cmake/opencv4/OpenCVModules.cmake:37 (message):
  Some (but not all) targets in this export set were already defined.

  Targets Defined: ittnotify

  Targets not yet defined:
  libwebp;libopenjp2;IlmImf;ippiw;libprotobuf;quirc;ade;opencv_core;opencv_flann;opencv_imgproc;opencv_ml;opencv_photo;opencv_dnn;opencv_features2d;opencv_imgcodecs;ocv.3rdparty.v4l;ocv.3rdparty.ffmpeg;ocv.3rdparty.ffmpeg.builtin_deps;ocv.3rdparty.obsensor;opencv_videoio;opencv_calib3d;ocv.3rdparty.gtk2;ocv.3rdparty.gthread;opencv_highgui;opencv_objdetect;opencv_stitching;opencv_video;opencv_gapi

Call Stack (most recent call first):
  /usr/local/lib/cmake/opencv4/OpenCVConfig.cmake:133 (include)
  samples/gstreamer/cpp/draw_face_attributes/CMakeLists.txt:11 (find_package)

-- Configuring incomplete, errors occurred!

**Comment by akwrobel** [comment]
Hi @KiwiHana,
Can you please share your setup and configuration, as well as what version of DL Streamer you are using, if you are using the docker image, and if you are altering any components?  

This error appears to originate from OpenCV, so please let us know any changes or updates you have made to this component in particular.

**Comment by KiwiHana** [comment]
@akwrobel 
Hello Andrew,
I try install dlstreamer by docker on Ubuntu22.04, but failed. My commands as following:
sudo apt install docker.io
$ sudo docker run -it --device /dev/dri/render128 --user root --rm intel/dlstreamer:devel /bin/bash
Unable to find image 'intel/dlstreamer:devel' locally
docker: Error response from daemon: Get "https://registry-1.docker.io/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers).
See 'docker run --help'

$ sudo docker pull intel/dlstreamer:2022.3.0-ubuntu22-gpu555-dpcpp
Error response from daemon: Get "https://registry-1.docker.io/v2/": dial tcp 52.1.184.176:443: i/o timeout

$ sudo docker images
REPOSITORY   TAG       IMAGE ID   CREATED   SIZE

$ sudo docker version
Client:
 Version:           20.10.21
 API version:       1.41
 Go version:        go1.18.1
 Git commit:        20.10.21-0ubuntu1~22.04.3
 Built:             Thu Apr 27 05:57:17 2023
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.21
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.1
  Git commit:       20.10.21-0ubuntu1~22.04.3
  Built:            Thu Apr 27 05:37:25 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.12-0ubuntu1~22.04.1
  GitCommit:
 runc:
  Version:          1.1.4-0ubuntu1~22.04.3
  GitCommit:
 docker-init:
  Version:          0.19.0
  GitCommit:

**Comment by KiwiHana** [comment]
solved. need to add proxy.
