### ISSUE TITLE
Decode and inference images of a document, but get error result. miss frame

### ISSUE THREAD

**Issue by KiwiHana** [dlstreamer/dlstreamer#361]
/root/data/202208/ have 250 JPG files named IMG_0000.png, IMG_0001.png, etc.
Decode them is right result. 35.06*7.445418880~=250 images
FpsCounter(overall 7.45sec): total=35.06 fps, number-streams=1, per-stream=35.06 fps
Execution ended after 0:00:07.445418880

But decode and then inference by detect model will get wrong results. 0.41 * 105.38 = 43 images
Execution ended after 0:01:45.356866255
FpsCounter(overall 105.38sec): total=0.41 fps, number-streams=1, per-stream=0.41 fps

I install dlstreamer by docker on Ubuntu22.04 Arc A380. GPU means A380.
$sudo docker run -it --device /dev/dri/renderD128 --user root --privileged -v /home/your/path/:/root/data --rm intel/dlstreamer:latest /bin/bash

 gst-launch-1.0 multifilesrc location="/root/data/202208/IMG_%04d.JPG" index=0 caps="image/jpeg,framerate=\(fraction\)30/1" ! decodebin ! gvafpscounter ! fakesink
Setting pipeline to PAUSED ...
Pipeline is PREROLLING ...
Pipeline is PREROLLED ...
Setting pipeline to PLAYING ...
Redistribute latency...
New clock: GstSystemClock
FpsCounter(last 1.01sec): total=35.72 fps, number-streams=1, per-stream=35.72 fps
FpsCounter(average 1.01sec): total=35.72 fps, number-streams=1, per-stream=35.72 fps
FpsCounter(last 1.02sec): total=35.31 fps, number-streams=1, per-stream=35.31 fps
FpsCounter(average 2.03sec): total=35.52 fps, number-streams=1, per-stream=35.52 fps
FpsCounter(last 1.03sec): total=35.97 fps, number-streams=1, per-stream=35.97 fps
FpsCounter(average 3.06sec): total=35.67 fps, number-streams=1, per-stream=35.67 fps
FpsCounter(last 1.00sec): total=33.83 fps, number-streams=1, per-stream=33.83 fps
FpsCounter(average 4.06sec): total=35.21 fps, number-streams=1, per-stream=35.21 fps
FpsCounter(last 1.01sec): total=38.54 fps, number-streams=1, per-stream=38.54 fps
FpsCounter(average 5.07sec): total=35.88 fps, number-streams=1, per-stream=35.88 fps
FpsCounter(last 1.01sec): total=33.57 fps, number-streams=1, per-stream=33.57 fps
FpsCounter(average 6.09sec): total=35.49 fps, number-streams=1, per-stream=35.49 fps
FpsCounter(last 1.00sec): total=32.94 fps, number-streams=1, per-stream=32.94 fps
FpsCounter(average 7.09sec): total=35.13 fps, number-streams=1, per-stream=35.13 fps
FpsCounter(last 0.36sec): total=33.54 fps, number-streams=1, per-stream=33.54 fps
FpsCounter(overall 7.45sec): total=35.06 fps, number-streams=1, per-stream=35.06 fps
Got EOS from element "pipeline0".
Execution ended after 0:00:07.445418880
Setting pipeline to NULL ...
Freeing pipeline ...

gst-launch-1.0 multifilesrc location="/root/data/ouyang/202208/IMG_%04d.JPG" index=0 caps="image/jpeg,framerate=\(fraction\)30/1" ! decodebin ! gvadetect model=/root/data/open_model_zoo/demos/face_recognition_demo/python/pipeline-zoo-models/storage/yolo-v4-tf_INT8/yolo-v4-tf_INT8.xml model_proc=/root/data/open_model_zoo/demos/face_recognition_demo/python/pipeline-zoo-models/storage/yolo-v4-tf_INT8/yolo-v4-tf_INT8.json inference-interval=1 device=GPU batch-size=1 ! queue ! gvafpscounter ! fakesink
Setting pipeline to PAUSED ...
Pipeline is PREROLLING ...
Pipeline is PREROLLED ...
Setting pipeline to PLAYING ...
Redistribute latency...
New clock: GstSystemClock
FpsCounter(last 5.19sec): total=0.96 fps, number-streams=1, per-stream=0.96 fps
FpsCounter(average 5.19sec): total=0.96 fps, number-streams=1, per-stream=0.96 fps
FpsCounter(last 5.16sec): total=0.19 fps, number-streams=1, per-stream=0.19 fps
FpsCounter(average 10.35sec): total=0.58 fps, number-streams=1, per-stream=0.58 fps
FpsCounter(last 5.19sec): total=0.19 fps, number-streams=1, per-stream=0.19 fps
FpsCounter(average 15.55sec): total=0.45 fps, number-streams=1, per-stream=0.45 fps
FpsCounter(last 5.01sec): total=0.20 fps, number-streams=1, per-stream=0.20 fps
FpsCounter(average 20.56sec): total=0.39 fps, number-streams=1, per-stream=0.39 fps
FpsCounter(last 5.23sec): total=0.19 fps, number-streams=1, per-stream=0.19 fps
FpsCounter(average 25.79sec): total=0.35 fps, number-streams=1, per-stream=0.35 fps
FpsCounter(last 5.64sec): total=0.18 fps, number-streams=1, per-stream=0.18 fps
FpsCounter(average 31.43sec): total=0.32 fps, number-streams=1, per-stream=0.32 fps
FpsCounter(last 5.54sec): total=0.54 fps, number-streams=1, per-stream=0.54 fps
FpsCounter(average 36.97sec): total=0.35 fps, number-streams=1, per-stream=0.35 fps
FpsCounter(last 5.74sec): total=0.17 fps, number-streams=1, per-stream=0.17 fps
FpsCounter(average 42.70sec): total=0.33 fps, number-streams=1, per-stream=0.33 fps
FpsCounter(last 5.91sec): total=1.35 fps, number-streams=1, per-stream=1.35 fps
FpsCounter(average 48.61sec): total=0.45 fps, number-streams=1, per-stream=0.45 fps
FpsCounter(last 5.78sec): total=0.35 fps, number-streams=1, per-stream=0.35 fps
FpsCounter(average 54.39sec): total=0.44 fps, number-streams=1, per-stream=0.44 fps
FpsCounter(last 5.56sec): total=0.72 fps, number-streams=1, per-stream=0.72 fps
FpsCounter(average 59.95sec): total=0.47 fps, number-streams=1, per-stream=0.47 fps
FpsCounter(last 5.81sec): total=0.17 fps, number-streams=1, per-stream=0.17 fps
FpsCounter(average 65.76sec): total=0.44 fps, number-streams=1, per-stream=0.44 fps
FpsCounter(last 5.60sec): total=0.71 fps, number-streams=1, per-stream=0.71 fps
FpsCounter(average 71.36sec): total=0.46 fps, number-streams=1, per-stream=0.46 fps
FpsCounter(last 5.58sec): total=0.18 fps, number-streams=1, per-stream=0.18 fps
FpsCounter(average 76.94sec): total=0.44 fps, number-streams=1, per-stream=0.44 fps
FpsCounter(last 5.81sec): total=0.69 fps, number-streams=1, per-stream=0.69 fps
FpsCounter(average 82.75sec): total=0.46 fps, number-streams=1, per-stream=0.46 fps
FpsCounter(last 5.53sec): total=0.18 fps, number-streams=1, per-stream=0.18 fps
FpsCounter(average 88.28sec): total=0.44 fps, number-streams=1, per-stream=0.44 fps
FpsCounter(last 5.81sec): total=0.52 fps, number-streams=1, per-stream=0.52 fps
FpsCounter(average 94.09sec): total=0.45 fps, number-streams=1, per-stream=0.45 fps
FpsCounter(last 5.71sec): total=0.18 fps, number-streams=1, per-stream=0.18 fps
FpsCounter(average 99.80sec): total=0.43 fps, number-streams=1, per-stream=0.43 fps
ERROR: from element /GstPipeline:pipeline0/GstMultiFileSrc:multifilesrc0: Internal data stream error.
Additional debug info:
../libs/gst/base/gstbasesrc.c(3127): gst_base_src_loop (): /GstPipeline:pipeline0/GstMultiFileSrc:multifilesrc0:
streaming stopped, reason not-negotiated (-4)
Execution ended after 0:01:45.356866255
Setting pipeline to NULL ...
Freeing pipeline ...
FpsCounter(last 5.58sec): total=0.00 fps, number-streams=1, per-stream=0.00 fps
FpsCounter(overall 105.38sec): total=0.41 fps, number-streams=1, per-stream=0.41 fps

**Comment by brmarkus** [comment]
Can you do a consistency-check of using another (face-)detection model, like "https://github.com/openvinotoolkit/open_model_zoo/tree/master/models/intel/face-detection-adas-0001"?

Can you try running it on CPU instead of CPU?

Can you try using FP16 instead of the INT8-quantized model?

Can you try using higher values for `batch-size` and add values for `nireq` in order to make parallel inference requests?

Experimenting with using `no-block` to see the effect on back-pressure due to inference.

Have you checked if JPEG-decoding happens on the CPU (SW-decoding) or in the GPU (HW-accelerated decoding in GPU via vaapi?) - you might want to spell-out plugins (like `vaapijpegdec`) instead of using `decodebin`? For decoding in the GPU (and using GPU-zero-copy for the decoded frames) you might benefit from using `pre-process-backend`.

**Comment by KiwiHana** [comment]
@brmarkus @
Hi Markus,

total 250 images in /root/data/202208/IMG_%04d.JPG

(1) Both FP16 & INT8 model are OK.
（2）vaapi decode will miss over 2/3 images. CPU decode get the right images number.

# gst-launch-1.0 multifilesrc location="/root/data/202208/IMG_%04d.JPG" index=0 caps="image/jpeg,framerate=(fraction)30/1" ! jpegdec ! gvafpscounter ! fakesink
FpsCounter(overall 7.31sec): total=35.72 fps, number-streams=1, per-stream=35.72 fps

# gst-launch-1.0 multifilesrc location="/root/data/202208/IMG_%04d.JPG" index=0 caps="image/jpeg,framerate=(fraction)30/1" ! vaapijpegdec ! gvafpscounter ! fakesink
FpsCounter(overall 0.51sec): total=142.09 fps, number-streams=1, per-stream=142.09 fps

(3) vaapi decode and inference by FP16/INT8 model also miss images.

# gst-launch-1.0 multifilesrc location="/root/data/202208/IMG_%04d.JPG" index=0 caps="image/jpeg,framerate=(fraction)30/1" ! vaapijpegdec ! capsfilter caps="video/x-raw(memory:VASurface)" ! gvadetect model=/root/data/public/yolo-v4-tf/FP16/yolo-v4-tf.xml model_proc=/root/data/open_model_zoo/yolo-v4-tf.json inference-interval=1 device=GPU batch-size=16 pre-process-backend=vaapi-surface-sharing ! queue ! gvafpscounter ! fakesink

FpsCounter(overall 211.81sec): total=0.33 fps, number-streams=1, per-stream=0.33 fps

# gst-launch-1.0 multifilesrc location="/root/data/202208/IMG_%04d.JPG" index=0 caps="image/jpeg,framerate=(fraction)30/1" ! vaapijpegdec ! capsfilter caps="video/x-raw(memory:VASurface)" ! gvadetect model=/root/pipeline-zoo-models/storage/yolo-v4-tf_INT8/yolo-v4-tf_INT8.xml  model_proc=/root/pipeline-zoo-models/storage/yolo-v4-tf_INT8/yolo-v4-tf_INT8.json inference-interval=1 device=GPU batch-size=16 pre-process-backend=vaapi-surface-sharing ! queue ! gvafpscounter ! fakesink

FpsCounter(overall 233.51sec): total=0.30 fps, number-streams=1, per-stream=0.30 fps


(4) CPU decode and inference by FP16 model also miss 220/250 images. 
# gst-launch-1.0 multifilesrc location="/root/data/202208/IMG_%04d.JPG" index=0 caps="image/jpeg,framerate=(fraction)30/1" ! jpegdec ! gvadetect model=/root/data/public/yolo-v4-tf/FP16/yolo-v4-tf.xml model_proc=/root/pipeline-zoo-models/storage/yolo-v4-tf_INT8/yolo-v4-tf_INT8.json inference-interval=1 device=CPU batch-size=1 ! queue ! gvafpscounter ! fakesink

ERROR: from element /GstPipeline:pipeline0/GstMultiFileSrc:multifilesrc0: Internal data stream error.
Additional debug info:
../libs/gst/base/gstbasesrc.c(3127): gst_base_src_loop (): /GstPipeline:pipeline0/GstMultiFileSrc:multifilesrc0:
streaming stopped, reason not-negotiated (-4)
Execution ended after 0:00:32.328109084
Setting pipeline to NULL ...
Freeing pipeline ...
FpsCounter(last 1.69sec): total=0.00 fps, number-streams=1, per-stream=0.00 fps
FpsCounter(overall 33.00sec): total=1.30 fps, number-streams=1, per-stream=1.30 fps

(5) multi batch size with nireq on CPU is ERROR.
# gst-launch-1.0 multifilesrc location="/root/data/202208/IMG_%04d.JPG" index=0 caps="image/jpeg,framerate=(fraction)30/1" ! jpegdec ! gvadetect model=/root/data/public/yolo-v4-tf/FP16/yolo-v4-tf.xml model_proc=/root/data/pipeline-zoo-models/storage/yolo-v4-tf_INT8/yolo-v4-tf_INT8.json inference-interval=1 device=CPU batch-size=2 nireq=2 ! queue ! gvafpscounter ! fakesink
Setting pipeline to PAUSED ...
Pipeline is PREROLLING ...
ERROR: from element /GstPipeline:pipeline0/GstGvaDetect:gvadetect0: base_inference plugin initialization failed
Additional debug info:
/root/gst-video-analytics/gst/inference_elements/base/inference_singleton.cpp(173): acquire_inference_instance (): /GstPipeline:pipeline0/GstGvaDetect:gvadetect0:

Failed to construct OpenVINOImageInference
        Failed to create preprocessor of
                Inference Engine preprocessing with batching is not supported
ERROR: pipeline doesn't want to preroll.
ERROR: from element /GstPipeline:pipeline0/GstGvaDetect:gvadetect0: base_inference based element initialization has been failed.
Additional debug info:
/root/gst-video-analytics/gst/inference_elements/base/gva_base_inference.cpp(796): gva_base_inference_set_caps (): /GstPipeline:pipeline0/GstGvaDetect:gvadetect0:

inference is NULL.
ERROR: pipeline doesn't want to preroll.
Setting pipeline to NULL ...
ERROR: from element /GstPipeline:pipeline0/GstGvaDetect:gvadetect0: base_inference plugin initialization failed
Additional debug info:
/root/gst-video-analytics/gst/inference_elements/base/inference_singleton.cpp(173): acquire_inference_instance (): /GstPipeline:pipeline0/GstGvaDetect:gvadetect0:

Failed to construct OpenVINOImageInference
        Failed to create preprocessor of
                Inference Engine preprocessing with batching is not supported
ERROR: pipeline doesn't want to preroll.
ERROR: from element /GstPipeline:pipeline0/GstGvaDetect:gvadetect0: base_inference based element initialization has been failed.
Additional debug info:
/root/gst-video-analytics/gst/inference_elements/base/gva_base_inference.cpp(796): gva_base_inference_set_caps (): /GstPipeline:pipeline0/GstGvaDetect:gvadetect0:

inference is NULL.
ERROR: pipeline doesn't want to preroll.
ERROR: from element /GstPipeline:pipeline0/GstGvaDetect:gvadetect0: base_inference failed on stop
Additional debug info:
/root/gst-video-analytics/gst/inference_elements/base/gva_base_inference.cpp(897): gva_base_inference_stop (): /GstPipeline:pipeline0/GstGvaDetect:gvadetect0:
empty inference instance
ERROR: pipeline doesn't want to preroll.
Freeing pipeline ...

(6) use mp4 instead of images, the frame is right when use vaapi decode and inference by GPU.
backgroud_1080.mp4 is 25s * 60 frame = 1500 frame.

#gst-launch-1.0 filesrc location=/root/backgroud_1080.mp4 ! decodebin ! capsfilter caps="video/x-raw(memory:VASurface)" ! gvadetect model-instance-id=inf0 model=/root/data/public/yolo-v4-tf/FP16/yolo-v4-tf.xml model_proc=/root/data/pipeline-zoo-models/storage/yolo-v4-tf_INT8/yolo-v4-tf_INT8.json inference-interval=1 device=GPU batch-size=16 pre-process-backend=vaapi-surface-sharing ! queue ! gvafpscounter ! fakesink async=false
FpsCounter(overall 18.02sec): total=85.70 fps, number-streams=1, per-stream=85.70 fps

**Comment by pk1d3v** [comment]
Hi @KiwiHana 

Using the FPS counter to reconstruct the actual number of frames processed may not be accurate due to floating point rounding and timing. For example, teardown process of pipeline can affect numbers in overall FPS, especially when number of frames and/or  interval is small.

For your _initial pipeline_ (first message) I see there's an error in the log, so you need to understand what caused it:
> ERROR: from element /GstPipeline:pipeline0/GstMultiFileSrc:multifilesrc0: Internal data stream error.

Regarding pipeline **2**, (last message), vaapi can schedule operation to HW and pass frame downstream. First element that access the data will cause sync operation for data readiness. In your pipeline no-one uses the data, so no sync operation. This doesn't mean that it misses data, all data is actually processed.

Regarding pipeline **3**, this may be due to the FPS counter and frame count reconstruction reasons that I explained above.

Regarding pipeline **4**, there's error:
> ERROR: from element /GstPipeline:pipeline0/GstMultiFileSrc:multifilesrc0: Internal data stream error.

Regarding pipeline **5**, there's error message that saying that you can't use Inference Engine preprocessing with batching. You need to select different preprocessing via `pre-process-backend` property.
> Inference Engine preprocessing with batching is not supported

**Comment by KiwiHana** [comment]
@pk1d3v 
Hi Kirill, I need to process these images in document by yolo-v4-tf_INT8.xml. However, these pipeline I have tried with yolo-v4-tf_INT8.xml or vappi will miss frames. I want to get the right yolo-v4-tf_INT8.xml pipeline without miss frames. Do you have some suggestion?
 
(This is only one pipeline without miss frames) gst-launch-1.0 multifilesrc location="/root/data/202208/IMG_%04d.JPG" index=0 caps="image/jpeg,framerate=(fraction)30/1" ! decodebin ! gvafpscounter ! fakesink

**Comment by pk1d3v** [comment]
@KiwiHana,

Why do you still think that pipeline is missing frames ?

**Comment by KiwiHana** [comment]
> /root/data/202208/ have 250 JPG files named IMG_0000.png, IMG_0001.png, etc. Decode them is right result. 35.06*7.445418880~=250 images FpsCounter(overall 7.45sec): total=35.06 fps, number-streams=1, per-stream=35.06 fps Execution ended after 0:00:07.445418880
> 
> But decode and then inference by detect model will get wrong results. 0.41 * 105.38 = 43 images Execution ended after 0:01:45.356866255 FpsCounter(overall 105.38sec): total=0.41 fps, number-streams=1, per-stream=0.41 fps
> 
> I install dlstreamer by docker on Ubuntu22.04 Arc A380. GPU means A380. $sudo docker run -it --device /dev/dri/renderD128 --user root --privileged -v /home/your/path/:/root/data --rm intel/dlstreamer:latest /bin/bash
> 
> gst-launch-1.0 multifilesrc location="/root/data/202208/IMG_%04d.JPG" index=0 caps="image/jpeg,framerate=(fraction)30/1" ! decodebin ! gvafpscounter ! fakesink Setting pipeline to PAUSED ... Pipeline is PREROLLING ... Pipeline is PREROLLED ... Setting pipeline to PLAYING ... Redistribute latency... New clock: GstSystemClock FpsCounter(last 1.01sec): total=35.72 fps, number-streams=1, per-stream=35.72 fps FpsCounter(average 1.01sec): total=35.72 fps, number-streams=1, per-stream=35.72 fps FpsCounter(last 1.02sec): total=35.31 fps, number-streams=1, per-stream=35.31 fps FpsCounter(average 2.03sec): total=35.52 fps, number-streams=1, per-stream=35.52 fps FpsCounter(last 1.03sec): total=35.97 fps, number-streams=1, per-stream=35.97 fps FpsCounter(average 3.06sec): total=35.67 fps, number-streams=1, per-stream=35.67 fps FpsCounter(last 1.00sec): total=33.83 fps, number-streams=1, per-stream=33.83 fps FpsCounter(average 4.06sec): total=35.21 fps, number-streams=1, per-stream=35.21 fps FpsCounter(last 1.01sec): total=38.54 fps, number-streams=1, per-stream=38.54 fps FpsCounter(average 5.07sec): total=35.88 fps, number-streams=1, per-stream=35.88 fps FpsCounter(last 1.01sec): total=33.57 fps, number-streams=1, per-stream=33.57 fps FpsCounter(average 6.09sec): total=35.49 fps, number-streams=1, per-stream=35.49 fps FpsCounter(last 1.00sec): total=32.94 fps, number-streams=1, per-stream=32.94 fps FpsCounter(average 7.09sec): total=35.13 fps, number-streams=1, per-stream=35.13 fps FpsCounter(last 0.36sec): total=33.54 fps, number-streams=1, per-stream=33.54 fps FpsCounter(overall 7.45sec): total=35.06 fps, number-streams=1, per-stream=35.06 fps Got EOS from element "pipeline0". Execution ended after 0:00:07.445418880 Setting pipeline to NULL ... Freeing pipeline ...
> 
> gst-launch-1.0 multifilesrc location="/root/data/ouyang/202208/IMG_%04d.JPG" index=0 caps="image/jpeg,framerate=(fraction)30/1" ! decodebin ! gvadetect model=/root/data/open_model_zoo/demos/face_recognition_demo/python/pipeline-zoo-models/storage/yolo-v4-tf_INT8/yolo-v4-tf_INT8.xml model_proc=/root/data/open_model_zoo/demos/face_recognition_demo/python/pipeline-zoo-models/storage/yolo-v4-tf_INT8/yolo-v4-tf_INT8.json inference-interval=1 device=GPU batch-size=1 ! queue ! gvafpscounter ! fakesink Setting pipeline to PAUSED ... Pipeline is PREROLLING ... Pipeline is PREROLLED ... Setting pipeline to PLAYING ... Redistribute latency... New clock: GstSystemClock FpsCounter(last 5.19sec): total=0.96 fps, number-streams=1, per-stream=0.96 fps FpsCounter(average 5.19sec): total=0.96 fps, number-streams=1, per-stream=0.96 fps FpsCounter(last 5.16sec): total=0.19 fps, number-streams=1, per-stream=0.19 fps FpsCounter(average 10.35sec): total=0.58 fps, number-streams=1, per-stream=0.58 fps FpsCounter(last 5.19sec): total=0.19 fps, number-streams=1, per-stream=0.19 fps FpsCounter(average 15.55sec): total=0.45 fps, number-streams=1, per-stream=0.45 fps FpsCounter(last 5.01sec): total=0.20 fps, number-streams=1, per-stream=0.20 fps FpsCounter(average 20.56sec): total=0.39 fps, number-streams=1, per-stream=0.39 fps FpsCounter(last 5.23sec): total=0.19 fps, number-streams=1, per-stream=0.19 fps FpsCounter(average 25.79sec): total=0.35 fps, number-streams=1, per-stream=0.35 fps FpsCounter(last 5.64sec): total=0.18 fps, number-streams=1, per-stream=0.18 fps FpsCounter(average 31.43sec): total=0.32 fps, number-streams=1, per-stream=0.32 fps FpsCounter(last 5.54sec): total=0.54 fps, number-streams=1, per-stream=0.54 fps FpsCounter(average 36.97sec): total=0.35 fps, number-streams=1, per-stream=0.35 fps FpsCounter(last 5.74sec): total=0.17 fps, number-streams=1, per-stream=0.17 fps FpsCounter(average 42.70sec): total=0.33 fps, number-streams=1, per-stream=0.33 fps FpsCounter(last 5.91sec): total=1.35 fps, number-streams=1, per-stream=1.35 fps FpsCounter(average 48.61sec): total=0.45 fps, number-streams=1, per-stream=0.45 fps FpsCounter(last 5.78sec): total=0.35 fps, number-streams=1, per-stream=0.35 fps FpsCounter(average 54.39sec): total=0.44 fps, number-streams=1, per-stream=0.44 fps FpsCounter(last 5.56sec): total=0.72 fps, number-streams=1, per-stream=0.72 fps FpsCounter(average 59.95sec): total=0.47 fps, number-streams=1, per-stream=0.47 fps FpsCounter(last 5.81sec): total=0.17 fps, number-streams=1, per-stream=0.17 fps FpsCounter(average 65.76sec): total=0.44 fps, number-streams=1, per-stream=0.44 fps FpsCounter(last 5.60sec): total=0.71 fps, number-streams=1, per-stream=0.71 fps FpsCounter(average 71.36sec): total=0.46 fps, number-streams=1, per-stream=0.46 fps FpsCounter(last 5.58sec): total=0.18 fps, number-streams=1, per-stream=0.18 fps FpsCounter(average 76.94sec): total=0.44 fps, number-streams=1, per-stream=0.44 fps FpsCounter(last 5.81sec): total=0.69 fps, number-streams=1, per-stream=0.69 fps FpsCounter(average 82.75sec): total=0.46 fps, number-streams=1, per-stream=0.46 fps FpsCounter(last 5.53sec): total=0.18 fps, number-streams=1, per-stream=0.18 fps FpsCounter(average 88.28sec): total=0.44 fps, number-streams=1, per-stream=0.44 fps FpsCounter(last 5.81sec): total=0.52 fps, number-streams=1, per-stream=0.52 fps FpsCounter(average 94.09sec): total=0.45 fps, number-streams=1, per-stream=0.45 fps FpsCounter(last 5.71sec): total=0.18 fps, number-streams=1, per-stream=0.18 fps FpsCounter(average 99.80sec): total=0.43 fps, number-streams=1, per-stream=0.43 fps ERROR: from element /GstPipeline:pipeline0/GstMultiFileSrc:multifilesrc0: Internal data stream error. Additional debug info: ../libs/gst/base/gstbasesrc.c(3127): gst_base_src_loop (): /GstPipeline:pipeline0/GstMultiFileSrc:multifilesrc0: streaming stopped, reason not-negotiated (-4) Execution ended after 0:01:45.356866255 Setting pipeline to NULL ... Freeing pipeline ... FpsCounter(last 5.58sec): total=0.00 fps, number-streams=1, per-stream=0.00 fps FpsCounter(overall 105.38sec): total=0.41 fps, number-streams=1, per-stream=0.41 fps

According to this results. @pk1d3v

**Comment by pk1d3v** [comment]
@KiwiHana 

I commented on both of those pipelines:

`gst-launch-1.0 multifilesrc location="/root/data/202208/IMG_%04d.JPG" index=0 caps="image/jpeg,framerate=(fraction)30/1" ! decodebin ! gvafpscounter ! fakesink`

> vaapi can schedule operation to HW and pass frame downstream. First element that access the data will cause sync operation for data readiness. In your pipeline no-one uses the data, so no sync operation. This doesn't mean that it misses data, all data is actually processed.

---
`gst-launch-1.0 multifilesrc location="/root/data/ouyang/202208/IMG_%04d.JPG" index=0 caps="image/jpeg,framerate=(fraction)30/1" ! decodebin ! gvadetect model=/root/data/open_model_zoo/demos/face_recognition_demo/python/pipeline-zoo-models/storage/yolo-v4-tf_INT8/yolo-v4-tf_INT8.xml model_proc=/root/data/open_model_zoo/demos/face_recognition_demo/python/pipeline-zoo-models/storage/yolo-v4-tf_INT8/yolo-v4-tf_INT8.json inference-interval=1 device=GPU batch-size=1 ! queue ! gvafpscounter ! fakesink`

There's an error in the output for this pipeline:

```diff
-ERROR: from element /GstPipeline:pipeline0/GstMultiFileSrc:multifilesrc0: Internal data stream error.
Additional debug info:
../libs/gst/base/gstbasesrc.c(3127): gst_base_src_loop (): /GstPipeline:pipeline0/GstMultiFileSrc:multifilesrc0:
-streaming stopped, reason not-negotiated (-4)
Execution ended after 0:01:45.356866255
```

You need to understand what causing it. Try to see debug messages by setting `GST_DEBUG` to some value, e.g. `4` and check the logs. Try to simplify pipeline and see if it works.

---
Also repeating general statement:
> Using the FPS counter to reconstruct the actual number of frames processed may not be accurate due to floating point rounding and timing. For example, teardown process of pipeline can affect numbers in overall FPS, especially when number of frames and/or interval is small.

**Comment by akwrobel** [comment]
Closed due to no responce and age
