### ISSUE TITLE
Gvatrack retaining the bounding boxes for few seconds even after the removal of object from frame

### ISSUE THREAD

**Issue by sowmyasri123** [dlstreamer/dlstreamer#362]
I am using  current version of openvino 2022.3 with tracker short-term-imageless but I can see the bounding boxes are still in the frame for 5 seconds after object moved from frame and this issue is not there in the older version od openvino say 2021.4 where I used track type as short-term whose support got removed in the lastest release 

I am attaching you the screenshot for reference
![Screenshot from 2023-05-31 16-55-06](https://github.com/dlstreamer/dlstreamer/assets/20793156/eec27362-b72e-426f-8f43-3289d23c3e99)

**Comment by akwrobel** [comment]
@sowmyasri123 can you please share the pipeline you are using, as well as the command line and information on the media stack.  What version of DL Streamer are you using, and is your usage with the container or built from scratch?

**Comment by sowmyasri123** [comment]
@akwrobel FYI

PIPELINE------>rtspsrc location=rtsp://test123:test@test/stream0  latency=1 timeout=1000 ! queue silent=true max-size-buffers=1 ! rtph264depay !                 h264parse ! vaapih264dec ! video/x-raw! gvadetect model-instance-id=test_cam002 model=test.xml model-proc=test.json device=GPU threshold=0.7 inference-interval=4 ! queue silent=true max-size-buffers=1 leaky=upstream              ! gvapython module=test_filter.py  class=testFilter function=process_frame kwarg={\"camid\":\"cam002\"} ! queue silent=true max-size-buffers=1 leaky=upstream ! gvatrack tracking-type=short-term-imageless  name=gvainference ! queue silent=true max-size-buffers=1 leaky=upstream ! queue silent=true max-size-buffers=1 leaky=upstream ! appsink max-buffers=1 drop=true      
DLstreamer VERSION = latest version of dlstreamer alligned with openvino2022.3
I have built from scratch

**Comment by akwrobel** [comment]
@sowmyasri123 Tracker is based on the detection model, can you share the model you are using?

**Comment by sowmyasri123** [comment]
@akwrobel It is a yolov4 tiny head detector

**Comment by pk1d3v** [comment]
@sowmyasri123 ,

Could you please try [vehicle_pedestrian_tracking](https://github.com/dlstreamer/dlstreamer/tree/master/samples/gstreamer/gst_launch/vehicle_pedestrian_tracking) sample and see if it works? The problem could be related to your model/pipeline.

**Comment by akwrobel** [comment]
Closed due to inactivity and age.
