### ISSUE TITLE
ERROR: from element /GstPipeline:pipeline0/GstGvaDetect:gvadetect0: base_inference plugin initialization failed

### ISSUE THREAD

**Issue by andyyeh75** [dlstreamer/dlstreamer#363]
duplicate to (https://github.com/dlstreamer/dlstreamer/issues/363#issuecomment-1572198342) 
As the original issue is gone.

---

I then want to check the other sample (face_detection_and_classification) and applied some suggestions - now I ran into another type of issue. (changed bug title)

Redistribute latency...
ERROR: from element /GstPipeline:pipeline0/GstGvaDetect:gvadetect0: base_inference plugin initialization failed
Additional debug info:
/root/gst-video-analytics/gst/inference_elements/base/inference_singleton.cpp(173): acquire_inference_instance (): /GstPipeline:pipeline0/GstGvaDetect:gvadetect0:

[face_detection_and_classification.sh.error_0601.txt](https://github.com/dlstreamer/dlstreamer/files/11627334/face_detection_and_classification.sh.error_0601.txt)

**Comment by brmarkus** [comment]
Can you provide more details, please?
Which versions, in which environment, which sample, which command lines have you used?
How have you set-up and installed DL-Streamer?
Can you remember you called a "download model script" prior to try any sample?

**Comment by akwrobel** [comment]
`Failed to construct OpenVINOImageInference
        **Failed to load model '**/home/u/dlstreamer/models/intel/face-detection-adas-0001/FP32/face-detection-adas-0001.xml**'
                [ NETWORK_NOT_READ ] Unable to read the model: /home/u/dlstreamer/models/intel/face-detection-adas-0001/FP32/face-detection-adas-0001.xml** Please check that model format: xml is supported and the model is correct. Available frontends: tf ir paddle onnx
`

Hi @andyyeh75 can you confirm you model is in the path specified and is as expected?

**Comment by andyyeh75** [comment]
Thanks @akwrobel  for the hint. I just checked my face-detection-adas-0001.xml and don't know why it became 0. I downloaded again but still ran into different issues.

old error still exists:
`ERROR: from element /GstPipeline:pipeline0/GstGvaDetect:gvadetect0: base_inference plugin initialization failed`

new error for loading face-detection-adas-0001.xml:
`        Failed to load model '/home/u/dlstreamer/models/intel/face-detection-adas-0001/FP32/face-detection-adas-0001.xml'
                Check 'is_valid_axes_order(axes_order, output_rank)' failed at src/core/shape_inference/include/transpose_shape_inference.hpp:31:
While validating node 'v1::Transpose Transpose_501 (conv4_3_0_norm_mbox_loc[0]:f16[1,16,24,42], conv4_3_0_norm_mbox_loc_perm/Cast_121036_const[0]:i64[4]) -> ()' with friendly_name 'Transpose_501':
Permutation AxisVector{4407826262184049386, 13648051916050991260, 13624947687104175082, 13634380844027659327} is not valid for input shape [1,16,24,42]
`

log attached. 
[face_detection_and_classification.sh.error_0602.txt](https://github.com/dlstreamer/dlstreamer/files/11631236/face_detection_and_classification.sh.error_0602.txt)

**Comment by pk1d3v** [comment]
It still looks like smth is wrong with your model file. The error comes from OpenVINO™.

What version of OpenVINO are you using? How did you install it and DL Streamer?

**Comment by andyyeh75** [comment]
Thanks @pk1d3v 
I simply followed the README in this GitHub to perform "install Intel® DL Streamer Pipeline Framework from APT repository"

[https://dlstreamer.github.io/get_started/install/install_guide_ubuntu.html#id1](url)

**Install Intel® DL Streamer via apt-get install and OpenVINO™ via script install_openvino.sh.**

// Install Intel® DL Streamer
sudo apt-get update && sudo apt-get install intel-dlstreamer-dev

// Install OpenVINO™ toolkit (if not installed)
sudo -E /opt/intel/dlstreamer/install_dependencies/install_openvino.sh

**Configure the environment after installing Intel® DL Streamer and OpenVINO™:**

// Setup OpenVINO™ and Intel® DL Streamer environment
source /opt/intel/openvino_2022/setupvars.sh
source /opt/intel/dlstreamer/setupvars.sh

It installed this openvino version on my machine. Thanks.
openvino_ubuntu20_2022.3.0.9052.9752fafe8eb_x86_64

**Comment by akwrobel** [comment]
Hi @andyyeh75 could you please answer this?
`I'd suggest to check the model once again, and probably try to load model directly with OpenVINO, e.g. using benchmark tool.`

Can you also share how you got the model?  Based on your feedback on the model size and setup this looks like a model issue.

**Comment by andyyeh75** [comment]
@akwrobel sure. I will try to download the model again.  I am working in Intel and as this device is in the lab so due to the restriction of proxy. I will test with employee_hotspot or other way (use a commercially available non-proxied connection.) Thanks a lot.

[https://community.intel.com/t5/Intel-Distribution-of-OpenVINO/Using-OpenVino-with-company-network-proxy/td-p/1341230](url)
