### ISSUE TITLE
I want to show the video from "display" on a VNC destop; but it shows sink error 

### ISSUE THREAD

**Issue by andyyeh75** [dlstreamer/dlstreamer#364]
It is considered as an environment issue so I would like to consult with you if any suggestion.  I want to show the video from "display" on a VNC destop; but it shows sink error as below.  Kindly help me to root cause/resolve this display issue.  **NOTE:** OUTPUT: fps works well.

**Test model:** face_detection_and_classification
**logs:**
gst-launch-1.0 filesrc location=./head-pose-face-detection-female-and-male.mp4 ! decodebin ! gvadetect model=/home/u/dlstreamer/dlstreamer/samples/models/intel/face-detection-adas-0001/FP32/face-detection-adas-0001.xml device=CPU ! queue ! gvaclassify model=/home/u/dlstreamer/dlstreamer/samples/models/intel/age-gender-recognition-retail-0013/FP32/age-gender-recognition-retail-0013.xml model-proc=./model_proc/age-gender-recognition-retail-0013.json device=CPU ! queue ! gvaclassify model=/home/u/dlstreamer/dlstreamer/samples/models/intel/emotions-recognition-retail-0003/FP32/emotions-recognition-retail-0003.xml model-proc=./model_proc/emotions-recognition-retail-0003.json device=CPU ! queue ! gvaclassify model=/home/u/dlstreamer/dlstreamer/samples/models/intel/landmarks-regression-retail-0009/FP32/landmarks-regression-retail-0009.xml model-proc=./model_proc/landmarks-regression-retail-0009.json device=CPU ! queue ! gvawatermark ! videoconvert ! gvafpscounter ! autovideosink sync=false
Setting pipeline to PAUSED ...
Pipeline is PREROLLING ...
Got context from element 'vaapipostproc1': gst.vaapi.Display=context, gst.vaapi.Display=(GstVaapiDisplay)"\(GstVaapiDisplayGLX\)\ vaapidisplayglx0", gst.vaapi.Display.GObject=(GstObject)"\(GstVaapiDisplayGLX\)\ vaapidisplayglx0";
Redistribute latency...
**ERROR: from element /GstPipeline:pipeline0/GstAutoVideoSink:autovideosink0/GstKMSSink:autovideosink0-actual-sink-kms: GStreamer error: negotiation problem.**
### Additional debug info:
../sys/kms/gstkmssink.c(1187): gst_kms_sink_set_caps (): /GstPipeline:pipeline0/GstAutoVideoSink:autovideosink0/GstKMSSink:autovideosink0-actual-sink-kms:
failed to configure video mode
ERROR: pipeline doesn't want to preroll.
Setting pipeline to NULL ...
Freeing pipeline ...

**Comment by brmarkus** [comment]
Does the pipeline work in your environment when you ommit all the GVA related plugins, like

`gst-launch-1.0 filesrc location=./head-pose-face-detection-female-and-male.mp4 ! decodebin ! autovideosink sync=false`

?

Please try to be as specific as possible with the plugins to narrow-down the root-cause, i.e. not using `decodebin` and `autovideosink`, but using specific decoder-, post-processing- and sink-plugins.

**Comment by akwrobel** [comment]
Closed due to age an no response from the submitter
