### ISSUE TITLE
E: Unable to locate package intel-dlstreamer-dev

### ISSUE THREAD

**Issue by OpenVINO-dev-contest** [dlstreamer/dlstreamer#365]
OS: Ubuntu 22.04
Install Intel® DL Streamer Pipeline Framework from APT repository by:
```sudo apt-get update && sudo apt-get install intel-dlstreamer-dev```

got error messages:
```E: Unable to locate package intel-dlstreamer-dev```

Could you help to if there is anything missing in installation steps ?

**Comment by akwrobel** [comment]
Hi @OpenVINO-dev-contest can please make sure you are registering the correct APT repo.  

You can find the instructions on installation at our github.io page here: https://dlstreamer.github.io/get_started/install/install_guide_ubuntu.html#id1

**Comment by OpenVINO-dev-contest** [comment]
Yes I missed it, great thanks
