### ISSUE TITLE
human pose estimation pipeline error

### ISSUE THREAD

**Issue by sathyanarayanmc** [dlstreamer/dlstreamer#367]
hi,
i am running human pose estimation model and i am using human-pose-estimation-0001.json provided by dlstreamer and here is my pipe line gst-launch-1.0 filesrc location="new.mp4" ! decodebin ! gvadetect model="human-pose-estimation-0001.xml" model_proc="humanpose.json" device=CPU ! queue ! videoconvert ! fpsdisplaysink video-sink=xvimagesink sync=false
so i am getting error so,can u help me on this..

Thanks

**Comment by brmarkus** [comment]
Can you provide more details, please?
Which version of DL-Streamer are you using, hoiw have you built/installed it? Running under which OperatingSystem in which version? Where have you received the model "human-pose-estimation-0001" from?

Which error message(s) have you got?
Media-related (have you tried another video?)? Model-related (have you tried another model)?

**Comment by brmarkus** [comment]
Depending on the version of your DL-Streamer, have you tried to use one of the sample-scripts, like under "https://docs.openvino.ai/2021.4/gst_samples_gst_launch_human_pose_estimation_README.html"?

In general, do you see DL-streamer working using any sample-script or any manual pipeline?
In general, do you see gstreamer being able to decode and render the video, without any DL-Streamer/GVA-related plugins?

**Comment by akwrobel** [comment]
@sathyanarayanmc  Can you please provide the printed output of the error you are seeing, and hardware you are using, in addition to the information Markus has requested?  We need to understand your environment and the specific error message you are receiving.

**Comment by akwrobel** [comment]
Closed as this no longer appears to be an issue for the submitter.
