### ISSUE TITLE
Failed to execute tutorial exercise 1 object detection pipeline.

### ISSUE THREAD

**Issue by Arna-Maity** [dlstreamer/dlstreamer#370]
Trying to run the object detection pipeline from the exercise 1 of the DLStreamer tutorial section fails with the following output:

```
gst-launch-1.0 \
filesrc location=${VIDEO_EXAMPLE} ! decodebin ! \
gvadetect model=${DETECTION_MODEL} model_proc=${DETECTION_MODEL_PROC} device=CPU ! queue ! \
gvawatermark ! videoconvert ! fpsdisplaysink video-sink=xvimagesink sync=false

Setting pipeline to PAUSED ...
Pipeline is PREROLLING ...
Got context from element 'vaapipostproc1': gst.vaapi.Display=context, gst.vaapi.Display=(GstVaapiDisplay)"\(GstVaapiDisplayWayland\)\ vaapidisplaywayland0", gst.vaapi.Display.GObject=(GstObject)"\(GstVaapiDisplayWayland\)\ vaapidisplaywayland0";
Redistribute latency...
ERROR: from element /GstPipeline:pipeline0/GstGvaDetect:gvadetect0: base_inference plugin initialization failed
Additional debug info:
/root/gst-video-analytics/gst/inference_elements/base/inference_singleton.cpp(173): acquire_inference_instance (): /GstPipeline:pipeline0/GstGvaDetect:gvadetect0:

Failed to construct OpenVINOImageInference
	Failed to load model '/home/shyamal/intel/dl_streamer/models/intel/person-vehicle-bike-detection-2004/FP32/person-vehicle-bike-detection-2004.xml'
		Check 'false' failed at src/frontends/common/src/frontend.cpp:53:
Converting input model
Cannot create Interpolate layer Resize_177 id:287 from unsupported opset: opset11

ERROR: pipeline doesn't want to preroll.
ERROR: from element /GstPipeline:pipeline0/GstGvaDetect:gvadetect0: base_inference based element initialization has been failed.
Additional debug info:
/root/gst-video-analytics/gst/inference_elements/base/gva_base_inference.cpp(796): gva_base_inference_set_caps (): /GstPipeline:pipeline0/GstGvaDetect:gvadetect0:

inference is NULL.

```
Running on a fresh install of **Ubuntu 22.04 LTS**

**Test System**
*NUC12WSHi5 (i5 1240p)*
*32 GB RAM*

**Comment by akwrobel** [comment]
@Arna-Maity if this is still an issue please provide the information above, otherwise this issue will be closed.

**Comment by Arna-Maity** [comment]
Hi @akwrobel. Actually I don't have the test system with me currently. Can you please keep this issue open for some more time. I will be providing you with the necessary details within this month itself.

**Comment by Arna-Maity** [comment]
@akwrobel 

`mo --version` gives the following output:

```
Version of Model Optimizer is: 2023.0.1-11005-fa1c41994f3-releases/2023/0
```
How do I find the DL Streamer version installed on my system?

**Comment by brmarkus** [comment]
Do you remember how you have installed DL-Streamer? Have you followed installation descriptions, if yes, which?
Built from source?
Running within a Docker container?
Installed via "apt get installed"?
Downloaded pre-built packages?

Which "exercise 1 of the DLStreamer tutorial section" are you referring to?
Can you remember to have called a `source` command to get search paths exported and ENV variables set?

**Comment by Arna-Maity** [comment]
@brmarkus 
I followed the apt get install method.
I am referring to this example: https://dlstreamer.github.io/get_started/tutorial.html#object-detection 

I also have the environment variable setup script executed in my .bashrc file. The scripts are run on starting a new session as I get the following output upon starting a new terminal session.
![image](https://github.com/dlstreamer/dlstreamer/assets/32426434/23105914-4873-41e2-84e8-3ec60dab3387)

**Comment by Arna-Maity** [comment]
I completely removed DLStreamer by following the command here: 
https://dlstreamer.github.io/get_started/install/uninstall_guide_ubuntu.html#option-1-uninstall-intel-deep-learning-streamer-intel-dl-streamer-pipeline-framework-from-apt-repository

And reinstalling DLStreamer following the [install guide](https://dlstreamer.github.io/get_started/install/install_guide_ubuntu.html#option-1-install-intel-dl-streamer-pipeline-framework-from-debian-packages) seems to have solved the issue.

The [tutorial examples](https://dlstreamer.github.io/get_started/tutorial.html#) mentioned in the DLStreamer website work fine now.

Thanks @brmarkus @akwrobel.
