### ISSUE TITLE
How to add each color to the each label given in the json file 

### ISSUE THREAD

**Issue by smohammad-de** [dlstreamer/dlstreamer#372]
{
    "json_schema_version": "2.2.0",
    "input_preproc": [],
    "output_postproc": [
        {
            "layer_name": "age_conv3",
            "attribute_name": "age",
            "converter": "text",
            "text_precision": 0,
            "text_scale": 100.0
        },
        {
            "layer_name": "prob",
            "attribute_name": "gender",
            "labels": [
                "Female",
                "Male"
            ],
            "converter": "label",
            "method": "max"
        }
    ]
}

For this  "labels": ["Female","Male"]
add green colour for female and red colour for male for both bounding box and class name.

**Comment by brmarkus** [comment]
You might want to look into the older issues:
https://github.com/dlstreamer/dlstreamer/issues/290
https://github.com/dlstreamer/dlstreamer/issues/218

Looks like it cannot simply be configured in the model-proc-json file.

**Comment by smohammad-de** [comment]
Thanks @brmarkus , I'll take a look.

**Comment by brmarkus** [comment]
Have you got it working in the meantime?
Or found a different solution?

**Comment by akwrobel** [comment]
Closed due to inactivity
