### ISSUE TITLE
How to convert webcam video v4l2src device=/dev/video0 to a grayscale image and pass it back to the pipeline using cpp

### ISSUE THREAD

**Issue by smohammad-de** [dlstreamer/dlstreamer#374]
I have this command , gst-launch-1.0 -v v4l2src device=/dev/video0 name="source" ! decodebin ! videorate ! video/x-raw,framerate=30/1 ! videoconvert !  autovideosink

Retrieve the source element and do changes to the frame and pass it back to the pipeline.

Thanks!!

**Comment by brmarkus** [comment]
Your question doesn't seem to be related to DL-Streamer, does it, or do you have something specific in mind with your pipeline with respect to DL-Streamer (and OpenVINO and e.g. OpenCV)?

You might want to use the gst plugin "chromahold" if supported and available in your environment, see "https://gstreamer.freedesktop.org/documentation/coloreffects/chromahold.html?gi-language=c" (doing the conversion using the CPU, and not GPU-accelerated).

You could also use the plugin "videoconvert" to e.g. do a conversion to "GRAY8" (also using CPU and not the GPU).

There is also a plugin like "v4l2convert " to do the conversion.

You might also double-check your camera/video-source - it might support greyscale-image natively (like RealSense or Luxonis OAK).
