### ISSUE TITLE
run classification_with_background_removal.sh failed

### ISSUE THREAD

**Issue by zhjunqin** [dlstreamer/dlstreamer#377]
ERROR: from element /GstPipeline:pipeline0/ObjectClassify:objectclassify0/GstBin:bin0/opencv_remove_background:opencv_remove_background0: Failed to process buffer inplace
Additional debug info:
/root/intel/dlstreamer_gst/src/gst/lib/transform_element.cpp(526): transform_ip (): /GstPipeline:pipeline0/ObjectClassify:objectclassify0/GstBin:bin0/opencv_remove_background:opencv_remove_background0:
Buffer: 0x7f2ab00be000. PTS: 67039106. Error: Error getting data_buffer
Execution ended after 0:00:00.668596000

**Comment by brmarkus** [comment]
Can you provide more details, please?
What does your environment look like - running natively, in a Docker container, in a Python virt-env?
Which version of DL-Streamer and OpenVINO have you installed - and how was it installed?

Have you applied any local changes, provided command line parameters, using your own models or videos or pictures?

Do you get a different demo or sample-script working, or do you see a manually constructed gstreamer pipeline with DL-Streamer working?

**Comment by zhjunqin** [comment]
> Can you provide more details, please? What does your environment look like - running natively, in a Docker container, in a Python virt-env? Which version of DL-Streamer and OpenVINO have you installed - and how was it installed?
> 
> Have you applied any local changes, provided command line parameters, using your own models or videos or pictures?
> 
> Do you get a different demo or sample-script working, or do you see a manually constructed gstreamer pipeline with DL-Streamer working?

I'm using docker image  intel/dlstreamer:devel

after download model, change classification_with_background_removal.sh as below, 

```
INPUT=${1:-/data/videos/bottle-detection.mp4}
DEVICE=${2:-CPU}
OUTPUT=${3:-json} # Supported values: display, fps, json, display-and-json
```
then run

```
root:/opt/intel/dlstreamer/samples/gstreamer/gst_launch/instance_segmentation# ./classification_with_background_removal.sh
Running sample with the following parameters:
GST_PLUGIN_PATH=/opt/intel/dlstreamer/lib/gstreamer-1.0:/opt/intel/dlstreamer/gstreamer/lib/gstreamer-1.0:
gst-launch-1.0 filesrc location=/data/videos/bottle-detection.mp4 ! decodebin force-sw-decoders=true ! object_detect model=/home/dlstreamer/intel/dl_streamer/models/intel/instance-segmentation-security-1040/FP32/instance-segmentation-security-1040.xml device=CPU labels-file=/opt/intel/dlstreamer/samples/labels/coco_80cl.txt ! object_classify nireq=32 preprocess="videoconvert ! roi_split ! opencv_cropscale ! opencv_remove_background ! videoconvert ! videoscale ! tensor_convert" model=/home/dlstreamer/intel/dl_streamer/models/public/efficientnet-b0/FP32/efficientnet-b0.xml device=CPU postprocess="tensor_postproc_label threshold=0.2 labels-file=/opt/intel/dlstreamer/samples/labels/imagenet_2012.txt method=softmax" ! gvametaconvert ! gvametapublish file-format=json-lines file-path=output.json ! fakesink async=false

(gst-launch-1.0:426): GStreamer-WARNING **: 12:46:33.194: External plugin loader failed. This most likely means that the plugin loader helper binary was not found or could not be run. You might need to set the GST_PLUGIN_SCANNER environment variable if your setup is unusual. This should normally not be required though.
/usr/local/lib/python3.10/dist-packages/numpy/core/getlimits.py:518: UserWarning: The value of the smallest subnormal for <class 'numpy.float64'> type is zero.
  setattr(self, word, getattr(machar, word).flat[0])
/usr/local/lib/python3.10/dist-packages/numpy/core/getlimits.py:89: UserWarning: The value of the smallest subnormal for <class 'numpy.float64'> type is zero.
  return self._float_to_str(self.smallest_subnormal)
/usr/local/lib/python3.10/dist-packages/numpy/core/getlimits.py:518: UserWarning: The value of the smallest subnormal for <class 'numpy.float32'> type is zero.
  setattr(self, word, getattr(machar, word).flat[0])
/usr/local/lib/python3.10/dist-packages/numpy/core/getlimits.py:89: UserWarning: The value of the smallest subnormal for <class 'numpy.float32'> type is zero.
  return self._float_to_str(self.smallest_subnormal)
Setting pipeline to PAUSED ...
Pipeline is PREROLLING ...
Redistribute latency...
Redistribute latency...
Redistribute latency...
Redistribute latency...
Pipeline is PREROLLED ...
Setting pipeline to PLAYING ...
New clock: GstSystemClock
Redistribute latency...
ERROR: from element /GstPipeline:pipeline0/ObjectClassify:objectclassify0/GstBin:bin0/opencv_remove_background:opencv_remove_background0: Failed to process buffer inplace
Additional debug info:
/home/dlstreamer/dlstreamer/src/gst/lib/transform_element.cpp(526): transform_ip (): /GstPipeline:pipeline0/ObjectClassify:objectclassify0/GstBin:bin0/opencv_remove_background:opencv_remove_background0:
Buffer: 0x7f9070106000. PTS: 67039106. Error: mask metadata not found
Execution ended after 0:00:00.743644064
Setting pipeline to NULL ...
Freeing pipeline ...

```

**Comment by brmarkus** [comment]
Which HW, which system do you run Docker and DL-Streamer on?

Instead on using the "latest of the latest" with `intel/dlstreamer:devel` can you try one of the release images?

**Comment by akwrobel** [comment]
**intel/dlstreamer:devel** is the correct latest image of the developer image, **intel/dlstreamer:latest** is the runtime image.  These tags are updated at release time, so as long as the image was pulled post the release last week the image should be correct.  

There are known issues with instance segmentation as called out in the release notes.  This functionality for the 2.0 samples currently is not functional.  

<html>
<body>


Preview Architecture 2.0 Samples | Preview Arch 2.0 samples have known issues with inference results
-- | --



</body>
</html>

**Comment by zhjunqin** [comment]
> Which HW, which system do you run Docker and DL-Streamer on?
> 
> Instead on using the "latest of the latest" with `intel/dlstreamer:devel` can you try one of the release images?

Intel(R) Core(TM) i7-10700K CPU

**Comment by brmarkus** [comment]
The script `classification_with_background_removal.sh` seems about instance segmentation (from the logs in the initial post the model `instance-segmentation-security-1040.xml`).

@akwrobel can you recommend another, maybe older version of the DL-Streamer container to use known to have instance segmentation working?

**Comment by akwrobel** [comment]
You can try on the previous 2022.3.0 releases from dockerhub.
