### ISSUE TITLE
YOLO V8 Support.

### ISSUE THREAD

**Issue by VijayaKumarKamma** [dlstreamer/dlstreamer#378]
Hi Team,

Can you please confirm me - if we can use Yolov8 IR models in Dlstreamer latest ?

If yes please provide me the proc file and converter name i should use. This will help us immensely.

**Comment by VijayaKumarKamma** [comment]
Please reply on this.

**Comment by brmarkus** [comment]
Have you checked @OpenVINO-dev-contest comment under "https://github.com/dlstreamer/dlstreamer/issues/366#issuecomment-1759176751"?

**Comment by akwrobel** [comment]
@VijayaKumarKamma This is not a default supported model for DL Streamer, but your can add your own implementation.  for Yolov8 there is an example of someone who has done this that's @brmarkus has pointed out.

**Comment by VijayaKumarKamma** [comment]
> Have you checked @OpenVINO-dev-contest comment under "[#366 (comment)](https://github.com/dlstreamer/dlstreamer/issues/366#issuecomment-1759176751)"?

Hi @brmarkus and @OpenVINO-dev-contest Thanks for the help- we are able to run yolo v8 - but is there is any reason why you have hard coded 84 as the object size - if it is custom trained with 1 class - the converter script is failing. Please let me know how to handle this.

**Comment by VijayaKumarKamma** [comment]
Hi @brmarkus  and @OpenVINO-dev-contest   please reply on this

**Comment by brmarkus** [comment]
Can you confirm you see a stock, default, standard YoloV8 model from Ultralytics running in a pipeline successfully? It was working and showcased before

With your own (re-)trained model with your specific pre- and post-processing you would need to taylor your config files on your own.
See e.g.
- https://dlstreamer.github.io/dev_guide/how_to_create_model_proc_file.html
- https://dlstreamer.github.io/dev_guide/model_proc_file.html

**Comment by howardwa1** [comment]
looks the object size =80 was hard coded. Can someone help to point out the places need to be changed to adapt custom classes?

**Comment by howardwa1** [comment]
Yes, I have changed that line to my number, e.g. I have 16 classes, so I put 20 there.
Also recompiled dlstreamer libs, but looks no working at all.

**Comment by howardwa1** [comment]
It works now , thanks

**Comment by howardwa1** [comment]
That change should be enough. But the dlstreamer should be recomplied and the new libs should be copied to : /home/dlstreamer/dlstreamer_gst/build/intel64/Release/lib
