### ISSUE TITLE
Architecture 2.0 not supported element gvapython

### ISSUE THREAD

**Issue by nikulin-94** [dlstreamer/dlstreamer#379]
Hi!

I'm currently testing the new architecture version 2.0. In the previous version the pipeline consisted ....->gvainference->gvapython->..., where I could use python for post-processing. How can I implement this post-processing in version 2.0?  If video_inference->gvapython not supported.

Thank you!

**Comment by akwrobel** [comment]
Hi @nikulin-94 this is not supported in the 2.0 preview.  This should be done using 1.0 not the 2.0 preview.

**Comment by akwrobel** [comment]
@nikulin-94 Do you have any further questions using 1.0?

**Comment by nikulin-94** [comment]
@akwrobel, Thank you, this issue can be closed.
