### ISSUE TITLE
Problem overwrite roi in python_object_association.

### ISSUE THREAD

**Issue by nikulin-94** [dlstreamer/dlstreamer#380]
Hi! 
I'm testing the "python_object_association" element.

My pipeline:
..->gvainference (detector)->gvapython->gvainference (re_id model)->python_object_association->...sink (get_buffer)

And I noticed a feature/bug:

If the "python_object_association" element has "overwrite-roi"=true (the default), then all roi.confidence()s are nulled.
print(roi.confidence()) -> 0.0

**Comment by akwrobel** [comment]
@nikulin-94  can you please share the model you are using and the full pipeline.

**Comment by akwrobel** [comment]
@nikulin-94 Can you please provide the requested information?

**Comment by nikulin-94** [comment]
@akwrobel, Yes, I can provide information, but I need a little more time to repeat the pipeline.

**Comment by akwrobel** [comment]
Hi @nikulin-94 it has been over a month since your last update, please update this week with the requested information or this issue will be closed.

**Comment by akwrobel** [comment]
Closing due to age.
