### ISSUE TITLE
Regarding the problem of confusing bbox drawing after running gst launch in the 2023.0 version of the sample

### ISSUE THREAD

**Issue by tonyeatsm** [dlstreamer/dlstreamer#382]
Download models:

cd /root/dl_streamer/models
MODEL_PATH=intel/instance-segmentation-security-1040/FP32
mkdir -p $MODEL_PATH && cd $MODEL_PATH
wget https://storage.openvinotoolkit.org/repositories/open_model_zoo/2022.3/models_bin/1/instance-segmentation-security-1040/FP32/instance-segmentation-security-1040.xml
wget https://storage.openvinotoolkit.org/repositories/open_model_zoo/2022.3/models_bin/1/instance-segmentation-security-1040/FP32/instance-segmentation-security-1040.bin

Run the script as follows:

GST_PLUGIN_PATH=/opt/intel/dlstreamer/lib/gstreamer-1.0:/opt/intel/dlstreamer/gstreamer/lib/gstreamer-1.0::/opt/tidystream/tidystreame-1.0/lib/gst-plugins:/opt/tidystream/tidystreame-1.0/lib/gst-plugins:/opt/tidystream/tidystreame-1.0/lib/gst-plugins
gst-launch-1.0 filesrc location=/root/dl_streamer/datasets/samples-videos/classroom.mp4 ! decodebin ! object_detect model=/root/dl_streamer/models/intel/instance-segmentation-security-1040/FP32/instance-segmentation-security-1040.xml device=CPU labels-file=/root/dl_streamer/sources/dlstreamer/samples/labels/coco_80cl.txt ! gvawatermark ! videoconvert ! gvafpscounter ! autovideosink sync=false

Problem: All label labels are drawn on one target, and the labels overlap and are confusing

I suspect there is a problem with gvawatermark drawing. How can I solve it?

**Comment by akwrobel** [comment]
@tonyeatsm 
It is a known issue with the samples and architecture 2.0, from the release notes:
<html>
<body>


Preview Architecture 2.0 Samples | Preview Arch 2.0 samples have known issues with inference results
-- | --



</body>
</html>
