### ISSUE TITLE
docker file missing in latest release

### ISSUE THREAD

**Issue by zhjunqin** [dlstreamer/dlstreamer#383]
In old release, there are docker files.

https://github.com/dlstreamer/dlstreamer/tree/2022.3-release/docker

**Comment by akwrobel** [comment]
@zhjunqin Removal of the dockerfile in the 2023.0 release was an intentional change as we change our docker build process.

**Comment by zhjunqin** [comment]
> @zhjunqin Removal of the dockerfile in the 2023.0 release was an intentional change as we change our docker build process.



> What would the new Docker build process look like, now, @akwrobel ? The installation guide, referencing "https://dlstreamer.github.io/get_started/install/install_guide_ubuntu.html", only describes to _pull_ a _pre-built_ container.
> 
> But how to build (and maybe adapt&extend) a Docker container on our own now?

Same question with @brmarkus , we'd like to adapt&extend dlstreamer,  could you share docker file?

**Comment by akwrobel** [comment]
@zhjunqin We do not provide the build files for APT package creation, which the dockerfile pulls in during build, and the required APT packages are to published due to the build changes.  This precludes the ability to build with the dockerfile.  This should be resolved in the next release
