### ISSUE TITLE
yolo v8 custom models with 1 classes is throwing error 

### ISSUE THREAD

**Issue by Snehashishd2** [dlstreamer/dlstreamer#386]
We have trained a custom yolov8n model with a single class. While trying to infer the model from the pipeline. We are getting this error.
Post-processing has been exited with FAIL code.
0:00:06.988972104 18250 0x7fc8dc0b28c0 ERROR             GVA_common post_processor_impl.cpp:130:process: Post-processing error: 
Failed to do YoloV8 post-processing.
        Object size dimension of output blob is set to 5, but only 84 supported.

**Comment by VijayaKumarKamma** [comment]
Please reply on this.

**Comment by JSVJ** [comment]
Hi @Snehashishd2 , Are you using it in MS Win system or some other operating systems? Do you have a GPU or running only in CPU ?

**Comment by Snehashishd2** [comment]
We are using Ubuntu 20.04 with this docker image snake7gun/dlstreamer-yolov8-2023.0:latest

**Comment by akwrobel** [comment]
Hi @Snehashishd2 Can you provide more information on your configuration and HW setup?  You are using a custom docker image as it does not appear to be one of the official ones
**DockerHub tags list:** https://hub.docker.com/r/intel/dlstreamer/tags?page=1
Additionally Ubuntu 20.04 was noted as no longer being actively supported as of our 2023.0 release and was noted as going away in the previous release: https://github.com/dlstreamer/dlstreamer/releases

**Comment by Snehashishd2** [comment]
Hi, we are using #378 yolov8-2023.0 branch [](https://github.com/OpenVINO-dev-contest/dlstreamer/blob/yolov8-2023.0/demo/README.md) , you can run this docker. 
For getting a yolov8 model we are just using  
`from ultralytics import YOLO
    model = YOLO('yolov8n.pt')
    results = model.export(format='onnx')` from [ultralytics/engine/exporter.py](https://github.com/ultralytics/ultralytics/blob/70c400ee158fc52361e6d38e4b93f55fff21edd7/ultralytics/engine/exporter.py)
For a custom model of a single class.
Proc file 
`{
    "json_schema_version": "2.2.0",
    "input_preproc": [
      {
          "params": {
              "resize": "aspect-ratio"
          }
      }
    ],
    "output_postproc": [
      {
        "converter": "yolo_v8",
        "labels": [
            "person"
        ]
      }
    ]
  }`

**Comment by Snehashishd2** [comment]
@OpenVINO-dev-contest

**Comment by akwrobel** [comment]
@Snehashishd2 you are working with your own custom implementation, do you have any DLS related questions on the implementation?
Please make sure you are updating to a supported OS in this case you should be using 22.04 Ubuntu.  Please make sure your docker image is based on our latest image and there is no conflict with OpenVINO and let us know if you still have issues.

**Comment by akwrobel** [comment]
@Snehashishd2 Please let us know if you have any DLS related questions.

**Comment by akwrobel** [comment]
Closed as there has been no further response from the submitter and there are no DLS asks
