### ISSUE TITLE
gvadetect failing to initialize

### ISSUE THREAD

**Issue by mwright-pivotal** [dlstreamer/dlstreamer#387]
I am trying to run classification with a custom model but get an error that doesn't seem to be documented anywhere.   How can I find the reason for this error? 

env is dlstreamer docker image:

docker run -it --device /dev/dri --rm -v /home/mwright/projects/blackjack:/home/dlstreamer/blackjack intel/dlstreamer

> gst-launch-1.0 filesrc location=cards-sample.m4v ! decodebin ! gvadetect model=models/quantized_cards_detect-1023.xml device=CPU ! queue ! gvawatermark ! fakesink

output:

(gst-launch-1.0:12): GStreamer-WARNING **: 16:10:21.277: External plugin loader failed. This most likely means that the plugin loader helper binary was not found or could not be run. You might need to set the GST_PLUGIN_SCANNER environment variable if your setup is unusual. This should normally not be required though.
/usr/local/lib/python3.10/dist-packages/numpy/core/getlimits.py:549: UserWarning: The value of the smallest subnormal for <class 'numpy.float64'> type is zero.
  setattr(self, word, getattr(machar, word).flat[0])
/usr/local/lib/python3.10/dist-packages/numpy/core/getlimits.py:89: UserWarning: The value of the smallest subnormal for <class 'numpy.float64'> type is zero.
  return self._float_to_str(self.smallest_subnormal)
/usr/local/lib/python3.10/dist-packages/numpy/core/getlimits.py:549: UserWarning: The value of the smallest subnormal for <class 'numpy.float32'> type is zero.
  setattr(self, word, getattr(machar, word).flat[0])
/usr/local/lib/python3.10/dist-packages/numpy/core/getlimits.py:89: UserWarning: The value of the smallest subnormal for <class 'numpy.float32'> type is zero.
  return self._float_to_str(self.smallest_subnormal)
Setting pipeline to PAUSED ...
error: XDG_RUNTIME_DIR not set in the environment.
Pipeline is PREROLLING ...
Got context from element 'vaapipostproc1': gst.vaapi.Display=context, gst.vaapi.Display=(GstVaapiDisplay)"\(GstVaapiDisplayDRM\)\ vaapidisplaydrm2", gst.vaapi.Display.GObject=(GstObject)"\(GstVaapiDisplayDRM\)\ vaapidisplaydrm2";
Redistribute latency...
Redistribute latency...
Redistribute latency...
ERROR: from element /GstPipeline:pipeline0/GstGvaDetect:gvadetect0: base_inference based element initialization has been failed.
Additional debug info:
/home/dlstreamer/dlstreamer/src/monolithic/gst/inference_elements/base/gva_base_inference.cpp(796): gva_base_inference_set_caps (): /GstPipeline:pipeline0/GstGvaDetect:gvadetect0:

post-processing is NULL.
ERROR: pipeline doesn't want to preroll.
Setting pipeline to NULL ...
Freeing pipeline ...

**Comment by brmarkus** [comment]
Can you describe your environment - hardware and software (which OS, versions, how DL-Streamer and OpenVINO was installed, natively or inside a container, how was the container started) -  first, please?
Do you have a monitor connected?
How are you using your system, directly (via monitor and keyboard) ore remotely (like SSH connection)?
`error: XDG_RUNTIME_DIR not set in the environment` is critical - you can find this issue being reported a couple of times.
Can you set and export the ENV variable with your display config?
Can you have a quick consistenty test with using OpenVINO directly (one of the samples and demos of OpenVINO and Open-Model-Zoo)?

**Comment by mwright-pivotal** [comment]
Hello Markus - thanks for taking a look...

I am running DLStreamer from inside the latest version of the docker image published by Intel (intel/dlstreamer).   Docker is running on Ubuntu 20.04.  My hardware is an Intel NUC7i5, with iGPU but an older one (Intel Corporation Iris Plus Graphics 640)

I ssh into the NUC to run this, which does not have a monitor attached.   Are you suggesting that gstreamer/dlstreamer only will work in an X11 enabled OS?

Thanks again for the help?

**Comment by brmarkus** [comment]
The latest Docker container image of DL-Streamer has received bigger architectural changes recently. If you have still storage capacity left, could you try an older version?
(Ubuntu 22.04 is supported in the meantime, but 20.04 not; but important is the OS inside your used container image)

From the OpenVINO system requirements (e.g. "https://www.intel.com/content/www/us/en/developer/tools/openvino-toolkit/system-requirements.html") your system seems to be supported.

Systems without a connected monitor are supported (plus systems without a GPU/iGPU/dGPU as well) - however, you would need to set&export e.g. `DISPLAY` and/or `XDG_RUNTIME_DIR` (depending on whether its X/X11 or Wayland), if you want to use the GPU for e.g. HW-accelerated video-decoding (which might be hidden in your used GST plugin `decodebin`, using the VAAPI-based plugins and libva-interface).

**Comment by mwright-pivotal** [comment]
ok, thanks Markus.  I will look into how to set XDG_RUNTIME_DIR.  I assume this needs to be set from inside the docker container after it starts.

Doing some more test, it seems like one of the samples works..   I launched a container instance as follows:

`docker run -it --device /dev/dri --group-add=$(stat -c "%g" /dev/dri/render*) --rm -v /home/mwright/projects/blackjack:/home/dlstreamer/blackjack intel/dlstreamer:devel`

then running face detection sample with "fps" sink:

`dlstreamer@3bded1b7edc8:/opt/intel/dlstreamer/samples/gstreamer/gst_launch/face_detection_and_classification$ ./face_detection_and_classification.sh ~/blackjack/cards-sample.m4v GPU fps
gst-launch-1.0 filesrc location=/home/dlstreamer/blackjack/cards-sample.m4v ! decodebin ! gvadetect model=/home/dlstreamer/intel/dl_streamer/models/intel/face-detection-adas-0001/FP32/face-detection-adas-0001.xml device=GPU ! queue ! gvaclassify model=/home/dlstreamer/intel/dl_streamer/models/intel/age-gender-recognition-retail-0013/FP32/age-gender-recognition-retail-0013.xml model-proc=./model_proc/age-gender-recognition-retail-0013.json device=GPU ! queue ! gvaclassify model=/home/dlstreamer/intel/dl_streamer/models/intel/emotions-recognition-retail-0003/FP32/emotions-recognition-retail-0003.xml model-proc=./model_proc/emotions-recognition-retail-0003.json device=GPU ! queue ! gvaclassify model=/home/dlstreamer/intel/dl_streamer/models/intel/landmarks-regression-retail-0009/FP32/landmarks-regression-retail-0009.xml model-proc=./model_proc/landmarks-regression-retail-0009.json device=GPU ! queue ! gvafpscounter ! fakesink async=false
Setting pipeline to PAUSED ...
Pipeline is PREROLLING ...
Redistribute latency...
Redistribute latency...
error: XDG_RUNTIME_DIR not set in the environment.
Got context from element 'vaapipostproc0': gst.vaapi.Display=context, gst.vaapi.Display=(GstVaapiDisplay)"\(GstVaapiDisplayDRM\)\ vaapidisplaydrm1", gst.vaapi.Display.GObject=(GstObject)"\(GstVaapiDisplayDRM\)\ vaapidisplaydrm1";
Redistribute latency...
Redistribute latency...
Pipeline is PREROLLED ...
Setting pipeline to PLAYING ...
New clock: GstSystemClock
Redistribute latency...
FpsCounter(last 1.01sec): total=210.85 fps, number-streams=1, per-stream=210.85 fps
FpsCounter(average 1.01sec): total=210.81 fps, number-streams=1, per-stream=210.81 fps
FpsCounter(last 1.01sec): total=118.82 fps, number-streams=1, per-stream=118.82 fps
FpsCounter(average 2.02sec): total=164.73 fps, number-streams=1, per-stream=164.73 fps
FpsCounter(last 1.00sec): total=114.67 fps, number-streams=1, per-stream=114.67 fps
FpsCounter(average 3.02sec): total=148.10 fps, number-streams=1, per-stream=148.10 fps
FpsCounter(last 1.00sec): total=118.58 fps, number-streams=1, per-stream=118.58 fps
FpsCounter(average 4.02sec): total=140.73 fps, number-streams=1, per-stream=140.73 fps
FpsCounter(last 1.00sec): total=118.42 fps, number-streams=1, per-stream=118.42 fps
FpsCounter(average 5.03sec): total=136.27 fps, number-streams=1, per-stream=136.27 fps
FpsCounter(last 0.49sec): total=119.51 fps, number-streams=1, per-stream=119.51 fps
FpsCounter(overall 5.51sec): total=134.80 fps, number-streams=1, per-stream=134.80 fps
Got EOS from element "pipeline0".
Execution ended after 0:00:23.673104279
Setting pipeline to NULL ...
Freeing pipeline ..`

I still get XDG_RUNTIME_DIR error but it seems to be inconsequential?

**Comment by brmarkus** [comment]
You would need to forward `DISPLAY` and/or `XDG_RUNTIME_DIR` from your HOST into your container via the `docker run` command line (see e.g. https://docs.docker.com/engine/reference/commandline/run/#env), like `-e DISPLAY=${DISPLAY} -v /tmp/.X11-unix:/tmp/.X11-unix` or `-e XDG_RUNTIME_DIR=${XDG_RUNTIME_DIR}`.

The behaviour could differ between e.g. a gstreamer-command-line based sample/demo or a Python script or C/C++ application (with compiled-in CPU- or GPU-based video-decoding via OpenCV).

**Comment by akwrobel** [comment]
@mwright-pivotal As @brmarkus mentioned above 20.04 is no longer a supported Operating system, can you please confirm the Docker container version you are pulling, or if it is **latest**, when you last pulled?  [Our last release 2023.0 was Sept 29th](https://github.com/dlstreamer/dlstreamer/releases/tag/2023.0-release) and 20.04 support was dropped.  

_gst-launch-1.0 filesrc location=cards-sample.m4v ! decodebin ! gvadetect model=models/quantized_cards_detect-1023.xml device=CPU ! queue ! gvawatermark ! fakesink_

This is missing **model_proc file**, as a result the element can not determine what post-processing should be used for the model
You can add this file, or change to **gvainference** to disable post-processing.  
Documentation can be found on our GitHub.io site (linked from the repo) [model_proc file](https://dlstreamer.github.io/dev_guide/model_proc_file.html)

**Comment by mwright-pivotal** [comment]
Hi @akwrobel I am using the latest docker image from Intel.  So I assume that's built with a 22.04 ubuntu base?  The Host OS that runs Docker Daemon is Ubuntu 20.04 though.    Are you saying that Host OS running Docker also needs to be 20.04?  I can probably upgrade if that's a requirement. 

Although here are some updates I have been tryin on my end:

1. I was working with a YOLOv8 mode converted to IR.  It works fine with my python code using Openvino but I noticed that dlstreamer only supports up Yolov5 so I retrained another version based on that.
2. So far setting XDG_RUNTIME_DIR or not seems to have no affect on the behavior other than an error message
3. Pipeline is now: `gst-launch-1.0 -vvv urisourcebin buffer-size=4096 uri=rtsp://user:password@192.168.0.33/axis-media/media.amp?videocodec=h264 ! decodebin ! gvadetect model=models/yolov5_openvino/cards-yolov5.xml model_proc=blackjack-model-proc-v2.json device=GPU ! queue ! gvametaconvert ! gvametapublish file-format=json-lines file-path=output.json ! fakesink async=false`
4. output.json is empty
5. based on output it does seem to be processing feed from camera
6. model_proc file does not have much in it but I am unsure what, if any, input_proc config is needed. 

{
  "json_schema_version": "2.0.0",
  "input_preproc": [],
  "output_postproc": [
    {
      "labels": [
	  "10C", "10D", "10H", "10S", "2C", "2D", "2H", "2S", "3C", "3D", "3H", "3S", "4C", "4D", "4H", "4S", "5C", "5D", "5H", "5S", "6C", "6D", "6H", "6S", "7C", "7D", "7H", "7S", "8C", "8D", "8H", "8S", "9C", "9D", "9H", "9S", "AC", "AD", "AH", "AS", "JC", "JD", "JH", "JS", "KC", "KD", "KH", "KS", "QC", "QD", "QH", "QS"
      ],
      "converter": "boxes_labels"
    }
  ]
}

Is there a way to get any diagnostic info from gvadetect to see why nothing comes out?

**Comment by akwrobel** [comment]
@mwright-pivotal this looks like it may be an issue with our model_proc file, can you share how you created it, and what documentation you used?

**Comment by mwright-pivotal** [comment]
well, I am just using the dlstreamer docs for model_proc and looking at samples (person-vehicle-bike-detection, etc) but I am not 100% confident I understand everything accurately so it could definitely be a misunderstanding/learning curve on my end.  

I have been sharing my work in this repo:  https://github.com/mwright-pivotal/blackjack-cv-ai-backend/tree/master. Running Openvino with Python code and a converted Yolov8 works fine.  I am trying to accomplish the same with dlstreamer and assuming I have to be working off Yolov5s based model.  model_proc and shell script to run the pipeline are in the dlstreamer folder referencing models from the models folder.  Input layer of model is called "images" 
<img width="1242" alt="image" src="https://github.com/dlstreamer/dlstreamer/assets/5115931/2abd9e73-dc60-46ed-8b3f-dc418717ba25">

**Comment by mwright-pivotal** [comment]
I found the solution.  The key piece of documentation that helped me resolve is here: https://dlstreamer.github.io/dev_guide/yolov5_model_preparation.html#model-pre-post-processing

Output.json now producing output!  I'll commit my changes to the repo I shared.   You may close this issue.

{"objects":[{"detection":{"bounding_box":{"x_max":0.3329620952352199,"x_min":0.2637028559600738,"y_max":0.8092757792662943,"y_min":0.7777601864600208},"confidence":0.8889567852020264,"label":"3C","label_id":8},"h":20,"region_id":347,"roi_type":"3C","w":33,"x":127,"y":498},{"detection":{"bounding_box":{"x_max":0.18577046919520393,"x_min":0.14733011395727758,"y_max":0.4948729231189626,"y_min":0.4782186937066717},"confidence":0.8643626570701599,"label":"7S","label_id":27},"h":11,"region_id":348,"roi_type":"7S","w":18,"x":71,"y":306},{"detection":{"bounding_box":{"x_max":0.5058819871030545,"x_min":0.43861405956666744,"y_max":0.5916590227433892,"y_min":0.5614026704639593},"confidence":0.851202130317688,"label":"3C","label_id":8},"h":19,"region_id":349,"roi_type":"3C","w":32,"x":211,"y":359},{"detection":{"bounding_box":{"x_max":0.39718757118564196,"x_min":0.36733270884552643,"y_max":0.28454704187135454,"y_min":0.27046848268014906},"confidence":0.5741612315177917,"label":"7S","label_id":27},"h":9,"region_id":350,"roi_type":"7S","w":14,"x":176,"y":173}],"resolution":{"height":640,"width":480},"timestamp":0}
