### ISSUE TITLE
How to Use “model-instance-id"

### ISSUE THREAD

**Issue by imjxy** [dlstreamer/dlstreamer#389]
software：openvino2023.0+dlstreamer2023.0
hardware：Intel(R) Xeon(R) Gold 6430+Intel ARC770& Intel FLEX170

The description of model-instance-id in the official documentation is as follows: "Identifier for sharing a loaded model instance between elements of the same type. Elements with the same model-instance-id will share all model and inference engine related properties."

We need to run multiple dlstreamer pipelines in parallel, where the models required for inference are the same. Therefore, we hope to utilize the model-instance-id attribute to reduce redundant model loading.

However, we are unsure about the usage of the model-instance-id. When attempting to perform multiple inferences within the same gst-launch process, as shown in the following pipeline, it becomes unresponsive and fails to run correctly:
```
gst-launch-1.0 filesrc location={} ! h264parse ! vaapih264dec ! video/x-raw\(memory:VASurface\) ! gvadetect model-instance-id=de0 model-proc={} labels-file={}  model={}  pre-process-backend=vaapi-surface-sharing   device=GPU.0  ! gvafpscounter starting-frame=10 ! fakesink async=true filesrc location={} ! h264parse ! vaapih264dec ! video/x-raw\(memory:VASurface\) ! gvadetect model-instance-id=de0 model-proc={} labels-file={}  model={} pre-process-backend=vaapi-surface-sharing  device=GPU.0  ! gvafpscounter starting-frame=10 ! fakesink async=true
```
When we set the same model-instance-id for the model in multiple gst-launch processes and run these pipelines in parallel, we observe that the GPU memory does not decrease as expected.

Therefore, we would like to inquire about the specific functionality of model-instance-id and how to configure it within the pipeline.

**Comment by brmarkus** [comment]
I was searching for "model-instance-id" in this repo to see more examples and documentation (https://github.com/search?q=repo%3Adlstreamer%2Fdlstreamer%20model-instance-id&type=code).

Can you try with the simpliest possible pipeline like using e.g. "samples/gstreamer/benchmark/benchmark_two_models.sh", starting with one of the given sample models (using simple default model-proc files)?

Are you sure your used video-files (yes, both are decoded via `vaapih264dec`) result in the same format?
Because with the above search I saw an error message text saying

> All image formats and memoryType for the same model-instance-id in multichannel mode must be the same.

**Comment by imjxy** [comment]
hi @brmarkus, thanks for your advice.

I have tried using the '&' symbol to connect multiple pipelines, where each pipeline has the same model with model-instance-id set to the same value. As mentioned earlier, "When we set the same model-instance-id for the model in multiple gst-launch processes and run these pipelines in parallel, we observe that the GPU memory does not decrease as expected." 

However, the GPU memory usage is similar to when model-instance-id is not set. Therefore, I feel that it is not having the intended effect.

**Comment by brmarkus** [comment]
Do you see both scripts, `benchmark_two_models.sh` and `benchmark_one_model.sh`, running - starting with the default values, default models, default video files, to make sure the pipelines are working, parameters and videos are "compatible", for consistency-check?
Do you see a correlation with the used memory consumption between running "one model" and "two models"?
Would you have a chance to compare with running on the CPU?

**Comment by akwrobel** [comment]
Closed due to age an no further response from submitter
