### ISSUE TITLE
How to install packages with sudo inside the docker container intel/dlstreamer:latest

### ISSUE THREAD

**Issue by OrkhanHI** [dlstreamer/dlstreamer#390]
Hi,

I am trying to install packages inside the docker container, but it is asking for a password.

**Comment by brmarkus** [comment]
How do you start the Docker container?

Can you try temporarily running with root user like `docker run -it -u 0 --rm ...` and install packages?
Or creating your own Dockerfile, based on a DL-Streamer and add your individual packages?

**Comment by akwrobel** [comment]
@OrkhanHI Can you please share your docker container information?  It looks like this may be a permissions issue, but we can't tell with out more information.

**Comment by navyverma** [comment]
@brmarkus  I have to update dlstreamer  binaries inside container and that gives **"Permission denied"** error. So, tell me about the user(dlstreamer) info or root info of the container so that I can update dlstreamer binaries.

**Comment by navyverma** [comment]
I am using your own Dockerfile, but based on a DL-Streamer image.
