### ISSUE TITLE
Running gvawatermark on the GPU

### ISSUE THREAD

**Issue by eslam-ahmed-khair** [dlstreamer/dlstreamer#391]
Hello,

I'm running using the development docker image `intel/dlstreamer:devel` and tried running the `gvawatermark` element with `device=GPU` but I got the following error:
```
ERROR: from element /GstPipeline:pipeline0/GstGvaWatermark:gvawatermark0/GstGvaWatermarkImpl:gvawatermarkimpl0: Could not initialize
Additional debug info:
/home/dlstreamer/dlstreamer/src/monolithic/gst/elements/gvawatermark/gstgvawatermarkimpl.cpp(310): gst_gva_watermark_impl_set_caps (): /GstPipeline:pipeline0/GstGvaWatermark:gvawatermark0/GstGvaWatermarkImpl:gvawatermarkimpl0:
Cannot create watermark instance. 
GPU Watermark initialization failed: Could not open shared object libgpurenderer.so error: libgpurenderer.so: cannot open shared object file: No such file or directory. Seems DPC++ dependency is not installed. Please follow installation guide: https://dlstreamer.github.io/get_started/install/install_guide_ubuntu.html#step-7-install-intel-oneapi-dpc-c-compiler-optional
ERROR: pipeline doesn't want to preroll.
```
Then I installed the missing dependency from [here](https://dlstreamer.github.io/get_started/install/install_guide_ubuntu.html#step-7-install-intel-oneapi-dpc-c-compiler) and sourced the environment but I still could not locate the missing library `libgpurenderer.so` nor the element worked on the GPU.

I also tried the docker image `dlstreamer/dlstreamer:dpcpp` but it has the same issue.

Thanks in advance.

**Comment by akwrobel** [comment]
This usage has been deprecated, pleases see the notice and replacement here: https://github.com/dlstreamer/dlstreamer/releases/tag/2022.2-release
