### ISSUE TITLE
Debian file location for DL streamer 2022.3

### ISSUE THREAD

**Issue by aks473** [dlstreamer/dlstreamer#393]
Documentation reference for installing DL streamer is always referring to the latest version of the dlstreamer. Where can I download the 2022.3 version? Even the 2022 git branch doesn't provide link for the same.

**Comment by pk1d3v** [comment]
Hello @aks473,

You can try following:
```sh
curl -fsSL https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB | sudo gpg --dearmor --output /usr/share/keyrings/intel-sw-products.gpg
echo "deb [arch=amd64 signed-by=/usr/share/keyrings/intel-sw-products.gpg] https://apt.repos.intel.com/openvino/2022 jammy main" | sudo tee /etc/apt/sources.list.d/intel-openvino-2022.list
```

**Comment by aks473** [comment]
Thanks @pk1d3v for the response, I have been using the same command since Saturday and it wasn't working but today it's working. Not sure whether there was a server outage on Intel's apt link. 
Intel should at least update the release notes and documentation with specific instructions for specific versions. It's difficult to track and try, especially when dlstreamer is an integral part of a product. We use it extensively.
