### ISSUE TITLE
Custom YoloV5m Accuracy Drop in dlstreamer with model proc 

### ISSUE THREAD

**Issue by shekarneo** [dlstreamer/dlstreamer#394]
Hi i have followed this [yolov5 dlstreamer](https://dlstreamer.github.io/dev_guide/yolov5_model_preparation.html) guild to convert my two class yolov5m model to IR format.

I have the following issues with the accuracy.
1) When i use yolov5 `export.py` to convert IR format and use `detect.py` the results are same as .pt inference.
2) When i use [yolov5 dlstreamer](https://dlstreamer.github.io/dev_guide/yolov5_model_preparation.html) to convert IR format and use dlstreamer pipeline with model proc the accuracy is bounding boxes are not proper getting multiple bboxes for single object.

Please find the pipeline and model proc details.

MODEL_PATH=../models/yolov5_head_openvino_model/INT8/yolov5m.xml
PROC_PATH=../models/yolov5_head_openvino_model/crowdhuman_yolov5.json

cmd="filesrc location=../videos/NVR_ch18.mp4 ! decodebin \
      ! videoconvert ! video/x-raw, format=BGR \
      ! queue ! gvadetect model=$MODEL_PATH model-proc=$PROC_PATH device=CPU  \
      ! queue ! gvatrack \
      ! queue ! gvawatermark ! queue ! videoconvert ! fpsdisplaysink sync=false"
      
gst-launch-1.0 $cmd

## Model Proc:

{
    "json_schema_version": "2.2.0",
    "input_preproc": [
        {
        "format": "image",
        "layer_name": "images",
        "params": {
                "resize": "aspect-ratio",
                "color_space": "BGR",
                "reverse_channels": true
            }
        }
    ],
    "output_postproc": [
        {
            "converter": "yolo_v5",
            "output_sigmoid_activation": true,
            "do_cls_softmax": true,
            "iou_threshold": 0.2,
            "nms_threshold": 0.2,
            "bbox_number_on_cell": 3,
            "cells_number": 20,
            "classes": 2,
            "labels": ["person", "head"],
            "anchors": [
                10.0,
                13.0,
                16.0,
                30.0,
                33.0,
                23.0,
                30.0,
                61.0,
                62.0,
                45.0,
                59.0,
                119.0,
                116.0,
                90.0,
                156.0,
                198.0,
                373.0,
                326.0
            ],
            "masks": [
                6,
                7,
                8,
                3,
                4,
                5,
                0,
                1,
                2
            ]
        }
    ]
}

**Comment by brmarkus** [comment]
Can you maybe show a sample/screenshot?
Your model, your input-material, your (re-)trained models might require different tuning for NMS-, IOU-, confidence-level.
The script `detect.py` (see e.g. https://github.com/ultralytics/yolov5/blob/master/detect.py#L61) sets default values - have you changed them via command-line?
Your example of th emodel-proc shows different values - you might just experiment changing them in the proc-config:
```
"iou_threshold": 0.2,
"nms_threshold": 0.2,
"bbox_number_on_cell": 3,
```

**Comment by shekarneo** [comment]
@brmarkus  with these `"iou_threshold": 0.2` values at least i am able to remove few multiple bboxes.

if i use default `"iou_threshold":0.4` i am getting below result
<img width="1285" alt="image" src="https://github.com/dlstreamer/dlstreamer/assets/25033310/00aaf42d-8e21-42d4-8a93-d3dc1d253cc1">


and the same from detect.py 
![vlcsnap-2023-12-06-16h46m07s104](https://github.com/dlstreamer/dlstreamer/assets/25033310/f9bd7516-ad8e-4b17-baaf-23cd0d8f2678)


`"bbox_number_on_cell": 3,` this values i have not changed.

**Comment by akwrobel** [comment]
Hi @shekarneo please try adjusting you nms_threshold

**Comment by shekarneo** [comment]
@akwrobel thanks for your response, i have tried different `nms_threshold` from 0.1 to 0.9 this did not affect anything, but if i lower the `iou_threshold` to 0.2 i can reduce multiple bboxes for the single object, but still facing the bboxes drawing imperfectly like larger bboxes and smaller than the object.

**Comment by pmalatyn** [comment]
we plan to fix this issue in upcoming release, please stay tuned

**Comment by pmalatyn** [comment]
2024.0.1 version is released, it fixed this issue, if you will see any problems still please reopen this issue or create new one.
