### ISSUE TITLE
Creating a Tensor Object in Python from a List like structure

### ISSUE THREAD

**Issue by mschreil** [dlstreamer/dlstreamer#395]
Hello, 
I have seen that there were already ambitions to create a Tensor object from a list with the python interface. Are there any plans to fix this part of the code? 

https://github.com/dlstreamer/dlstreamer/blob/cd73cb144f834502e454359d61d283ad230f7bca/python/gstgva/tensor.py#L332-L340

More general, what I want to do is to use the gavinference element to get the raw model output tensors, post-process them and write them back to the Gstreamer pipeline as part of the RegionOfIntreset Object in the VideoFrame, such that my other elements can directly use the post-processed tensor. 

Or are there any workarounds / suggestions how to accomplish this in python. I am kind of stuck here. Would be really appreciated if someone could help me out.

**Comment by mschreil** [comment]
anyone who can help here?

**Comment by pmalatyn** [comment]
@mschreil can you please check if it works or you on newest version of DL Streamer (2024.0)?

**Comment by mschreil** [comment]
@pmalatyn 
https://github.com/dlstreamer/dlstreamer/blob/v2024.0/python/gstgva/tensor.py#L333-L341

The code is still commented and a `NotImplementedError` is raised. So no it is not working on DLStreamer 2024-0 with this approach. 

Or is there any workaround?

**Comment by pmalatyn** [comment]
thanks for fast response, you are right, code is commented so we did not improve that part yet, so far such use case was also not planned to be implemented. Let me check with the team how (if) we can help here.

**Comment by pmalatyn** [comment]
@mschreil  ...plus can you give us more background about your use case? Do you want to import unsupported model, do inference with DL Streamer and export it?

**Comment by mschreil** [comment]
@pmalatyn: sorry for the late response. 

Here is some more information: 
You already guessed it right. I am using RTMdet which is currently not supported. RTMdet is able to predict instance segmentation masks. However, they need some post-processing. After inference, I would like to apply the post-processing to the masks and write them back to the buffer such that they can be used by other elements.

**Comment by pmalatyn** [comment]
@mschreil thanks! it looks like feature request for me no a bug, we will need to discuss how and when we can implement it. In the meantime are you able to share your pipeline? It would be easiest way for us to understand exactly in details your use case

**Comment by pmalatyn** [comment]
as for now it is not planned for releases in 2024 year. Closing.
