### ISSUE TITLE
Installation Error DLStreamer - Both Debian Packages and Compile from Sources

### ISSUE THREAD

**Issue by Sharan-Sundar** [dlstreamer/dlstreamer#397]
Hi, I have been using DLStreamer and OpenVINO for the past 3 years and have a working codebase dependent on it. It is an integral part of my product. However, recently when I tried to install on a new device, I am facing errors. I have been working on this for the past 1 week and I am not sure where the problem is. 
I am using `Ubuntu 22.04.3 LTS` on a `Intel Celeron(R) N4120` with 8GB RAM. These are the errors I am facing while installing DLStreamer.

[1. Install from Debian Packages](https://dlstreamer.github.io/get_started/install/install_guide_ubuntu.html#option-1-install-intel-dl-streamer-pipeline-framework-from-debian-packages)
When I ran 
`wget $(wget -q -O - https://api.github.com/repos/dlstreamer/dlstreamer/releases/latest |  jq -r '.assets[] | select(.name | contains (".deb")) | .browser_download_url') `
I get 26 packages as shown - 
![Screenshot from 2023-12-15 21-11-07](https://github.com/dlstreamer/dlstreamer/assets/43034406/4f6660b7-4951-4523-99c4-f058b5c48d52)

But when I try to install with `sudo apt install ./*.deb`, I get the following error - 
![Screenshot from 2023-12-15 21-13-49](https://github.com/dlstreamer/dlstreamer/assets/43034406/1f3d2366-6fc1-432a-a9b5-10a9a8610489)
I am not sure how to proceed with this.

[2.Compile from Source](https://dlstreamer.github.io/get_started/install/install_guide_ubuntu.html#id3)
When I compile from source following the exact instructions in the install_guide page, I get stuck in `Step 9 - Build Intel DL Streamer Pipeline Framework`. 
Here, `source /opt/intel/dlstreamer/gstreamer/setupvars.sh` returns an error because in `/opt/intel/`, there is no such folder called `dlstreamer` itself. I remember it used to get automatically created in the previous releases. I am not sure where I am going wrong. 

Since the support of my product is at stake, I request you to kindly respond as soon as possible. I need help installing OpenVINO and DLStreamer on Ubuntu 22.04.3 LTS. It would help if you can give me access to the Installation Guide of previous DLStreamer releases as well as I have been using those only for the past 3 years. 
Looking forward to your response. Thanks.

**Comment by Sharan-Sundar** [comment]
Just an update. Getting this new error while I am trying to debug - 
![Screenshot from 2023-12-16 14-46-10](https://github.com/dlstreamer/dlstreamer/assets/43034406/1b689157-76d9-46a4-8f93-7f6f97870890)

**Comment by Sharan-Sundar** [comment]
Yep I have been erasing and reinstalling from scratch multiple times over the last week. I have tried both on Ubuntu 20 and Ubuntu 22. Somehow, it ends up in some random error everytime. Have been trying to debug.

Yes I tried `sudo apt-get install -f` and then using dpgk like `sudo dpkg -i ./*.deb` and am still getting the same. 
Docker I haven't tried yet because I am new to it and am not sure how much time it will take to migrate my existing product codebase to docker. I would prefer to have it without dockerizing.

**Comment by Sharan-Sundar** [comment]
Yeah I understand. But I am erasing the disk and reinstalling Ubuntu to get a "clean" environment. Docker is not an bad option either I agree.

Update - This is what I get when I try to install on a clean Ubuntu 20. This is what I am trying out now -
![Screenshot from 2023-12-16 16-29-03](https://github.com/dlstreamer/dlstreamer/assets/43034406/9b2a4d3b-91d4-4982-afd9-06cddec9c646)

**Comment by Sharan-Sundar** [comment]
Yeah so only this comment is on Ubuntu 20. Rest of the comments are from Ubuntu 22 only.

Yep I think they did. Also, I have installed multiple times over the last 3 years starting from OpenVINO 2019 to 2023. But this is the first time, I am completely stuck.

**Comment by Sharan-Sundar** [comment]
Do you have any installation guide for DLStreamer on Ubuntu 20? Or can we conclude that DLStreamer has offically stopped support for it?

**Comment by Sharan-Sundar** [comment]
> DL-Streamer defined Ubuntu 22 as the "supported version" (see https://dlstreamer.github.io/get_started/install/install_guide_ubuntu.html).
> 
> Your first installations 3 years ago - you might have installed OpenVINO first and then DL-Streamer? (old versions even came with gstreamer and OpenCV install scripts)

Yeah but here you yourself say it for Ubuntu22. And yeah when I tried it on Ubuntu20, I got even more errors. So I don't think it is a good idea to try Ubuntu20. I will continue working on Ubuntu22.

**Comment by akwrobel** [comment]
The issue you are seeing is due to a security issue found in Ubuntu and is related to their Debian packaged
https://launchpad.net/ubuntu/+source/gst-plugins-bad1.0/1.20.3-0ubuntu1.1
The chain is broken and a new release will be required to fix this issue.

**Comment by Sharan-Sundar** [comment]
Alright so till then, I will try to test without gst-plugins-bad.

**Comment by darshanraj-intc** [comment]
Hi,

any ETA on fixing this? Or a workaround to use the toolset. 

```

The following packages have unmet dependencies:
 intel-dlstreamer-gst-plugins-bad : Depends: libgstreamer-plugins-bad1.0-0 (= 1.20.3-0ubuntu1) but 1.20.3-0ubuntu1.1 is to be installed
E: Unable to correct problems, you have held broken packages.

```

https://dlstreamer.github.io/index.html is used often by external folks. Please suggest an ETA for the fix or at least a workaround on Ubuntu22

Thanks.
Darshan

**Comment by deshpanda** [comment]
Trying to install latest dlstreamer in a docker container where I had previously installed OpenVINO 2024.3 on Ubuntu22.04 and I am still facing this error while installing through debian packages

```
The following packages have unmet dependencies:
 intel-dlstreamer-gst-plugins-base : Depends: liborc-0.4-dev-bin:any (= 1:0.4.32-2)
E: Unable to correct problems, you have held broken packages.
```

**Comment by pmalatyn** [comment]
hello,
thanks for highlighting this issue to us. We are aware of the problem and working on fixing it, looks like Ubuntu was updated few days ago and this impacted our release, will update you when we will have solution ready.

**Comment by pmalatyn** [comment]
Solution is ready, affected packages are updated. You can try if it works for you.

**Comment by deshpanda** [comment]
Thank you, it works now

**Comment by pmalatyn** [comment]
great :) closing the issue then
