### ISSUE TITLE
yolox support

### ISSUE THREAD

**Issue by vtpl1** [dlstreamer/dlstreamer#406]
Is the yolox supported in dlstreamer?

https://github.com/Megvii-BaseDetection/YOLOX

omz_downloader downloads yolox-tiny model but there is no suitable model_proc file

**Comment by pmalatyn** [comment]
hello, 

thanks for your question. We are planning to add official support for this model in upcoming quarter. 
Until that you can check: 
- https://docs.openvino.ai/2024/notebooks/230-yolov8-object-detection-with-output.html and 
- https://docs.ultralytics.com/integrations/openvino/

**Comment by vtpl1** [comment]
Hi @pmalatyn ,
Thank you for the update.
You can chechout the PR [#408](https://github.com/dlstreamer/dlstreamer/pull/408)

**Comment by pmalatyn** [comment]
hello 
thank you for your contribution, 
yolox support will be added in next release coming very soon, but feel free to contribute in the future :)
