### ISSUE TITLE
ffmpeg_openvino/decode_resize_inference build error

### ISSUE THREAD

**Issue by KiwiHana** [dlstreamer/dlstreamer#414]
```
dlstreamer/samples/ffmpeg_openvino/cpp/decode_resize_inference$ ./build_and_run.sh /home/test/kiwi/test_1080p_15.mp4 /home/test/kiwi/yolov5s_openvino_model/yolov5s.xml
CMake Warning (dev) in CMakeLists.txt:
  No project() command is present.  The top-level CMakeLists.txt file must
  contain a literal, direct call to the project() command.  Add a line of
  code such as

    project(ProjectName)

  near the top of the file, but after cmake_minimum_required().

  CMake is pretending there is a "project(Project)" command on the first
  line.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- The C compiler identification is GNU 11.4.0
-- The CXX compiler identification is GNU 11.4.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.2")
-- Checking for modules 'libavformat;libavcodec;libswscale;libavutil'
--   Found libavformat, version 60.16.100
--   Found libavcodec, version 60.31.102
--   Found libswscale, version 7.5.100
--   Found libavutil, version 58.29.100
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE
-- Looking for CL_VERSION_2_2
-- Looking for CL_VERSION_2_2 - found
-- Found OpenCL: /usr/lib/x86_64-linux-gnu/libOpenCL.so (found version "2.2")
-- Checking for module 'dl-streamer'
--   Found dl-streamer, version 2.0.0
-- Configuring done
-- Generating done
-- Build files have been written to: /home/test/intel/dl_streamer/samples/ffmpeg_openvino_decode_resize_inference/build
[ 50%] Building CXX object CMakeFiles/ffmpeg_openvino_decode_resize_inference.dir/decode_resize_inference.cpp.o
In file included from /opt/intel/openvino_2024.0/runtime/include/openvino/runtime/intel_gpu/ocl/ocl_wrapper.hpp:50,
                 from /opt/intel/openvino_2024.0/runtime/include/openvino/runtime/intel_gpu/ocl/ocl.hpp:17,
                 from /opt/intel/openvino_2024.0/runtime/include/openvino/runtime/intel_gpu/ocl/va.hpp:23,
                 from /home/test/kiwi/dlstreamer/samples/ffmpeg_openvino/cpp/decode_resize_inference/decode_resize_inference.cpp:20:
/usr/include/CL/cl2.hpp:18:151: note: ‘#pragma message: cl2.hpp has been renamed to opencl.hpp to make it clear that it supports all versions of OpenCL. Please include opencl.hpp directly.’
   18 | encl.hpp to make it clear that it supports all versions of OpenCL. Please include opencl.hpp directly.")
      |                                                                                                        ^

[100%] Linking CXX executable ffmpeg_openvino_decode_resize_inference
[100%] Built target ffmpeg_openvino_decode_resize_inference
terminate called after throwing an instance of 'ov::AssertFailure'
  what():  Check 'it != m_names.end()' failed at src/core/src/layout.cpp:203:
W dimension index is not defined

./build_and_run.sh: line 32: 94029 Aborted                 (core dumped) "${BUILD_DIR}"/${EXE_NAME} -i "${VIDEO_FILE}" -m "${MODEL}"

```

**Comment by KiwiHana** [comment]
```
$/home/test/intel/dl_streamer/samples/ffmpeg_openvino_decode_resize_inference/build/ffmpeg_openvino_decode_resize_inference -i /home/test/kiwi/test_1080p_15.mp4 -m /home/test/kiwi/yolov5s_openvino_model/yolov5s.xml
terminate called after throwing an instance of 'ov::AssertFailure'
  what():  Check 'it != m_names.end()' failed at src/core/src/layout.cpp:203:
W dimension index is not defined

Aborted (core dumped)

```

**Comment by KiwiHana** [comment]
> Does it work with another model, like the default model `face-detection-adas-0001` from the build-script, "https://github.com/dlstreamer/dlstreamer/blob/master/samples/ffmpeg_openvino/cpp/decode_resize_inference/build_and_run.sh#L9C33-L9C57"?

```
:~/intel/dl_streamer/samples/ffmpeg_openvino_decode_resize_inference/build$ ./ffmpeg_openvino_decode_resize_inference -i /home/test/kiwi/test_1080p_15.mp4 -m /home/test/kiwi/face-detection-adas-0001/FP32/face-detection-adas-0001.xml
model /home/test/kiwi/face-detection-adas-0001/FP32/face-detection-adas-0001.xml
read model
ffmpeg_openvino_decode_resize_inference: /home/dlstreamer/dlstreamer/src/vaapi/vaapi_batch_proc/vaapi_batch_proc.cpp:65: virtual dlstreamer::FramePtr dlstreamer::VaapiBatchProc::process(dlstreamer::FramePtr): Assertion `false' failed.
Aborted (core dumped)
```

**Comment by pmalatyn** [comment]
hello, @brmarkus you are right this part is part of Architecture 2.0 which is under development now.
@KiwiHana we can fix your issue in release planned at the end of March. Will this help? Plus 2nd question - anything else from Architecture 2.0 that you are interested in?

**Comment by KiwiHana** [comment]
> hello, @brmarkus you are right this part is part of Architecture 2.0 which is under development now. @KiwiHana we can fix your issue in release planned at the end of March. Will this help? Plus 2nd question - anything else from Architecture 2.0 that you are interested in?

Thanks @brmarkus and @pmalatyn ! March goes by, do you mean fix this issue on May?
Also, we are interested in more image preprocess in ffmpeg pipeline, like  color conversion, clip, fill etc.

**Comment by pmalatyn** [comment]
yeah May not March ;) 
About your use cases are you able to share user stories how you would like to use it? Preferably in a form like: "As a user I want to ..." ?

**Comment by pmalatyn** [comment]
sadly we were not able to finish this item, it is now planned for June release, apologies for that

**Comment by HooJE90** [comment]
Hi, we are having the same problem too.
May i know is this issue have the solution already?

(.env3) ubuntu@ubuntu-Not-Specified:~/intel/dlstreamer_gst/samples/ffmpeg_openvino/cpp/decode_resize_inference$ ./ffmpeg_openvino_decode_resize_inference -i /home/ubuntu/Desktop/123.mp4 -m /home/ubuntu/intel/face-detection-0205/FP32/face-detection-0205.xml
ffmpeg_openvino_decode_resize_inference: /home/dlstreamer/dlstreamer/src/vaapi/vaapi_batch_proc/vaapi_batch_proc.cpp:65: virtual dlstreamer::FramePtr dlstreamer::VaapiBatchProc::process(dlstreamer::FramePtr): Assertion `false' failed.
Aborted (core dumped)
(.env3) ubuntu@ubuntu-Not-Specified:~/intel/dlstreamer_gst/samples/ffmpeg_openvino/cpp/decode_resize_inference$ ./ffmpeg_openvino_decode_resize_inference /home/ubuntu/Desktop/123.mp4 /home/ubuntu/intel/face-detection-0205/FP32/face-detection-0205.xml
terminate called after throwing an instance of 'std::runtime_error'
  what():  main: Error on: !FLAGS_i.empty() && !FLAGS_m.empty()
Aborted (core dumped)

**Comment by pmalatyn** [comment]
hello,

yes we have it in plans, atm code is compiling but we are still working to fix decode_resize_inference sample. It is quite complex task related to Arch 2.0 so sorry for delay but it will again slip to July release. But work is ongoing.

**Comment by zyitom** [comment]
Will it be fixed on July?

**Comment by pmalatyn** [comment]
hello, 
sorry for late response, we just released 2024.1.1 version - please check it, it should be fixed

**Comment by pmalatyn** [comment]
fix delivered, no feedback, closing

**Comment by khairulintel** [comment]
Here is how you can build the sample code:

1. Follow step by step to this guide: https://dlstreamer.github.io/dev_guide/advanced_install/advanced_install_guide_compilation.html

2. Go to: 
https://github.com/open-edge-platform/edge-ai-libraries/blob/main/libraries/dl-streamer/CMakeLists.txt
uncomment `#add_subdirectory` in 
https://github.com/open-edge-platform/edge-ai-libraries/blob/main/libraries/dl-streamer/CMakeLists.txt#L206C1-L211C8
 
 3. Go to:
https://github.com/open-edge-platform/edge-ai-libraries/blob/main/libraries/dl-streamer/src/CMakeLists.txt#L9
and uncomment` #add_subdirectory(ffmpeg)`
        
 4. Next, in include/dlstreamer/base/blocking_queue.h
https://github.com/open-edge-platform/edge-ai-libraries/blob/main/libraries/dl-streamer/include/dlstreamer/base/blocking_queue.h#L31

`_push_condition.wait(lock, [=] { return !_queue.empty(); }); --> _push_condition.wait(lock, [this] { return !_queue.empty(); });`

Change the `[=]` symbol to `[this]`

5. Open a new terminal and git clone https://github.com/dlstreamer/dlstreamer.git  in the /home/$USER/

6. Go back to the original terminal, while in the python3venv virtual environment (activated during Step 1) execute this: `export DLSTREAMER_DIR=/home/${USER}/your_dlstreamer_folder
`
7. Then go to /home/$USER/edge-ai-libraries/libraries/dl-streamer/ , then execute the cmake command: `cmake -DENABLE_SAMPLES=ON`, then `make`

You will get 100% built message like this:

![Image](https://github.com/user-attachments/assets/099afed0-aa19-4a14-a0ae-1cae38cb5341)

Find the build sample using this command:
`find . -type f -name ffmpeg_openvino_decode_resize_inference`

![Image](https://github.com/user-attachments/assets/1dec14d7-ab3e-4a22-b413-363b4b9be3f6)

8. Run inference like this, and get results like below. I recommend downloading videos from Pexels for high def videos. 

![Image](https://github.com/user-attachments/assets/a326dea4-ffd7-4de3-9667-e93dc96ad350)

**Comment by khairulintel** [comment]
Sure, I will create a PR
