### ISSUE TITLE
cant run against Efficientnet-b0 due to model exceeds allowable size of 10MB

### ISSUE THREAD

**Issue by jemata** [dlstreamer/dlstreamer#415]
Running DL streamer using the Docker option on a Serpent Canyon Board and using Ubuntu 22.04 

Running the following command against my real Sense camera and replaced the classification model with efficientnet that came with the models download, i get an error that model exeeds allowable size of 10MB....

gst-launch-1.0 v4l2src device=/dev/video4 ! video/x-raw,width=320,height=240,framerate=30/1 ! videoconvert !  gvadetect model=${DETECTION_MODEL} model_proc=${DETECTION_MODEL_PROC} device=CPU ! queue ! gvaclassify model=${OBJECT_CLASSIFICATION_MODEL} model-proc=${OBJECT_CLASSIFICATION_MODEL_PROC} device=CPU object-class=vehicle ! queue ! gvawatermark ! videoconvert ! fpsdisplaysink video-sink=xvimagesink sync=false

![image](https://github.com/dlstreamer/dlstreamer/assets/17582122/da378737-cbde-4d00-94a0-e1135b7e632f)

**Comment by jemata** [comment]
yes that is correct, it is the path to the model, where would the .json files be?


dlstreamer@vision-checkout:~/temp/public/efficientnet-b0$ ls
FP16  FP32  efficientnet-b0
dlstreamer@vision-checkout:~/temp/public/efficientnet-b0$ cd FP32/
dlstreamer@vision-checkout:~/temp/public/efficientnet-b0/FP32$ ls
efficientnet-b0.bin  efficientnet-b0.xml
dlstreamer@vision-checkout:~/temp/public/efficientnet-b0/FP32$ pwd
/home/dlstreamer/temp/public/efficientnet-b0/FP32
dlstreamer@vision-checkout:~/temp/public/efficientnet-b0/FP32$ echo $MODEL_PATH

dlstreamer@vision-checkout:~/temp/public/efficientnet-b0/FP32$ echo $MODELS_PATH
/home/dlstreamer/temp/
dlstreamer@vision-checkout:~/temp/public/efficientnet-b0/FP32$ pwd
/home/dlstreamer/temp/public/efficientnet-b0/FP32
dlstreamer@vision-checkout:~/temp/public/efficientnet-b0/FP32$

**Comment by jemata** [comment]
i cant find the efficienet one under dlstreamer@vision-checkout:~/dlstreamer/samples/gstreamer/model_proc/intel$ pwd
/home/dlstreamer/dlstreamer/samples/gstreamer/model_proc/intel

**Comment by tjanczak** [comment]
efficientnet is a simple classification model, it does not require dedicated model-proc file; please use the following params:

gvaclassify inference-region=full-frame device=CPU model=<path_to_models>/efficientnet-b0/FP32/efficientnet-b0.xml model-proc=<path_to_model_proc>/samples/gstreamer/model_proc/public/preproc-aspect-ratio.json labels-file=<path_to_labels>/samples/labels/imagenet_2012.txt ! queue ! ...

**Comment by jemata** [comment]
added the efficient classification option to my working yolov8 detection dlstreamer cmd and i am getting the following error

gst-launch-1.0 v4l2src device=/dev/video10 ! video/x-raw,width=320,height=240,framerate=30/1 ! videoconvert ! gvadetect model=${OBJECT_DETECTION_MODEL} model_proc=${OBJECT_DETECTION_MODEL_PROC} device=CPU ! queue ! gvaclassify inference-region=full-frame device=CPU model=${OBJECT_CLASSIFICATION_MODEL} model-proc=/home/dlstreamer/dlstreamer/samples/gstreamer/model_proc/public/preproc-aspect-ratio.json labels-file=/home/dlstreamer/dlstreamer/samples/labels/imagenet_2012.txt ! queue ! gvawatermark ! videoconvert ! fpsdisplaysink video-sink=xvimagesink sync=false
Setting pipeline to PAUSED ...
Pipeline is live and does not need PREROLL ...
Got context from element 'vaapipostproc1': gst.vaapi.Display=context, gst.vaapi.Display=(GstVaapiDisplay)"\(GstVaapiDisplayGLX\)\ vaapidisplayglx0", gst.vaapi.Display.GObject=(GstObject)"\(GstVaapiDisplayGLX\)\ vaapidisplayglx0";
Pipeline is PREROLLED ...
Setting pipeline to PLAYING ...
New clock: GstSystemClock
X Error of failed request:  BadShmSeg (invalid shared segment parameter)
  Major opcode of failed request:  130 (MIT-SHM)
  Minor opcode of failed request:  2 (X_ShmDetach)
  Segment id in failed request:  0x2c00004
  Serial number of failed request:  67
  Current serial number in output stream:  68

**Comment by jemata** [comment]
ok after several tries and disconnecting connecting the real sense cameras it is working
<img width="848" alt="image" src="https://github.com/dlstreamer/dlstreamer/assets/17582122/3830be05-55ea-4144-a3ed-e3623e2f4a2a">

Not sure why i need to unplug/plug cameras for dlstreamer to work again as i was getting device no found......has anyone seen this issue?

**Comment by jemata** [comment]
what is the correct way to end the stream? as I closed the "gst-launch 1.0" window and now re-running same cmd i get
gst-launch-1.0 v4l2src device=/dev/video4 ! video/x-raw,width=320,height=240,framerate=30/1 ! videoconvert ! gvadetect model=${OBJECT_DETECTION_MODEL} model_proc=${OBJECT_DETECTION_MODEL_PROC} device=CPU ! queue !     gvaclassify inference-region=full-frame device=CPU model=${OBJECT_CLASSIFICATION_MODEL} model-proc=/home/dlstreamer/dlstreamer/samples/gstreamer/model_proc/public/preproc-aspect-ratio.json labels-file=/home/dlstreamer/dlstreamer/samples/labels/imagenet_2012.txt ! queue ! gvawatermark ! videoconvert ! fpsdisplaysink video-sink=xvimagesink sync=false
Setting pipeline to PAUSED ...
Pipeline is live and does not need PREROLL ...
Got context from element 'vaapipostproc1': gst.vaapi.Display=context, gst.vaapi.Display=(GstVaapiDisplay)"\(GstVaapiDisplayGLX\)\ vaapidisplayglx0", gst.vaapi.Display.GObject=(GstObject)"\(GstVaapiDisplayGLX\)\ vaapidisplayglx0";
Pipeline is PREROLLED ...
Setting pipeline to PLAYING ...
New clock: GstSystemClock
ERROR: from element /GstPipeline:pipeline0/GstV4l2Src:v4l2src0: Device '/dev/video4' is busy
Additional debug info:
../sys/v4l2/gstv4l2object.c(4145): gst_v4l2_object_set_format_full (): /GstPipeline:pipeline0/GstV4l2Src:v4l2src0:
Call to S_FMT failed for YUYV @ 320x240: Device or resource busy
Execution ended after 0:00:00.159668979
ERROR: from element /GstPipeline:pipeline0/GstV4l2Src:v4l2src0: Internal data stream error.
Setting pipeline to NULL ...
Additional debug info:
../libs/gst/base/gstbasesrc.c(3132): gst_base_src_loop (): /GstPipeline:pipeline0/GstV4l2Src:v4l2src0:
streaming stopped, reason not-negotiated (-4)
Freeing pipeline ...
(openvino_env) dlstreamer@vision-checkout:~$

**Comment by jemata** [comment]
CTRL+C works and i am able to re-start the stream; however noticing issues with the real sense cameras, when 1 connected it works ok however when 2 or more it is getting flaky

**Comment by jemata** [comment]
closing this issue as i am able to run efficienet

**Comment by jemata** [comment]
closing as issue has been resolved
