### ISSUE TITLE
cant run 2 dlstreamer cmds side to side on same docker using 2 different camera feeds

### ISSUE THREAD

**Issue by jemata** [dlstreamer/dlstreamer#419]
Running DL streamer using the Docker option on a Serpent Canyon Board and using Ubuntu 22.04

Application objective: run  more than 2 dlstreamer side to side each targeting a different camera.

follow-on discussion from Issue https://github.com/dlstreamer/dlstreamer/issues/416#issuecomment-2088815170 

try running these 2 cmds  and got the following

**gst-launch-1.0 videotestsrc ! xvimagesink 2>&1 > /dev/null &
gst-launch-1.0 videotestsrc pattern=ball ! xvimagesink 2>&1 > /dev/null &**

![image](https://github.com/dlstreamer/dlstreamer/assets/17582122/d896636d-9156-482a-aac0-0175c8d8867b)

**Comment by jemata** [comment]
i get this when i tried the autoviediosink instead

<img width="823" alt="image" src="https://github.com/dlstreamer/dlstreamer/assets/17582122/4d88431e-fb1e-44af-bf8e-035b0b227848">

**Comment by jemata** [comment]
so yes on the direct host i can run both but not through remote desktop
I will now run both of my DLstreamer cmds and see how it goes...

**Comment by jemata** [comment]
I have updated realsense camera FW, i see both cameras when running lspci however, gstreamer keeps complaining that 
it cant indentify devices
![image](https://github.com/dlstreamer/dlstreamer/assets/17582122/e66ef615-cc3f-4066-9eb7-32a3bb2ffd28)

![image](https://github.com/dlstreamer/dlstreamer/assets/17582122/58da0009-343d-408e-93c0-0d09c14fa0eb)

I have even run ffplay against camera 16 with no issues i see video on it

**Comment by jemata** [comment]
when i directly log into the system w.o logging remote i am able to run and see  stripe-test-pattern and another with the bouncing ball; 
Need to add this info within another Tutorial example on how to run 2 DL Streamers side to side

I am still dealing with Real sense issues when it does not detect one of the cameras for the other pipeline to work

**Comment by tbujewsk** [comment]
Hi Jhoanna,

Thank you for your question.

Here is an example cmdline for 2 USB cameras.
With the next Intel Deep Learning Streamer release there should be added multi-streams sample.

You must install v4l-utils to handle USB cameras (v4l2src).
_[tested with Ubuntu 22.04]_

v4l2src device=/dev/video0 ! decodebin ! videoscale ! "video/x-raw,width=1280,height=720" ! videorate ! "video/x-raw,framerate=25" ! vaapipostproc ! "video/x-raw(memory:VASurface)" ! gvadetect model=$MODEL_PATH model-proc=$MODELPROC_PATH device=GPU pre-process-backend=ie nireq=4 model-instance-id=inf0 ! queue ! gvawatermark ! gvafpscounter ! autovideosink sync=false \
v4l2src device=/dev/video2 ! decodebin ! videoscale ! "video/x-raw,width=1280,height=720" ! videorate ! "video/x-raw,framerate=25" ! vaapipostproc ! "video/x-raw(memory:VASurface)" ! gvadetect model=$MODEL_PATH model-proc=$MODELPROC_PATH device=GPU pre-process-backend=ie nireq=4 model-instance-id=inf0 ! queue ! gvawatermark ! gvafpscounter ! autovideosink sync=false

To display available cameras in the system you can use this command:
v4l2-ctl --list-devices

Regards
Tomasz

**Comment by jemata** [comment]
> (v4l2src)

where do i get this? is this from glstreamer? i am running inside docker

**Comment by jemata** [comment]
since Tomasz suggested to install v412src thought it was an extra step.
I have created the following cmd adding the detection and classification models; however, i am not sure what is the syntax issue, i have replace the device CPU with the GPU option provided by you, is this correct?

gst-launch-1.0 \
compositor name=comp sink_0::xpos=0 sink_0::ypos=0 sink_1::xpos=1280 sink_1::ypos=0 ! autovideosink sync=false \
v4l2src device=/dev/video16 ! decodebin ! videoscale ! "video/x-raw,width=1280,height=720" ! videorate ! "video/x-raw,framerate=25" ! vaapipostproc ! "video/x-raw(memory:VASurface)" ! gvadetect model=${OBJECT_DETECTION_MODEL} model_proc=${OBJECT_DETECTION_MODEL_PROC}  device=GPU pre-process-backend=ie nireq=4 model-instance-id=inf0 ! queue ! gvaclassify inference-region=full-frame device=GPU pre-process-backend=ie nireq=4 model-instance-id=inf0 ! queue ! gvaclassify inference-region=full-frame  device=GPU pre-process-backend=ie nireq=4 model-instance-id=inf0 model=${OBJECT_CLASSIFICATION_MODEL} model-proc=/home/dlstreamer/dlstreamer/samples/gstreamer/model_proc/public/preproc-aspect-ratio.json labels-file=/home/dlstreamer/dlstreamer/samples/labels/imagenet_2012.txt ! gvawatermark ! gvafpscounter ! comp.sink_0\
v4l2src device=/dev/video10 ! decodebin ! videoscale ! "video/x-raw,width=1280,height=720" ! videorate ! "video/x-raw,framerate=25" ! vaapipostproc ! "video/x-raw(memory:VASurface)" ! gvadetect model=${OBJECT_DETECTION_MODEL} model_proc=${OBJECT_DETECTION_MODEL_PROC}  device=GPU pre-process-backend=ie nireq=4 model-instance-id=inf0  ! queue ! gvaclassify inference-region=full-frame device=GPU pre-process-backend=ie nireq=4 model-instance-id=inf0 ! queue ! gvaclassify inference-region=full-frame  device=GPU pre-process-backend=ie nireq=4 model-instance-id=inf0 model=${OBJECT_CLASSIFICATION_MODEL} model-proc=/home/dlstreamer/dlstreamer/samples/gstreamer/model_proc/public/preproc-aspect-ratio.json labels-file=/home/dlstreamer/dlstreamer/samples/labels/imagenet_2012.txt ! queue ! gvawatermark ! gvafpscounter ! comp.sink_1

**Comment by jemata** [comment]
ok so i simplify the cmd into this. Although i see 2 dlstreamer windows come up, both show a black screen. I checked the 2 cameras with FFPLAY and both are working and showing video

![image](https://github.com/dlstreamer/dlstreamer/assets/17582122/2275940c-5219-4c67-b6df-dd399ad6a258)

**Comment by jemata** [comment]
> You shared two pictures - one with the simplified command-line, the other with the result. But the result seems to use a different command-line (e.g. using `compositor`), so the result should not creqate two separate windows, but one (where the first command-line will result in two windows).
> 
> Can you share the command-line from the second picture, please?
> 
> (the simplified version contains, in both "branches", `region=full-frame`, which you don't need when running an object-detection before; the object-detection, when successfull, will provide a RegionOfInterest (ROI), and only this region will and shall be used for classification)

here is the one i used which is similar output as the pciture i sent 
gst-launch-1.0 \
v4l2src device=/dev/video11 ! video/x-raw,width=320,height=240,framerate=30/1 ! videoconvert ! gvadetect model=${OBJECT_DETECTION_MODEL} model_proc=${OBJECT_DETECTION_MODEL_PROC} device=GPU ! queue ! gvawatermark ! gvafpscounter ! autovideosink sync=false \
v4l2src device=/dev/video23 ! video/x-raw,width=320,height=240,framerate=30/1 ! videoconvert ! gvadetect model=${OBJECT_DETECTION_MODEL} model_proc=${OBJECT_DETECTION_MODEL_PROC} device=GPU ! queue ! gvawatermark ! gvafpscounter ! autovideosink sync=false

**Comment by pmalatyn** [comment]
@jemata does the @brmarkus proposed pipeline helped you?

**Comment by jemata** [comment]
> gst-launch-1.0 compositor name=m sink_1::xpos=768 ! fpsdisplaysink video-sink=ximagesink sync=false \
>   filesrc location=/home/dlstreamer/person-bicycle-car-detection.mp4 ! \
>   decodebin ! vaapipostproc ! 'video/x-raw(memory:VASurface)' ! \
>   gvadetect model=/home/dlstreamer/temp/models/myYolo8/public/yolov8s/FP32/yolov8s.xml \
>   model-proc=/opt/intel/dlstreamer/samples/gstreamer/model_proc/public/yolo-v8.json device=GPU \
>   pre-process-backend=vaapi-surface-sharing ! queue ! gvawatermark ! videoconvertscale ! queue ! m. \
>   \
>   filesrc location=/home/dlstreamer/1192116-sd_640_360_30fps.mp4 ! \
>   decodebin ! vaapipostproc ! 'video/x-raw(memory:VASurface)' ! \
>   gvadetect model=/home/dlstreamer/temp/models/myYolo8/public/yolov8s/FP32/yolov8s.xml \
>   model-proc=/opt/intel/dlstreamer/samples/gstreamer/model_proc/public/yolo-v8.json device=GPU \
>   pre-process-backend=vaapi-surface-sharing ! queue ! gvawatermark ! videoconvertscale ! queue ! m.

these are working now adding the object detection....

**Comment by jemata** [comment]
im getting the following error when trying the below cmd

![image](https://github.com/dlstreamer/dlstreamer/assets/17582122/25994430-77b1-4720-82ea-22e3aeb54a83)



**ERROR: from element /GstPipeline:pipeline0/GstGvaDetect:gvadetect1: base_inference plugin initialization failed
Additional debug info:
/home/dlstreamer/dlstreamer/src/monolithic/gst/inference_elements/base/inference_singleton.cpp(175): acquire_inference_instance (): /GstPipeline:pipeline0/GstGvaDetect:gvadetect1:

For system memory only supports ie, opencv image preprocessors
ERROR: from element /GstPipeline:pipeline0/GstGvaDetect:gvadetect1: base_inference based element initialization has been failed.
Additional debug info:
/home/dlstreamer/dlstreamer/src/monolithic/gst/inference_elements/base/gva_base_inference.cpp(778): gva_base_inference_set_caps (): /GstPipeline:pipeline0/GstGvaDetect:gvadetect1:

inference is NULL.**

**Comment by jemata** [comment]
i got it to work for object detection with following cmd
gst-launch-1.0 compositor name=m sink_1::xpos=320 ! fpsdisplaysink video-sink=ximagesink sync=false -e \
v4l2src device=/dev/video4 ! video/x-raw,width=320,height=240,framerate=30/1 ! videoconvert ! \
decodebin ! vaapipostproc ! 'video/x-raw(memory:VASurface)' !\
  gvadetect model=${OBJECT_DETECTION_MODEL} \
 model_proc=${OBJECT_DETECTION_MODEL_PROC} device=GPU \
 ! queue ! gvawatermark ! videoconvertscale ! queue ! m. \
  v4l2src device=/dev/video16 ! video/x-raw,width=320,height=240,framerate=30/1 ! videoconvert ! \
decodebin ! vaapipostproc ! 'video/x-raw(memory:VASurface)' !\
  gvadetect model=${OBJECT_DETECTION_MODEL} \
 model_proc=${OBJECT_DETECTION_MODEL_PROC} device=GPU \
  ! queue ! gvawatermark ! videoconvertscale ! queue ! m.

![image](https://github.com/dlstreamer/dlstreamer/assets/17582122/de343a80-d070-4ce4-a15e-98a3f0fd863e)

**Comment by jemata** [comment]
however when i add the object classification piece with this cmd
![image](https://github.com/dlstreamer/dlstreamer/assets/17582122/49ccf414-effd-4666-9db1-fdeb1c9a98ec)


i see this 

![image](https://github.com/dlstreamer/dlstreamer/assets/17582122/9ff0e120-fdba-476e-82b8-d34f2aa35472)

**Comment by pmalatyn** [comment]
@jemata do you was able to check Markus suggestion?

**Comment by jemata** [comment]
i ran the following cmd  with the following variables

export OBJECT_DETECTION_MODEL=/home/dlstreamer/temp/models/myYolo8/public/yolov8s/FP32/yolov8s.xml
export OBJECT_DETECTION_MODEL_PROC=/home/dlstreamer/dlstreamer/samples/gstreamer/model_proc/public/yolo-v8.json
export OBJECT_CLASSIFICATION_MODEL=/home/dlstreamer/intel/dl_streamer/models/public/efficientnet-b0/FP32/efficientnet-b0.xml
export OBJECT_CLASSIFICATION_MODEL_PROC=/home/dlstreamer/temp/public/efficientnet-b0/FP32/efficientnet-b0.bin 


gst-launch-1.0 compositor name=m sink_1::xpos=320 ! fpsdisplaysink video-sink=ximagesink sync=false -e \
v4l2src device=/dev/video4 ! video/x-raw,width=320,height=240,framerate=30/1 ! videoconvert !\
decodebin ! vaapipostproc ! 'video/x-raw(memory:VASurface)' !\
gvadetect model=${OBJECT_DETECTION_MODEL} \
model_proc=${OBJECT_DETECTION_MODEL_PROC} device=GPU \
! queue ! gvaclassify inference-region=full-frame device=GPU \
model=${OBJECT_CLASSIFICATION_MODEL} \
model-proc=/home/dlstreamer/dlstreamer/samples/gstreamer/model_proc/public/preproc-aspect-ratio.json \
labels-file=/home/dlstreamer/dlstreamer/samples/labels/imagenet_2012.txt \
! queue ! gvawatermark ! videoconvertscale ! queue ! m. \
v4l2src device=/dev/video16 ! video/x-raw,width=320,height=240,framerate=30/1 ! videoconvert ! \
decodebin ! vaapipostproc ! 'video/x-raw(memory:VASurface)' ! \
gvadetect model=${OBJECT_DETECTION_MODEL} \
model_proc=${OBJECT_DETECTION_MODEL_PROC} device=GPU \
! queue ! gvaclassify inference-region=full-frame device=GPU \
model=${OBJECT_CLASSIFICATION_MODEL} \
model-proc=/home/dlstreamer/dlstreamer/samples/gstreamer/model_proc/public/preproc-aspect-ratio.json \
labels-file=/home/dlstreamer/dlstreamer/samples/labels/imagenet_2012.txt \
! queue ! gvawatermark ! videoconvertscale ! queue ! m.

and i am getting the following errors


Setting pipeline to PAUSED ...
Pipeline is live and does not need PREROLL ...
Got context from element 'vaapipostproc2': gst.vaapi.Display=context, gst.vaapi.Display=(GstVaapiDisplay)"\(GstVaapiDisplayDRM\)\ vaapidisplaydrm1", gst.vaapi.Display.GObject=(GstObject)"\(GstVaapiDisplayDRM\)\ vaapidisplaydrm1";
Pipeline is PREROLLED ...
Setting pipeline to PLAYING ...
New clock: GstSystemClock
ERROR: from element /GstPipeline:pipeline0/GstGvaDetect:gvadetect1: base_inference failed on frame processing
Additional debug info:
/home/dlstreamer/dlstreamer/src/monolithic/gst/inference_elements/base/gva_base_inference.cpp(928): gva_base_inference_transform_ip (): /GstPipeline:pipeline0/GstGvaDetect:gvadetect1:

Failed to submit images to inference
	Pre-processing was failed.
		Failed while software frame preprocessing
			Failed during OpenCV image pre-processing
				Image's depth should be CV_8U.
ERROR: from element /GstPipeline:pipeline0/GstV4l2Src:v4l2src0: Internal data stream error.
Additional debug info:
../libs/gst/base/gstbasesrc.c(3132): gst_base_src_loop (): /GstPipeline:pipeline0/GstV4l2Src:v4l2src0:
streaming stopped, reason error (-5)
Execution ended after 0:00:02.261898748
Setting pipeline to NULL ...
ERROR: from element /GstPipeline:pipeline0/GstGvaClassify:gvaclassify0: base_inference failed on stop
Additional debug info:
/home/dlstreamer/dlstreamer/src/monolithic/gst/inference_elements/base/gva_base_inference.cpp(879): gva_base_inference_stop (): /GstPipeline:pipeline0/GstGvaClassify:gvaclassify0:
empty inference instance
ERROR: from element /GstPipeline:pipeline0/GstGvaDetect:gvadetect0: base_inference failed on stop
Additional debug info:
/home/dlstreamer/dlstreamer/src/monolithic/gst/inference_elements/base/gva_base_inference.cpp(879): gva_base_inference_stop (): /GstPipeline:pipeline0/GstGvaDetect:gvadetect0:
empty inference instance

**Comment by jemata** [comment]
hmm i ran on a clean boot, they should not be busy or invalid? 
I did try running 1 camera only and that worked fine

**Comment by jemata** [comment]
yes i am the only running on this system, rebooted system ran the docker cmd suggested, checked the video and media devices show up within docker
ran this cmd and worked

gst-launch-1.0 compositor name=m sink_1::xpos=320 ! fpsdisplaysink video-sink=ximagesink sync=false -e v4l2src device=/dev/video4 ! video/x-raw,width=320,height=240,framerate=30/1 ! videoconvert ! gvadetect model=${OBJECT_DETECTION_MODEL} model_proc=${OBJECT_DETECTION_MODEL_PROC} device=GPU ! queue ! gvawatermark ! videoconvertscale ! queue ! m. v4l2src device=/dev/video10 ! video/x-raw,width=320,height=240,framerate=30/1 ! videoconvert ! gvadetect model=${OBJECT_DETECTION_MODEL} model_proc=${OBJECT_DETECTION_MODEL_PROC} device=GPU ! queue ! gvawatermark ! videoconvertscale ! queue ! m.


then ran this cmd adding classfication to it, not sure why adding classification is failing


gst-launch-1.0 compositor name=m sink_1::xpos=320 ! fpsdisplaysink video-sink=ximagesink sync=false -e \
v4l2src device=/dev/video4 ! video/x-raw,width=320,height=240,framerate=30/1 ! videoconvert !\
decodebin ! vaapipostproc ! 'video/x-raw(memory:VASurface)' !\
gvadetect model=${OBJECT_DETECTION_MODEL} \
model_proc=${OBJECT_DETECTION_MODEL_PROC} device=GPU \
! queue ! gvaclassify inference-region=full-frame device=GPU \
model=${OBJECT_CLASSIFICATION_MODEL} \
model-proc=/home/dlstreamer/dlstreamer/samples/gstreamer/model_proc/public/preproc-aspect-ratio.json \
labels-file=/home/dlstreamer/dlstreamer/samples/labels/imagenet_2012.txt \
! queue ! gvawatermark ! videoconvertscale ! queue ! m. \
v4l2src device=/dev/video10 ! video/x-raw,width=320,height=240,framerate=30/1 ! videoconvert ! \
decodebin ! vaapipostproc ! 'video/x-raw(memory:VASurface)' ! \
gvadetect model=${OBJECT_DETECTION_MODEL} \
model_proc=${OBJECT_DETECTION_MODEL_PROC} device=GPU \
! queue ! gvaclassify inference-region=full-frame device=GPU \
model=${OBJECT_CLASSIFICATION_MODEL} \
model-proc=/home/dlstreamer/dlstreamer/samples/gstreamer/model_proc/public/preproc-aspect-ratio.json \
labels-file=/home/dlstreamer/dlstreamer/samples/labels/imagenet_2012.txt \
! queue ! gvawatermark ! videoconvertscale ! queue ! m.

i get the following errors



ERROR: from element /GstPipeline:pipeline0/GstGvaDetect:gvadetect1: base_inference failed on frame processing
Additional debug info:
/home/dlstreamer/dlstreamer/src/monolithic/gst/inference_elements/base/gva_base_inference.cpp(928): gva_base_inference_transform_ip (): /GstPipeline:pipeline0/GstGvaDetect:gvadetect1:

Failed to submit images to inference
	Pre-processing was failed.
		Failed while software frame preprocessing
			Failed during OpenCV image pre-processing
				Image's depth should be CV_8U.
ERROR: from element /GstPipeline:pipeline0/GstV4l2Src:v4l2src0: Internal data stream error.
Additional debug info:
../libs/gst/base/gstbasesrc.c(3132): gst_base_src_loop (): /GstPipeline:pipeline0/GstV4l2Src:v4l2src0:
streaming stopped, reason error (-5)
Execution ended after 0:00:00.345980005
Setting pipeline to NULL ...
ERROR: from element /GstPipeline:pipeline0/GstGvaClassify:gvaclassify0: base_inference failed on stop

**Comment by jemata** [comment]
so individual cmd lines work when combining 2 cameras i keep getting this error
ERROR: from element /GstPipeline:pipeline0/GstGvaDetect:gvadetect1: base_inference failed on frame processing
Additional debug info:
/home/dlstreamer/dlstreamer/src/monolithic/gst/inference_elements/base/gva_base_inference.cpp(928): gva_base_inference_transform_ip (): /GstPipeline:pipeline0/GstGvaDetect:gvadetect1:

Failed to submit images to inference
        Pre-processing was failed.
                Failed while software frame preprocessing
                        Failed during OpenCV image pre-processing
                                Image's depth should be CV_8U.
ERROR: from element /GstPipeline:pipeline0/GstV4l2Src:v4l2src1: Internal data stream error.

**Comment by jemata** [comment]
could it be something with  cmd ike videoconvert!

**Comment by jemata** [comment]
> How do you usually stop the command-line? Some users close the video-window, some press "Ctrl-C", others use signals (SIGTERM, SIGKILL, etc.).
> 
> Are you able to start the shorter command-line (object-detection only), let it run a while, stop it - and then start it again? Do the video- (and media-)devices stay the same, when starting and stopping multiple times?
> 
> Maybe you have a problematic camera... or a problematic firmware...

yes i ran several invidual cameras back to back just doing object detection with no issues, the issue is when i ran 2 cameras

**Comment by jemata** [comment]
ok thanks
