### ISSUE TITLE
there is a customer's detect model need to support

### ISSUE THREAD

**Issue by Fred-cell** [dlstreamer/dlstreamer#420]
The pipeline includes face detection and emotion recognition, and dl streamer doesn't support face detection now, I send this model to Marcin by teams, if any information, i will append comment ASAP. @Wadolkowski Marcin

**Comment by Fred-cell** [comment]
no quantization, the input shape of certerface.onnx is [1,3,768,1280], the input shape of emotion model is [16,3,224,224], the whole pipeline is  as below:
video -> decode -> face detection -> emotion recognition
the device is Arc A770, output is image with label face position with box and show emotion status.

**Comment by pmalatyn** [comment]
this model is not supported by DL Streamer, if you would like to have it added to the list of supported models please let us know and we will come back to you with the answer when it is possible

**Comment by pmalatyn** [comment]
request accepted, will be available in next release
