### ISSUE TITLE
Can we specify the IOU threshold in yolov8 post-process json like yolov5?

### ISSUE THREAD

**Issue by howardwa1** [dlstreamer/dlstreamer#421]
Looks like iou threshold is hard coded in source?

**Comment by howardwa1** [comment]
Hi @brmarkus , you mean iou_threshold value read from xml file?

**Comment by howardwa1** [comment]
I didnt find the the place tbh. I visualized the detection results in both openvino(call api) and dlstreamer using the same model(xml,bin). Kinf of weird openvino API get better detection including bboxes and confidence.

**Comment by howardwa1** [comment]
The bounding boxes in OpenVINO appear more stable and accurate. In contrast, the bounding boxes in DLStreamer often fail to cover the entire person and have lower confidence scores.

**Comment by howardwa1** [comment]
Thanks @brmarkus , will try the latest version and update progress

**Comment by tjanczak** [comment]
Yes, model-proc file takes precedence over model-xml file, model-xml is parsed only if model-proc file is missing. 
Right now it cannot be changed in runtime.

**Comment by howardwa1** [comment]
We tested yolov8 with our custom model but many bboxes can only cover partial object. However the same model running on openvino and pytorch , the bboxes look much more accurate

**Comment by howardwa1** [comment]
Also tried yolo-x on coco dataset in dlstreamer looks much better than yolov8 detections

**Comment by howardwa1** [comment]
And very confusing here :https://dlstreamer.github.io/supported_models.html#supported-models

**Comment by howardwa1** [comment]
The link above said no need model-proc in yolov 7/8/9, I just tested if not specify post-proc json, pipeline wont run

**Comment by howardwa1** [comment]
> Yes, model-proc file takes precedence over model-xml file, model-xml is parsed only if model-proc file is missing. Right now it cannot be changed in runtime.

Hi @tjanczak , what arguments can be put to postproc json and what arguments parsed from the xml model file?

**Comment by howardwa1** [comment]
> Here is the command line with model-proc: filesrc location=${INPUT} ! decodebin ! vaapipostproc ! video/x-raw(memory:VASurface) ! queue ! gvadetect device=GPU pre-process-backend=vaapi-surface-sharing model={$MODEL_PATH}/yolov8s/FP16/yolov8s.xml model-proc=${MODEL_PROC_PATH}/samples/gstreamer/model_proc/public/yolo-v8.json ....
> 
> Here is the command line without model-proc (it should yield same outcome): filesrc location=${INPUT} ! decodebin ! vaapipostproc ! video/x-raw(memory:VASurface) ! queue ! gvadetect device=GPU pre-process-backend=vaapi-surface-sharing model={$MODEL_PATH}/yolov8s/FP16/yolov8s.xml ....
> 
> Are you using the latest version 2024.0.2? If yes, can you please share your pipeline that does not work or works with overlapping bounding boxes?

I am running pipeline in python on CPU platform. So no vaapi-surface used. For preprocessing, I just specified        
  **"params": {
            "resize": "aspect-ratio",
            "range":[0,1]

          }**
in the model-proc json file. Do I still need implement an explicit pre-processing myself? Thanks

**Comment by howardwa1** [comment]
we found vehicle bboxes are perfect, but just person bboxes look like nms failed. The person bbox not cover the whole person

**Comment by howardwa1** [comment]
Hi @brmarkus  , looks like my post processing got some issues, checked the existing posts here and prob solved. thanks

**Comment by howardwa1** [comment]
refer to this:https://github.com/dlstreamer/dlstreamer/issues/394
