### ISSUE TITLE
Update aligned image for the next classifier 

### ISSUE THREAD

**Issue by PavanKumar13** [dlstreamer/dlstreamer#422]
Hi All,

I wanted to do an alignment of the face using the landmarks and update the aligned face image for the next gvaclassify to get the facial feature vector from the aligned face,

gvadetect(detect faces) -> gvaclassify(Landmarks - align face and update the face image in the buffer) -> gvaclassify(Facial vector - will get the updated aligned face as an input)

can you please help me with any suggestions,

Regards,
Pavan

**Comment by PavanKumar13** [comment]
Hi @brmarkus,

we are trying to implement facial recognition system with dlstreamer pipeline, I am able to get the inference results from face detector and extracting the landmarks from the detected faces using gvadetect and gvaclassify, next step I wanted to do is align(skew correction,etc.,) the faces (probably using gvapython) and pass it to next feature vector model.

currently, I am getting the faces from the gvadetect, landmarks for the detected faces from gvaclassify from the pipeline, after this I have a custom function to align the faces outside of the pipeline and use openvino inferencing to get the feature vector, I am not sure how to pass only the aligned faces to the next gvaclassify element, I wanted some suggestions over here,
if you could help me how could I update the existing faces buffer with the aligned faces, so that feature vector extraction  can be done,

what am I doing now (pipeline + python module for feature vector):
1. gvadetect(detect faces) -> gvaclassify(Landmarks) 
2. the output landmarks will be used to align and get feature vector in a separate python module, which is called in the frame_callback which is not part of the pipeline.

what's expected(full flow in pipeline to get feature vector):
gvadetect(detect faces) -> gvaclassify(Landmarks) ->align faces (to be part of pipeline)-> gvaclassify(Facial vector - will get the updated aligned face as an input)

**Comment by pmalatyn** [comment]
@PavanKumar13 does the sugestions from Markus helped you to solve your pipeline or you still need help?

**Comment by pmalatyn** [comment]
closing due to age
