### ISSUE TITLE
How is 'padding' parameter in model proc file used?

### ISSUE THREAD

**Issue by YIXIN-YAO** [dlstreamer/dlstreamer#424]
Hi,
I wanted to ask how the **padding** preprocessing parameter in the model proc file is parsed into the code and where it is used when using the YOLO series models. Is the *stride_x* and *stride_y* the same as *stride* in letterbox function below?

https://github.com/ultralytics/yolov5/blob/e4d836080f68dd14ae9becaa7b50c510ac1db54f/utils/augmentations.py#L111

By reading the code, I can only find these two functions: 

https://github.com/dlstreamer/dlstreamer/blob/master/src/monolithic/inference_backend/pre_proc/opencv_utils/opencv_utils.cpp#L215
https://github.com/dlstreamer/dlstreamer/blob/master/src/monolithic/inference_backend/pre_proc/opencv_utils/opencv_utils.cpp#L297

But I can't find where they are called.

I am asking because I found that this parameter brings a huge performance difference on my CPU. After using a big padding stride value like 110, the number of CPU cores needed to process the same video stream decreased from 5 to 1.5, but the detection accuracy dropped slightly. I would like to know why there is such a significant difference in CPU usage.

I'm using a yolov8n model, the input size is 640.
Here is my proc file:
```
{
  "json_schema_version": "2.2.0",
  "input_preproc": [
    {
      "format": "image",
      "layer_name": "images",
      "params": {
        "resize": "aspect-ratio",
        "range": [
          0.0,
          1.0
        ],
        "color_space": "RGB",
        "reverse_channels": true,
        "padding": {
          "stride_x": 110,
          "stride_y": 110
        }
      }
    }
  ],
  "output_postproc": [
    {
      "converter": "yolo_v8",
      "iou_threshold": 0.7,
      "nms_threshold": 0.7,
      "bbox_number_on_cell": 3,
      "classes": 4,
      "labels": [
        "person",
        "scooterist",
        "cyclist",
        "motorcyclist"
      ]
    }
  ]
}
```
BTW, is *iou_threshold* and *nms_threshold* the same thing?

Thanks!

**Comment by pmalatyn** [comment]
hello,
you are right stride_x and stride_y are defining the area where padding needs to be added. If you will make it bigger the accuracy will drop (but also less resources will be needed) as less pixels will be analyzed.

**Comment by YIXIN-YAO** [comment]
Hi @pmalatyn, Thank you for your reply.
Does that mean if my model input size is 640x640, and when I set "padding": {"stride_x": 100, "stride_y": 100}, my image will be resized to 440x440 and then have a 100-pixel wide border added around it?

**Comment by pmalatyn** [comment]
@YIXIN-YAO yes you are correct. Please have a look into source code for more details:
[(https://github.com/dlstreamer/dlstreamer/blob/5d51072ce41753fb76f31544958f682b5b4e6b5d/src/monolithic/inference_backend/image_inference/async_with_va_api/va_api_wrapper/vaapi_converter.cpp#L191)]
and
[https://github.com/dlstreamer/dlstreamer/blob/5d51072ce41753fb76f31544958f682b5b4e6b5d/src/monolithic/inference_backend/pre_proc/opencv/opencv_pre_proc.cpp#L46]
hope it will help :)

**Comment by pmalatyn** [comment]
no further comments, closing
