### ISSUE TITLE
when using inference-region=roi-list vs full-frame in my classification pipeline, classification data does not get published

### ISSUE THREAD

**Issue by jemata** [dlstreamer/dlstreamer#425]
Running DL streamer using the Docker option on a Serpent Canyon Board and using Ubuntu 22.04

docker build -t dlstreamer -f dlstreamer.Dockerfile .
docker run -it     -v /dev:/dev --net=host --device=/dev/dri --group-add=110     -v ~/.Xauthority:/home/dlstreamer/.Xauthority -v /tmp/.X11-unix -e DISPLAY=$DISPLAY     -v /dev/bus/usb     --device-cgroup-rule "c 81:* rmw"     --device-cgroup-rule "c 189:* rmw"     -e XDG_RUNTIME_DIR=$XDG_RUNTIME_DIR --rm dlstreamer /bin/bash

export OBJECT_DETECTION_MODEL=/home/dlstreamer/temp/models/myYolo8/public/yolov8s/FP32/yolov8s.xml
export OBJECT_DETECTION_MODEL_PROC=/home/dlstreamer/dlstreamer/samples/gstreamer/model_proc/public/yolo-v8.json
export OBJECT_CLASSIFICATION_MODEL=/home/dlstreamer/intel/dl_streamer/models/public/efficientnet-b0/FP32/efficientnet-b0.xml
export OBJECT_CLASSIFICATION_MODEL_PROC=/home/dlstreamer/temp/public/efficientnet-b0/FP32/efficientnet-b0.bin

When using inference-region=full-frame 

export OUTFILE=/home/dlstreamer/toPublish1.json

gst-launch-1.0 v4l2src device=/dev/video16 ! video/x-raw,width=320,height=240,framerate=30/1 ! videoconvert ! gvadetect model=${OBJECT_DETECTION_MODEL} model_proc=${OBJECT_DETECTION_MODEL_PROC} device=CPU ! queue ! gvaclassify inference-region=full-frame device=CPU model=${OBJECT_CLASSIFICATION_MODEL} model-proc=/home/dlstreamer/dlstreamer/samples/gstreamer/model_proc/public/preproc-aspect-ratio.json labels-file=/home/dlstreamer/dlstreamer/samples/labels/imagenet_2012.txt ! queue ! gvawatermark ! videoconvert ! gvametaconvert format=json ! gvametapublish method=file file-path=${OUTFILE} ! fpsdisplaysink video-sink=xvimagesink sync=false -e

i see the following in my .json file

[{"objects":[{"h":77,"region_id":206,"roi_type":"bottle","w":35,"x":185,"y":8},{"h":64,"region_id":207,"roi_type":"bottle","w":38,"x":192,"y":81},{"h":61,"region_id":208,"roi_type":"bottle","w":46,"x":125,"y":87},{"classification_layer_name:efficientnet-b0/model/head/dense/BiasAdd:0":{"confidence":10.541126251220703,"label":"n03983396 pop bottle, soda bottle","label_id":737,"model":{"name":"TensorFlow_Frontend_IR"}},"h":240,"w":320,"x":0,"y":0}],"resolution":{"height":240,"width":320},"timestamp":562628971},
{"objects":[{"h":77,"region_id":224,"roi_type":"bottle","w":35,"x":185,"y":8},{"h":64,"region_id":225,"roi_type":"bottle","w":38,"x":192,"y":81},{"h":61,"region_id":226,"roi_type":"bottle","w":46,"x":125,"y":87},{"classification_layer_name:efficientnet-b0/model/head/dense/BiasAdd:0":{"confidence":10.537965774536133,"label":"n03983396 pop bottle, soda bottle","label_id":737,"model":{"name":"TensorFlow_Frontend_IR"}},"h":240,"w":320,"x":0,"y":0}],"resolution":{"height":240,"width":320},"timestamp":595818781},

however when using inference-region=roi-list, it does not provide the classification data, why is this? am i missing an option in my pipeline?

[{"objects":[{"h":78,"region_id":206,"roi_type":"bottle","w":35,"x":185,"y":6},{"h":64,"region_id":207,"roi_type":"bottle","w":38,"x":192,"y":81},{"h":61,"region_id":208,"roi_type":"bottle","w":46,"x":125,"y":87}],"resolution":{"height":240,"width":320},"timestamp":564983566},
{"objects":[{"h":76,"region_id":227,"roi_type":"bottle","w":35,"x":185,"y":8},{"h":64,"region_id":228,"roi_type":"bottle","w":38,"x":192,"y":81},{"h":61,"region_id":229,"roi_type":"bottle","w":46,"x":125,"y":87}],"resolution":{"height":240,"width":320},"timestamp":597980578},

**Comment by pmalatyn** [comment]
we tuned the configuration of the system and it is working as expected so no bug from DL Streamer side, closing

**Comment by pmalatyn** [comment]
@brmarkus sure :)

roi-list

This is the default setting (when there is no explicit setting). It means that detected ROIs (bounding boxes) which are detected by gvaclassify are classified to specific class/classes one by one. So each detected object is classified. This can be seen in output json file.
Examplary pipeline: Pipeline: gst-launch-1.0 filesrc location=/home/USER/video-examples/Fun_at_a_Fair.mp4 ! decodebin ! gvadetect model=/home/USER/FP32/yolov8s.xml model_proc=/home/USER/intel/dlstreamer_gst/samples/gstreamer/model_proc/public/yolo-v8.json device=CPU ! queue ! gvaclassify device=CPU model=/home/USER/FP32/efficientnet-b0.xml model-proc=/home/USER/intel/dlstreamer_gst/samples/gstreamer/model_proc/public/preproc-aspect-ratio.json labels-file=/home/USER/intel/dlstreamer_gst/samples/labels/imagenet_2012.txt inference-region=roi-list ! queue ! gvawatermark ! videoconvert ! gvametaconvert format=json ! gvametapublish method=file file-path=/home/USER/yolo_roi-list.json ! fakesink sync=false

full-frame

This is the case when entire frame is assigned to class, regardless of detection. Therefore, in JSON file the classify result is seen on the same level as detection. 

Here is the same pipeline as above for roi-list, but with full-frame classification.
Pipeline: gst-launch-1.0 filesrc location=/home/USER/Fun_at_a_Fair.mp4 ! decodebin ! gvadetect model=/home/USER/FP32/yolov8s.xml model_proc=/home/USER/intel/dlstreamer_gst/samples/gstreamer/model_proc/public/yolo-v8.json device=CPU ! queue ! gvaclassify device=CPU model=/home/USER/FP32/efficientnet-b0.xml model-proc=/home/USER/intel/dlstreamer_gst/samples/gstreamer/model_proc/public/preproc-aspect-ratio.json labels-file=/home/USER/intel/dlstreamer_gst/samples/labels/imagenet_2012.txt inference-region=full-frame ! queue ! gvawatermark ! videoconvert ! gvametaconvert format=json ! gvametapublish method=file file-path=/home/USER/yolo_full-frame.json ! fakesink sync=false

There were some wrong settings with file-path param on original machine, after fixing this those pipeline worked as expected and were producing outputs to specified files
