### ISSUE TITLE
Can run on Mac M1? 

### ISSUE THREAD

**Issue by kbscolin** [dlstreamer/dlstreamer#426]
Hello,  I run the dlstreamer examples according to https://dlstreamer.github.io/get_started/tutorial.html#tutorial-setup-for-docker
on mac m1 machaine. An  error happens: 

dlstreamer@d017cc3cba4a:~$ gst-launch-1.0 \
filesrc location=${VIDEO_EXAMPLE} ! decodebin ! \
gvadetect model=${DETECTION_MODEL} model_proc=${DETECTION_MODEL_PROC} device=CPU ! queue ! \
gvawatermark ! videoconvert ! fpsdisplaysink video-sink=xvimagesink sync=false

(gst-plugin-scanner:18): GStreamer-WARNING **: 14:15:42.470: Failed to load plugin '/opt/intel/dlstreamer/gstreamer/lib/gstreamer-1.0/libgstximagesrc.so': libXtst.so.6: cannot open shared object file: No such file or directory

(gst-plugin-scanner:18): GStreamer-WARNING **: 14:15:44.718: Failed to load plugin '/opt/intel/dlstreamer/gstreamer/lib/gstreamer-1.0/libgstximagesrc.so': libXtst.so.6: cannot open shared object file: No such file or directory

(gst-plugin-scanner:18): GLib-GObject-WARNING **: 14:15:44.915: cannot register existing type 'GstVideoConvert'

(gst-plugin-scanner:18): GLib-CRITICAL **: 14:15:44.916: g_once_init_leave: assertion 'result != 0' failed

(gst-plugin-scanner:18): GStreamer-CRITICAL **: 14:15:44.916: gst_element_register: assertion 'g_type_is_a (type, GST_TYPE_ELEMENT)' failed

(gst-plugin-scanner:18): GLib-GObject-WARNING **: 14:15:45.040: cannot register existing type 'GstVideoScale'

(gst-plugin-scanner:18): GLib-CRITICAL **: 14:15:45.040: g_once_init_leave: assertion 'result != 0' failed

(gst-plugin-scanner:18): GStreamer-CRITICAL **: 14:15:45.040: gst_element_register: assertion 'g_type_is_a (type, GST_TYPE_ELEMENT)' failed
Setting pipeline to PAUSED ...
ERROR: from element /GstPipeline:pipeline0/GstFPSDisplaySink:fpsdisplaysink0/GstXvImageSink:xvimagesink0: Could not initialise Xv output
Additional debug info:
../sys/xvimage/xvimagesink.c(1944): gst_xv_image_sink_open (): /GstPipeline:pipeline0/GstFPSDisplaySink:fpsdisplaysink0/GstXvImageSink:xvimagesink0:
Could not open display (null)
ERROR: pipeline doesn't want to preroll.
Failed to set pipeline to PAUSED.
Setting pipeline to NULL ...
Freeing pipeline ...
dlstreamer@d017cc3cba4a:~$ 

Thanks!

**Comment by kbscolin** [comment]
Ok, thanks! I use openvino 2022. If that,  it is very difficult to let dlstreamer run mac m1.

**Comment by pmalatyn** [comment]
@kbscolin primarily we are focusing on Intel HW support for DL Streamer, but Markus gave you good hints how you can try to solve your issue. There was an architecture change from 1.0 to 2.0 in 2024 releases to follow OV changes so you should try it with newer version also.
