### ISSUE TITLE
When launching multiple RTSP streams with gst-launch, the inference results are incorrect.

### ISSUE THREAD

**Issue by leaffangyi** [dlstreamer/dlstreamer#427]
### Problem Description:
After concatenating 25 RTSP streams into one and launching it with gst-launch, the trajectories aggregated by gvapython through VideoFrame object_id exhibit abnormal detection boxes and do not follow normal trajectory paths. However, when 25 RTSP streams are launched via 25 separate gst-launch instances, the trajectories aggregated by gvapython through VideoFrame object_id appear normal, without any abnormal detection boxes.

### Error code:
```
gst-launch-1.0 -e \
rtspsrc location=$RTSP_URI1 ! decodebin ! vaapipostproc ! video/x-raw(memory:VASurface) ! gvadetect model=$MODEL_PATH model-proc=$MODEL_PROC device=GPU pre-process-backend=vaapi-surface-sharing batch_size=8 model-instance-id=inf0 ! gvatrack tracking-type=zero-term-imageless ! gvapython module=postproc_callbacks/analyze_plugin.py class=AnalyzePlugin function=process_frame ! gvafpscounter ! fakesink \
rtspsrc location=$RTSP_URI2 ! decodebin ! vaapipostproc ! video/x-raw(memory:VASurface) ! gvadetect model=$MODEL_PATH model-proc=$MODEL_PROC device=GPU pre-process-backend=vaapi-surface-sharing batch_size=8 model-instance-id=inf0 ! gvatrack tracking-type=zero-term-imageless ! gvapython module=postproc_callbacks/analyze_plugin.py class=AnalyzePlugin function=process_frame ! gvafpscounter ! fakesink \
...

```

### Correct code:
```
gst-launch-1.0 -e  rtspsrc location=$RTSP_URI1 ! decodebin ! vaapipostproc ! video/x-raw(memory:VASurface) ! gvadetect model=$MODEL_PATH model-proc=$MODEL_PROC device=GPU pre-process-backend=vaapi-surface-sharing batch_size=1 ! gvatrack tracking-type=zero-term-imageless ! gvapython module=postproc_callbacks/analyze_plugin.py class=AnalyzePlugin function=process_frame ! gvafpscounter ! fakesink
gst-launch-1.0 -e rtspsrc location=$RTSP_URI2 ! decodebin ! vaapipostproc ! video/x-raw(memory:VASurface) ! gvadetect model=$MODEL_PATH model-proc=$MODEL_PROC device=GPU pre-process-backend=vaapi-surface-sharing batch_size=1 ! gvatrack tracking-type=zero-term-imageless ! gvapython module=postproc_callbacks/analyze_plugin.py class=AnalyzePlugin function=process_frame ! gvafpscounter ! fakesink
...
```

### analyze_plugin.py
```
class AnalyzePlugin：
    def __init__(self):
        self.tracks_dict = {}
        self.frame_id = 0
    def process_frame(self, frame: VideoFrame) -> bool:
        detects = []
        for roi in frame.regions():
            label_id = roi.label_id()
            object_id = roi.object_id()
            confidence = roi.confidence()
            rect = roi.normalized_rect()
            if object_id not in self.tracks_dict:
                self.tracks_dict[object_id] = []
            self.tracks_dict[object_id].append([self.frame_id, label_id, object_id, confidence, rect])
        del_list = []
        tracks_list = []
        for track_id in self.tracks_dict:
            tracks = self.tracks_dict[track_id]
            lst_frame_id = tracks[-1][0]
            if self.frame_id - lst_frame_id > 5:
                del_list.append(track_id)
                tracks_list.append(tracks)
        for track_id in del_list:
            del self.tracks_dict[track_id]
    
        # analyze tracks_list code
        
        self.frame_id += 1
        return True

```

### model-proc
```
{
    "json_schema_version": "2.2.0",
    "input_preproc": [
      {
          "params": {
              "resize": "aspect-ratio"
          }
      }
    ],
    "output_postproc": [
      {
        "converter": "yolo_v8",
        "labels": [
            "fastpackage"
        ]
      }
    ]
  }

```

### environment:
    GPU: flex170
    system: ubuntu22.04
    kernel: 5.15.0-116-generic
    driver:intel-i915-dkms/1.24.3.23.240419.26
    container: https://github.com/dlstreamer/dlstreamer/releases/download/v2024.0.2/dlstreamer.Dockerfile

**Comment by pmalatyn** [comment]
@leaffangyi  are you able to provide at least part of the answers for Markus questions? It would help us to better understand your issue. E.g. we had issues with bigger batch sizes but it was already fixed. Thanks!

**Comment by leaffangyi** [comment]
@pmalatyn The environment is quite complex; I will conduct tests with different numbers of video streams and batch sizes next week.

**Comment by leaffangyi** [comment]
After changing vaapipostproc to vaapipostproc width=640 height=360, the results became normal, and the saved images also returned to normal. The images saved before this change were abnormal as well.

**Comment by pmalatyn** [comment]
@leaffangyi good to hear that, am I understanding it correctly - after you normalized all inputs to same size you do not observe any deviations right?

**Comment by leaffangyi** [comment]
@pmalatyn I suspect that the issue is caused by the batch-size of gvadetect. My video has 25 streams, and when the batch-size of gvadetect is 32, there are no problems. However, when the batch-size is 8, there are extra detection boxes appearing. The vaapipostproc width=640 height=360 that I mentioned above only resolved the anomaly with the image data.

**Comment by pmalatyn** [comment]
@leaffangyi thanks for the comment, we will investigate it further
