### ISSUE TITLE
back to back detect missing parent_id

### ISSUE THREAD

**Issue by PrinceP** [dlstreamer/dlstreamer#430]
According to https://github.com/dlstreamer/dlstreamer/issues/206#issuecomment-1188346806

gvadetect sets parent_id field only if inference-region=roi-list (second gvadetect in your pipeline).
Once you get parent_id, you can iterate all objects and find parent object itself by checking roi->id() == parent_id.

Now for the below tried command, the parent_id is 0 for both first model class and second model class
```python
pipeline = Gst.parse_launch(
    "filesrc location=test.mp4 ! decodebin ! vapostproc ! video/x-raw(memory:VAMemory) ! "
    "gvadetect model=first_custom_yolov7.xml model-proc=first_custom_yolov7.json "
    "device=GPU pre-process-backend=va-surface-sharing batch-size=1 threshold=0.4 inference-region=full-frame model-instance-id=yolov7_id name=yolov7 ! "
    "queue ! gvatrack ! queue !"
    "gvadetect model=second_custom_yolov8.xml model-proc=second_custom_yolov8.json "
    "device=GPU pre-process-backend=va-surface-sharing object-class=person  inference-region=roi-list model-instance-id=yolov8_id name=yolov8 threshold=0.3 ! "
    "queue ! gvawatermark name=gvawatermark ! videoconvertscale ! gvafpscounter ! vah264enc ! h264parse ! mp4mux ! "
    "filesink location=testoutput_GPU.mp4"
)
```
If we extract the parent_id on the GstVideoRegionOfInterestMeta using https://github.com/dlstreamer/dlstreamer/blob/5d51072ce41753fb76f31544958f682b5b4e6b5d/samples/gstreamer/python/draw_face_attributes/draw_face_attributes.py#L42

by adding below codebase 
```python
for roi in frame.regions():
        print(f"ROI parent ID: {roi.meta().parent_id}")
        print(f"X: {roi.meta().x}, Y: {roi.meta().y} W: {roi.meta().w}, H: {roi.meta().h}")
        print(f"ROI object ID: {roi.object_id()}, label: {roi.label()}, confidence: {roi.confidence()}")
```

we are getting
```text
ROI parent ID: 0
X: 288, Y: 279 W: 368, H: 439
ROI object ID: 11, label: person, confidence: 0.8125
ROI parent ID: 0
X: 220, Y: 226 W: 393, H: 248
ROI object ID: None, label: x confidence: 0.5283203125
```
which is wrong as the 2nd label comes from the second custom model and the parent id should be object id of first model

@mikhail-nikolskiy

**Comment by pmalatyn** [comment]
hello @PrinceP 
in the comment that you pointed out there is stated that "The first gvadetect in your pipeline runs detection on full frame, so there is no "parent" object (i.e the "parent" is full original image)." and I can see that also here you have your 1st pipeline with full-frame and only 2nd one has roi-list.
Here is broader description of full-frame and roi-list
For full-frame: detection and classification are on the same level in json file, both under "objects". It means that on single frame (with some resolution and timestamp) there was a detection and classification done, on the same full frame picture. In case of multiple detected objects, there would be multiple detection sections but only one classification. 
In the contrary, for the roi-list: classification is UNDER detection, one level 'deeper'. It means classification was done for the detected object, not on full frame but only on some roi. Here each detected object would be classified.
Moreover if you would like to track object via parent id it should be done as explained in the comment that you pointed
Does it makes sense and I understand properly your use case?

**Comment by knandanan** [comment]
@pmalatyn to clarify, the pipeline has two back-to-back gvadetect where the first gvadetect runs on full frame and the second gvadetect runs on inference-region=roi-list and object-class=person. For the detections from the second gvadetect, we get parent_id = 0 where as ideally it should have given parent_id that refer to the id of the detection box from the first gvadetect

**Comment by pmalatyn** [comment]
understood, but gvadetect sets parent_id only if you use roi-list (and not full-frame). SO in your case the 1st pipeline is running on full frame so there is nothing that 2nd pipeline can refer to.

I think that it was clarified in similar manner in comment thant you refered: https://github.com/dlstreamer/dlstreamer/issues/206#issuecomment-1188346806

**Comment by PrinceP** [comment]
@pmalatyn Can you point the correct in my Gst.parse_launch. Is it 2 different pipelines? I want a single pipeline like this gvadetect -> gvatrack -> gvadetect?

**Comment by knandanan** [comment]
> understood, but gvadetect sets parent_id only if you use roi-list (and not full-frame). SO in your case the 1st pipeline is running on full frame so there is nothing that 2nd pipeline can refer to.
> 
> I think that it was clarified in similar manner in comment thant you refered: [#206 (comment)](https://github.com/dlstreamer/dlstreamer/issues/206#issuecomment-1188346806)

well I do understand that parent_id won't be set for the bounding boxes from first gvadetect as it runs on full frame. But the bounding boxes from the second gvadetect (it uses roi-list) should have got assigned parent id, right ?

**Comment by pmalatyn** [comment]
please have a look at my response in this issue: https://github.com/dlstreamer/dlstreamer/issues/434 
it is also relevant to your case, when you are using object-class without definition of labels bind to ROIs then such ROI is skipped from detection

**Comment by pmalatyn** [comment]
no further feedback, closing, please reopen the issue if needed
