### ISSUE TITLE
WARNING: erroneous pipeline: no element "gvaattachroi" inside Docker image 2024.1.2-dev-ubuntu24

### ISSUE THREAD

**Issue by antoniomtz** [dlstreamer/dlstreamer#433]
Hello, I'm following the documentation here https://github.com/dlstreamer/dlstreamer/blob/6a9a405ff45200cb5883614f496027a36b04cfd7/samples/gstreamer/gst_launch/gvaattachroi/README.md to run the gvaattachroi sample code inside dlstreamer docker container 2024.1.2-dev-ubuntu24 and get the following error:

```
root@11425b4a304f:/home/dlstreamer/dlstreamer/samples/gstreamer/gst_launch/gvaattachroi# ./gvaattachroi_sample.sh "https://videos.pexels.com/video-files/1192116/1192116-sd_640_360_30fps.mp4" CPU file 100,150,200,300
MODELS_PATH: /home/dlstreamer/intel/dl_streamer/models
gst-launch-1.0 urisourcebin buffer-size=4096 uri=https://videos.pexels.com/video-files/1192116/1192116-sd_640_360_30fps.mp4 ! decodebin ! gvaattachroi roi=100,150,200,300 ! gvadetect inference-region=1 model=/home/dlstreamer/intel/dl_streamer/models/public/yolov8s/FP32/yolov8s.xml device=CPU pre-process-backend=ie ! queue ! gvawatermark ! videoconvertscale ! gvafpscounter ! vah264enc ! h264parse ! mp4mux ! filesink location=1192116-sd_640_360_30fps_CPU.mp4
WARNING: erroneous pipeline: no element "gvaattachroi"
```

Likewise, the "yolo_detect.sh" throws the error: 

```
#./yolo_detect.sh yolov8s CPU "https://videos.pexels.com/video-files/1192116/1192116-sd_640_360_30fps.mp4" display
gst-launch-1.0 urisourcebin buffer-size=4096 uri=https://videos.pexels.com/video-files/1192116/1192116-sd_640_360_30fps.mp4 ! decodebin ! gvadetect model=/home/dlstreamer/intel/dl_streamer/models/public/yolov8s/FP32/yolov8s.xml model-proc=/opt/intel/dlstreamer/samples/gstreamer/model_proc/public/yolo-v8.json device=CPU pre-process-backend=ie ! queue ! gvawatermark ! videoconvertscale ! gvafpscounter ! autovideosink sync=false
Setting pipeline to PAUSED ...
Pipeline is PREROLLING ...
Got context from element 'vapostproc1': gst.va.display.handle=context, gst-display=(GstObject)"\(GstVaDisplayDrm\)\ vadisplaydrm2", description=(string)"Intel\(R\)\ Gen\ Graphics", path=(string)/dev/dri/renderD128;
Setting pipeline to PLAYING ...
Buffering, setting pipeline to PAUSED ...
Redistribute latency...
ERROR: from element /GstPipeline:pipeline0/GstAutoVideoSink:autovideosink0/GstKMSSink:autovideosink0-actual-sink-kms: GStreamer encountered a general resource error.
Additional debug info:
../sys/kms/gstkmssink.c(2032): gst_kms_sink_show_frame (): /GstPipeline:pipeline0/GstAutoVideoSink:autovideosink0/GstKMSSink:autovideosink0-actual-sink-kms:
drmModeSetPlane failed: Permission denied (13)
```

This is the command I use to launch the container which is working for previous versions:

`docker run -it --privileged -e DISPLAY=$DISPLAY -v ~/.Xauthority:/home/dlstreamer/.Xauthority -v /tmp/.X11-unix:/tmp/.X11-unix --user root --ipc=host --rm intel/dlstreamer:2024.1.2-dev-ubuntu2`

Any ideas why the docker image isn't working?

**Comment by antoniomtz** [comment]
Update, the script worked using the `latest` tag. Should be 2024.1.2 also latest tag as of now?

**Comment by pmalatyn** [comment]
hello ,

in last week we releases latest version (2024.1.2) which has also support for Ubuntu 24.04, so as for now there will be 4 images:
2 for Ubuntu 22.04 (standard and dev version) and 2 for Ubuntu 24.04 (standard and dev version)

DL Streamer is release monthly so please expect every end of the month newer version with expanded functionalities

**Comment by pmalatyn** [comment]
according to comment above script worked so will close the issue

**Comment by wow2006** [comment]
Hello @pmalatyn,

I can't find  `gvaattachroi` in the following docker images `intel/dlstreamer:2024.1.2-dev-ubuntu24`, or `intel/dlstreamer:2025.0.1-dev-ubuntu22`. I searched the repo for the element name `gvaattachroi` and I only found it in the sample no c code. Could you please tell me what I am missing?

**Comment by pmalatyn** [comment]
please try to check: tests/helper_elements/gvaattachroi

**Comment by pmalatyn** [comment]
good question @brmarkus - it is currently in internal components, the plan is to move it to external ones

**Comment by pmalatyn** [comment]
we noticed recently that gvaattachroi is not included in our source code and working on resolving this issue, but after your question we checked one more time the images as you suggested and you are right, we are missing this element also in docker images, we will fix this, will provide ETA as soon as possible

**Comment by pmalatyn** [comment]
gvaattachroi is now included in the code: 
https://github.com/open-edge-platform/edge-ai-libraries/tree/main/libraries/dl-streamer/src/monolithic/gst/elements
