### ISSUE TITLE
No such element or plugin 'gvadetect'

### ISSUE THREAD

**Issue by sharmav2-intc** [dlstreamer/dlstreamer#435]
I had a working setup with dl streamer, suddenly this error started coming "No such element or plugin 'gvadetect'", and I'm not able to detect/classify anymore.
I tried reinstalling dlstreamer, openvino, oneapi, still it's not getting resolved, it's showing me this:-

gst-inspect-1.0 gvadetect

(gst-inspect-1.0:25500): GStreamer-WARNING **: 14:26:56.604: External plugin loader failed. This most likely means that the plugin loader helper binary was not found or could not be run. You might need to set the GST_PLUGIN_SCANNER environment variable if your setup is unusual. This should normally not be required though.

(gst-inspect-1.0:25500): GStreamer-WARNING **: 14:26:56.604: Failed to load plugin '/opt/intel/dlstreamer/lib/gstreamer-1.0/libgstdlstreamer_opencv.so': libopencv_objdetect.so.410: cannot open shared object file: No such file or directory

(gst-inspect-1.0:25500): GStreamer-WARNING **: 14:26:56.604: Failed to load plugin '/opt/intel/dlstreamer/lib/gstreamer-1.0/libgstvideoanalytics.so': libopencv_imgproc.so.410: cannot open shared object file: No such file or directory
No such element or plugin 'gvadetect'

**Comment by sharmav2-intc** [comment]
Hi @brmarkus , sourcing I did, 
still not working

**Comment by pmalatyn** [comment]
hello,

@sharmav2-intc few questions:
1) which version of DL Streamer were you using, 
2) which version you reinstalled, 
3) which option you used for installation, 
4) did Ubuntu was updated in the meantime?

**Comment by sharmav2-intc** [comment]
HI @pmalatyn,
I followed, previously also I followed this for installation,
 [Install Guide Ubuntu — Intel® Deep Learning Streamer (Intel® DL Streamer) documentation](https://dlstreamer.github.io/get_started/install/install_guide_ubuntu.html)

this for installation, I used debian installation option, 
Ubuntu was not updated

**Comment by sharmav2-intc** [comment]
- Yes I have more files under /opt/intel/dlstreamer/lib/gstreamer-1.0/
- Yes, /opt/intel/dlstreamer/lib/gstreamer-1.0/libgstvideoanalytics.so is present in the folder

- After doing gst-inspect-1.0 /opt/intel/dlstreamer/lib/gstreamer-1.0/libgstvideoanalytics.so

/opt/intel/dlstreamer/lib/gstreamer-1.0$ gst-inspect-1.0 /opt/intel/dlstreamer/lib/gstreamer-1.0/libgstvideoanalytics.so

(gst-inspect-1.0:3087): GStreamer-WARNING **: 15:23:37.680: Failed to load plugin '/opt/intel/dlstreamer/lib/gstreamer-1.0/libgstvideoanalytics.so': libopencv_imgproc.so.410: cannot open shared object file: No such file or directory
Could not load plugin file: Opening module failed: libopencv_imgproc.so.410: cannot open shared object file: No such file or directory

- /opt/intel/dlstreamer/lib/gstreamer-1.0$ ldd /opt/intel/dlstreamer/lib/gstreamer-1.0/libgstvideoanalytics.so
        linux-vdso.so.1 (0x00007ffc083a6000)
        libgstreamer-1.0.so.0 => /lib/x86_64-linux-gnu/libgstreamer-1.0.so.0 (0x000079133cb4a000)
        libgstdlstreamer_bins.so (0x000079133caa6000)
        libopencv_imgproc.so.410 => not found
        libopencv_core.so.410 => not found
        libopenvino.so.2430 => /opt/intel/openvino_2024.3/runtime/lib/intel64/libopenvino.so.2430 (0x000079133bc00000)
        libgstaudio-1.0.so.0 => /lib/x86_64-linux-gnu/libgstaudio-1.0.so.0 (0x000079133ca22000)
        libgstanalytics-1.0.so.0 => not found
        libgstallocators-1.0.so.0 => /lib/x86_64-linux-gnu/libgstallocators-1.0.so.0 (0x000079133bbf9000)
        libdlstreamer_gst.so => not found
        libgstvideo-1.0.so.0 => /lib/x86_64-linux-gnu/libgstvideo-1.0.so.0 (0x000079133bb34000)
        libgstbase-1.0.so.0 => /lib/x86_64-linux-gnu/libgstbase-1.0.so.0 (0x000079133baaf000)
        libdlstreamer_gst_meta.so => not found
        libgobject-2.0.so.0 => /lib/x86_64-linux-gnu/libgobject-2.0.so.0 (0x000079133ba4f000)
        libglib-2.0.so.0 => /lib/x86_64-linux-gnu/libglib-2.0.so.0 (0x000079133b915000)
        libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x000079133b600000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x000079133b82e000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x000079133b5e0000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x000079133b200000)
        /lib64/ld-linux-x86-64.so.2 (0x000079133ce9d000)
        libgmodule-2.0.so.0 => /lib/x86_64-linux-gnu/libgmodule-2.0.so.0 (0x000079133b5d9000)
        libunwind.so.8 => /lib/x86_64-linux-gnu/libunwind.so.8 (0x000079133b5be000)
        libdw.so.1 => /lib/x86_64-linux-gnu/libdw.so.1 (0x000079133b512000)
        libtbb.so.12 => /lib/x86_64-linux-gnu/libtbb.so.12 (0x000079133b4c2000)
        libgsttag-1.0.so.0 => /lib/x86_64-linux-gnu/libgsttag-1.0.so.0 (0x000079133b47e000)
        liborc-0.4.so.0 => /lib/x86_64-linux-gnu/liborc-0.4.so.0 (0x000079133b17b000)
        libffi.so.8 => /lib/x86_64-linux-gnu/libffi.so.8 (0x000079133b471000)
        libpcre.so.3 => /lib/x86_64-linux-gnu/libpcre.so.3 (0x000079133b105000)
        liblzma.so.5 => /lib/x86_64-linux-gnu/liblzma.so.5 (0x000079133b446000)
        libelf.so.1 => /lib/x86_64-linux-gnu/libelf.so.1 (0x000079133b0e7000)
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x000079133b0cb000)
        libbz2.so.1.0 => /lib/x86_64-linux-gnu/libbz2.so.1.0 (0x000079133b431000)

- source /opt/intel/openvino_2024/setupvars.sh
[setupvars.sh] OpenVINO environment initialized

- source /opt/intel/oneapi/setvars.sh

:: WARNING: setvars.sh has already been run. Skipping re-execution.
   To force a re-execution of setvars.sh, use the '--force' option.
   Using '--force' can result in excessive use of your environment variables.

usage: source setvars.sh [--force] [--config=file] [--help] [...]
  --force        Force setvars.sh to re-run, doing so may overload environment.
  --config=file  Customize env vars using a setvars.sh configuration file.
  --help         Display this help message and exit.
  ...            Additional args are passed to individual env/vars.sh scripts
                 and should follow this script's arguments.

  Some POSIX shells do not accept command-line options. In that case, you can pass
  command-line options via the SETVARS_ARGS environment variable. For example:

  $ SETVARS_ARGS="ia32 --config=config.txt" ; export SETVARS_ARGS
  $ . path/to/setvars.sh

  The SETVARS_ARGS environment variable is cleared on exiting setvars.sh.


- source /opt/intel/dlstreamer/setupvars.sh
[setupvars.sh] GStreamer 1.24.6 framework initialized
[setupvars.sh] GStreamer 1.24.6 plugins path initialized
[setupvars.sh] Intel(R) DL Streamer environment initialized

**Comment by pmalatyn** [comment]
I agree with @brmarkus if you followed our instruction you saw that checking gvadetect details is last step that verifies installation.  As for now I would also go into direction of different versions of the files/DLS on your machine that are causing problems. I saw in a logs GStreamer 1.24.6 so I'm assuming that you are using latest (2024.1.2) version was this a case also before your problems?

**Comment by sharmav2-intc** [comment]
Thanks for you inputs @brmarkus  @pmalatyn , one strange thing I'm facing is I'm able to decode with gst-launch commands but only issue I'm facing with gvadetect commands, can you please share if there is any alternative command for gvadetect e.g. command:

gst-launch-1.0 filesrc location=/home/intel/workspace/Classroom_1080p30_noB.265 ! h265parse ! vah265dec ! vapostproc ! gvadetect model=/home/intel/models//intel/face-detection-adas-0001/FP32/face-detection-adas-0001.xml device=GPU pre-process-backend=va-surface-sharing batch-size=8 ! queue ! gvaclassify model=/home/intel/models//intel/age-gender-recognition-retail-0013/FP32/age-gender-recognition-retail-0013.xml model-proc=/opt/intel/dlstreamer/samples/gstreamer/gst_launch/face_detection_and_classification/model_proc/age-gender-recognition-retail-0013.json device=GPU ! queue ! gvaclassify model=/home/intel/models//intel/emotions-recognition-retail-0003/FP32/emotions-recognition-retail-0003.xml model-proc=/opt/intel/dlstreamer/samples/gstreamer/gst_launch/face_detection_and_classification/model_proc/emotions-recognition-retail-0003.json device=GPU ! queue ! gvaclassify model=/home/intel/models//intel/landmarks-regression-retail-0009/FP32/landmarks-regression-retail-0009.xml model-proc=/opt/intel/dlstreamer/samples/gstreamer/gst_launch/face_detection_and_classification/model_proc/landmarks-regression-retail-0009.json device=GPU ! gvafpscounter ! queue ! fpsdisplaysink fps-update-interval=1000 video-sink=fakesink  text-overlay=false sync=false -v

**Comment by pmalatyn** [comment]
we identified installation issue related to option 1, working on resolving it, will update you, as a w/a you can use Docker image (option 2). Sorry for any inconvenience it may cause

**Comment by sharmav2-intc** [comment]
sure @pmalatyn please let me know how to fix this

**Comment by pmalatyn** [comment]
we just published corrected documentation, please check it: https://dlstreamer.github.io/get_started/install/install_guide_ubuntu.html

**Comment by sharmav2-intc** [comment]
thanks for the update @pmalatyn , can you please elaborate on what has been changed in the guide and what the actual issue was, just for understanding

**Comment by pmalatyn** [comment]
due to introduction of Ubuntu 24.04 we had to upgrade version of OpenCV and this caused issues with 22.04 version, so for 22.04 extra steps were added - I checked it now and it is still not published, please give the system some time to process the changes :)

**Comment by pmalatyn** [comment]
changes are visible now

**Comment by sharmav2-intc** [comment]
great, thanks for the info and quick fix

**Comment by pmalatyn** [comment]
I suppose that installation is working now as I do not see further feedback, will close this issue, please reopen it in case of any failures during installation

**Comment by pinkisaharan** [comment]
Hi,
I tried enabling dlstreamer on Ubuntu 24.04 and facing few issues.
1. The very first one was, while installing the dependencies using below command, and it shows that level-zero is not installable. Tried installing it standalone, error msg is copied below:
sudo apt-get update && sudo apt-get install intel-level-zero-gpu level-zero 

_

intel@intel:~/workspace$ sudo apt install level-zero
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package level-zero is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  libze1

E: Package 'level-zero' has no installation candidate
intel@intel:~/workspace$ sudo apt install libzel
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package libzel
intel@intel:~/workspace$

_
2. 2nd issue faced was related to debian package intel-dlstreamer-dpcpp_2024.320_ubuntu_24.04_amd64.deb
while installing all the deb packages this package gave error as it showed dependency on level-zero
Below is the error msg:

python3-intel-dlstreamer is already the newest version (2024.320).
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 intel-dlstreamer-dpcpp : Depends: level-zero but it is not installable
E: Unable to correct problems, you have held broken packages.

3. 3rd one is again issue with gvadetect. Below is the error message:

intel@intel:~/install_drivers/dlstreamer$ gst-inspect-1.0 gvadetect

** (gst-plugin-scanner:23660): CRITICAL **: 04:20:08.140: gi.repository.Gst is no dict
Traceback (most recent call last):
  File "/opt/intel/dlstreamer/lib/gstreamer-1.0/python/python_object_association.py", line 20, in <module>
    from deep_sort_realtime.deep_sort.tracker import Tracker
ModuleNotFoundError: No module named 'deep_sort_realtime'
Traceback (most recent call last):
  File "/opt/intel/dlstreamer/lib/gstreamer-1.0/python/pytorch_tensor_inference.py", line 16, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
No such element or plugin 'gvadetect'
intel@intel:~/install_drivers/dlstreamer$

Please guide me in resolving the issue as its high priority for me to make dlstreamer working to get some workload results.
Thank you

**Comment by pinkisaharan** [comment]
Hi @brmarkus 

I am using Raptorlake S, Intel iGPU, with ubuntu 24.04, kernel version 6.8

I have done the installation on fresh image only.. that message "python3-intel-dlstreamer is already the newest version (2024.320)" came here because I reran the install command to capture the error message for posting here which I forgot to copy earlier and console got closed.

Yes I followed the steps from this installation link only.

**Comment by pinkisaharan** [comment]
Hi,

Can I please get any update on this issue from your side. Is it working for you on Ubuntu 24.04

Thank you

**Comment by pinkisaharan** [comment]
Hi,

I tried with latest release also on a fresh ubuntu installation and still facing same failure. 
One basic query here: Is level-zero package must for dlstreamer? if yes, the very basic issue is this package is not at all available for Ubuntu 24.04. 
While installing dlstreamer with prebuilt debian packages, installation fails with this same error that package installation depends on level-zero which is a non installable option for 24.04. But there must be some replacement then if this package can't be displayed. 
Should I start a new thread for Ubuntu 24.04 issues?
Please help me in debugging this issue as this has become a show stopper for my work

Thank you

**Comment by pinkisaharan** [comment]
Yes I followed all the steps from this link and this has the GPG key steps in it.. https://dlstreamer.github.io/dev_guide/advanced_install/advanced_install_guide_prebuilt.html

There is a pre-requisite step where we install dependencies, there itself level-zero installation fails
I am not sure why this is happening but I am just running the basic commands mentioned in installation guide.

intel@intel:~$ sudo apt-get install intel-level-zero-gpu level-zero
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package level-zero is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  libze1

E: Package 'level-zero' has no installation candidate
intel@intel:~$

**Comment by pinkisaharan** [comment]
Ok I will give it a try this way. Thank you for the inputs. I will come back with my results.

**Comment by pinkisaharan** [comment]
Hi I tried twice on fresh installed Ubuntu 24.04 with media driver, oneapi, opencv all installed before trying dlstreamer but still getting this same error

The following packages have unmet dependencies:
 intel-dlstreamer-dpcpp : Depends: level-zero but it is not installable
                          Depends: intel-oneapi-compiler-dpcpp-cpp-runtime but it is not installable
E: Unable to correct problems, you have held broken packages.

Can anyone please try on your end. this issue has become a big blocker for my work and needs immediate addressing

While installing media driver dependencies also got this error. Tried all one by one also and all "xorg xorg-dev openbox libx11-dev libgl1-mesa-glx" these gave same error. Though vainfo is detecting all encoder decoders properly and media driver also installed properly, but just mentioning for reference as this is working fine on Ubuntu 22.04
intel@intel:~/dlstreamer$ sudo apt install autoconf libtool libdrm-dev xorg xorg-dev openbox libx11-dev libgl1-mesa-glx
[sudo] password for intel:
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package libgl1-mesa-glx is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'libgl1-mesa-glx' has no installation candidate

What can be the proxy setting that you mentioned earlier. Please share what to check for that

**Comment by pinkisaharan** [comment]
Hi @brmarkus 

Thank you for all the help. Dlstreamer and openvino are working fine with latest deb packages and we are able to run workloads as well. 

Thank you
